#!/usr/bin/env python3
# =============================================================================
# kwin_restore.py
# Generated by: Claude Sonnet 4.6
#
# Restores a window layout from a YAML snapshot file produced by
# kwin_snapshot.py.
#
# Startup confirmation dialogs ("Ready to restore?" / "Watch for pop-ups")
# are handled by the `restore` bash wrapper script in the same directory.
# Run `restore` rather than invoking this script directly in normal use.
# Direct invocation still works; the startup dialogs are simply skipped.
#
# The restore runs in five separate phases to give KWin time to settle
# its internal state between operations:
#
#   Phase 1 — Launch & identify
#     For each entry: launch the app (or find the existing window), wait for
#     the window to appear, and record its internalId.  Tray apps are launched
#     and immediately skipped (no window expected).
#
#   Phase 2 — Move
#     For each identified window: unmaximize, move to the target desktop, move
#     to the target screen.  No state changes (maximize/minimize) yet.
#     Followed by a settle delay (default 3s) to let KWin commit all the
#     screen re-associations before state operations begin.
#
#   Phase 3 — Finalise
#     For each identified window: unminimize (restores the window from the
#     minimize applied at the end of Phase 2), then apply the target state
#     (maximize / tile / minimize / raise).  unmaximize() is NOT called here —
#     Phase 1 already handled it; see note in finalise_entry().
#     Set onAllDesktops last.
#
#   Phase 4 — Input actions
#     For each placed window that has input_actions defined: use the XDG
#     RemoteDesktop portal session (opened before Phase 1) to inject the
#     specified keystrokes and mouse events.  The progress window is hidden
#     for the duration of this phase.
#
#   Phase 5 — Re-tile all-desktops windows
#     For each window placed with on_all_desktops=True: loop over every
#     virtual desktop in order, switch to it, re-apply move_to_screen and
#     the tile/maximize state.  This corrects the KWin-side drift where tile
#     position is stored per (window, desktop) pair, so a window placed on
#     desktop 1 and then set to on_all_desktops will be correctly tiled only
#     on desktop 1.  After the loop the originally active desktop is restored.
#     Phase 5 is skipped silently if no all-desktops windows were placed.
#
# USAGE:
#   restore [OPTIONS] [APP]          (preferred — runs startup dialogs first)
#   python3 kwin_restore.py [OPTIONS] [APP]
#
# ARGUMENTS:
#   APP                 (optional) Restore only this one application.
#                       Accepts an app alias or resourceClass from the snapshot.
#                       Equivalent to --filter APP.
#
# OPTIONS:
#   --setup FILE        Snapshot file to restore from.
#                       If omitted, reads default_setup from config.yaml and
#                       searches in: current dir, ~/.config/wayland-desktop/,
#                       snapshot_dir.
#   --config FILE       Alternate config file
#   --log FILE          Tee all output to FILE (ANSI codes stripped).
#                       Parent directories are created as needed.
#   --dry-run           Show what would be done without launching or moving
#   --no-launch         Skip launching apps; only place already-open windows
#   --timeout SECS      Per-app launch timeout (default: 30)
#   --delay MS          Milliseconds between app launches in phase 1
#                       (default: 500)
#   --settle-delay SECS Seconds to wait between phase 2 (move) and phase 3
#                       (finalise), allowing KWin to commit all screen
#                       re-associations before maximize operations begin
#                       (default: 3.0)
#   --phase5-delay MS   Milliseconds to wait after each desktop switch in
#                       phase 5 (default: 400)
#   --filter APP        Only restore entries matching this alias or
#                       resourceClass (repeatable; combined with APP positional)
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import argparse
import os
import re
import shlex
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kwin_lib.config        import load_config, KWinConfig
from kwin_lib.models        import DesktopInfo, ScreenInfo
from kwin_lib.snapshot      import LayoutSnapshot, SnapshotEntry
from kwin_lib.session_state import SessionState, make_entry
from kwin_lib               import KWinSession, WindowProbe, WindowInfo
from kwin_lib.progress_window import ProgressWindow, ProgressWindowLogger
from kwin_lib.input_injection  import InputInjector, run_input_actions, parse_actions
from kwin_lib.secret_service   import SecretService
from kwin_lib.click_indicator  import ClickIndicator


# ── Log tee (--log FILE) ─────────────────────────────────────────────────────

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


class _TeeWriter:
    """
    Wraps a stream so every write goes to both the original stream and a log
    file.  ANSI colour codes are stripped before writing to the log file.
    """
    def __init__(self, original, logfile):
        self._orig = original
        self._log  = logfile

    def write(self, data: str) -> int:
        self._orig.write(data)
        self._orig.flush()
        self._log.write(_ANSI_RE.sub("", data))
        self._log.flush()
        return len(data)

    def flush(self) -> None:
        self._orig.flush()
        self._log.flush()

    def isatty(self) -> bool:
        return self._orig.isatty()

    def fileno(self) -> int:
        return self._orig.fileno()


def _install_log_tee(log_path: str) -> None:
    """
    Redirect stdout and stderr so all output is written to both the terminal
    and log_path.  ANSI colour codes are stripped in the log file.
    A header with the current timestamp and the full command line is written
    at the start of the file.
    """
    import datetime
    p = Path(log_path).expanduser()
    p.parent.mkdir(parents=True, exist_ok=True)
    fh = p.open("w", encoding="utf-8")
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cmd = " ".join(sys.argv)
    fh.write(f"# wayland-desktop restore log — {now}\n")
    fh.write(f"# Command: {cmd}\n\n")
    fh.flush()
    sys.stdout = _TeeWriter(sys.stdout, fh)   # type: ignore[assignment]
    sys.stderr = _TeeWriter(sys.stderr, fh)   # type: ignore[assignment]


# ── Colour helpers ────────────────────────────────────────────────────────────

class C:
    _t = sys.stdout.isatty()
    BOLD   = "\033[1m"  if _t else ""; CYAN   = "\033[36m" if _t else ""
    GREEN  = "\033[32m" if _t else ""; YELLOW = "\033[33m" if _t else ""
    RED    = "\033[31m" if _t else ""; RESET  = "\033[0m"  if _t else ""

def info(m):  print(f"{C.CYAN}[INFO ] {C.RESET}{m}")
def ok(m):    print(f"{C.GREEN}[OK   ] {C.RESET}{m}")
def warn(m):  print(f"{C.YELLOW}[WARN ] {C.RESET}{m}")
def error(m): print(f"{C.RED}[ERROR] {C.RESET}{m}", file=sys.stderr)
def head(m):  print(f"\n{C.BOLD}{C.CYAN}{m}{C.RESET}")


class RestoreResult:
    """
    Records the state of one snapshot entry as it moves through the three
    restore phases.

    Status values:
      pending     - initial state
      identified  - phase 1 complete: window found/launched, internalId known
      launched    - tray app launched; phases 2 and 3 are skipped
      skipped     - nothing to do (dry-run, --no-launch miss, etc.)
      placed      - phase 3 complete: window moved and finalised
      failed      - error in any phase
    """
    def __init__(self, entry: SnapshotEntry) -> None:
        self.entry              = entry
        self.status             = "pending"
        self.reason             = ""
        self.uuid               = ""   # internalId — set in phase 1
        self.pid                = 0    # PID of launched process (0 = pre-existing)

        # Resolved placement targets — populated in phase 1, used in phases 2 & 3
        self.target_desktop:    DesktopInfo | None = None
        self.target_screen:     ScreenInfo  | None = None
        self.wants_all:         bool               = False
        self.canonical_desktop: str                = ""
        self.canonical_screen:  str                = ""

    def identified(self, uuid: str, pid: int) -> "RestoreResult":
        """Phase 1 complete: window found or launched."""
        self.status = "identified"
        self.uuid   = uuid
        self.pid    = pid
        return self

    def launched(self, pid: int) -> "RestoreResult":
        """Tray app launched — no window to move or finalise."""
        self.status = "launched"
        self.pid    = pid
        return self

    def placed(self) -> "RestoreResult":
        """Phase 3 complete: window fully placed."""
        self.status = "placed"
        return self

    def skipped(self, reason: str) -> "RestoreResult":
        self.status = "skipped"
        self.reason = reason
        return self

    def failed(self, reason: str) -> "RestoreResult":
        self.status = "failed"
        self.reason = reason
        return self


# == Phase 1: Launch & identify ===============================================

def launch_entry(
    entry:     SnapshotEntry,
    kwin:      KWinSession,
    cfg:       KWinConfig,
    no_launch: bool,
    timeout:   float,
    dry_run:   bool,
    logger:    ProgressWindowLogger,
) -> RestoreResult:
    """
    Phase 1: launch the application (if needed) and identify its window.

    On success, returns a result with status="identified" and uuid set.
    Also resolves and stores the target desktop and screen on the result
    so that phases 2 and 3 can use them without repeating the lookup.

    Tray apps (ignore_window=True) are launched here and returned with
    status="launched" -- phases 2 and 3 will skip them.
    """
    result = RestoreResult(entry)

    label = f"{entry.app_alias!r} -> {entry.desktop_alias!r}/{entry.screen_alias!r}"
    if entry.ignore_window:
        label = f"{entry.app_alias!r}  [tray app -- no window]"
    logger.info(f"  {label}")

    # -- Tray-only apps -------------------------------------------------------
    if entry.ignore_window:
        if dry_run:
            logger.info(f"    [dry-run] Would launch tray app: {entry.command!r}")
            return result.skipped("dry-run")
        if no_launch:
            return result.skipped("--no-launch: tray app skipped")
        command = shlex.split(entry.command) if entry.command else []
        if not command:
            return result.failed("no command defined -- edit snapshot file")
        try:
            proc = subprocess.Popen(
                command,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            logger.ok(f"    Tray app launched (PID {proc.pid})")
            return result.launched(proc.pid)
        except Exception as exc:
            return result.failed(f"launch failed: {exc}")

    # -- Resolve placement targets --------------------------------------------
    wants_all = entry.on_all_desktops
    canonical_desktop = (
        cfg.ALL_DESKTOPS
        if wants_all
        else cfg.resolve_desktop(entry.desktop_alias or entry.desktop)
    )
    canonical_screen = cfg.resolve_screen(entry.screen_alias or entry.screen)

    result.wants_all          = wants_all
    result.canonical_desktop  = canonical_desktop
    result.canonical_screen   = canonical_screen

    if not wants_all and canonical_desktop:
        try:
            result.target_desktop = kwin.desktops.find_desktop(name=canonical_desktop)
            if result.target_desktop is None:
                logger.warn(f"    Desktop {canonical_desktop!r} not found")
        except Exception as exc:
            logger.warn(f"    Desktop lookup failed: {exc}")

    try:
        result.target_screen = kwin.desktops.find_screen(name=canonical_screen)
        if result.target_screen is None and canonical_screen:
            logger.warn(f"    Screen {canonical_screen!r} not found")
    except Exception as exc:
        logger.warn(f"    Screen lookup failed: {exc}")

    # -- Dry-run output -------------------------------------------------------
    if dry_run:
        action = "reuse existing" if entry.single_instance else "launch"
        if no_launch:
            action = "find existing (--no-launch)"
        desktop_label = "* (all desktops)" if wants_all else repr(canonical_desktop)
        logger.info(f"    [dry-run] Would {action}: {entry.command!r}")
        logger.info(f"    target  : desktop={desktop_label}  screen={canonical_screen!r}")
        maximize = entry.maximized and not entry.minimized
        state = "maximize" if maximize else ("minimize" if entry.minimized else "raise")
        logger.info(f"    finalise: {state}")
        return result.skipped("dry-run")

    # -- Find or launch the window --------------------------------------------
    if no_launch:
        wins = kwin.windows.find_by_class(entry.resource_class)
        if not wins:
            return result.skipped(
                f"--no-launch: no open window with "
                f"resourceClass={entry.resource_class!r}"
            )
        uuid = wins[0].internalId
        logger.info(f"    Found existing window: {uuid[:20]}...")
        return result.identified(uuid, 0)

    relaunch = not entry.single_instance
    try:
        probe = WindowProbe(
            timeout_secs = timeout,
            filter_class = entry.resource_class,
            stop_count   = 1,
            relaunch     = relaunch,
        )
        command = shlex.split(entry.command) if entry.command else []
        if not command:
            return result.failed("no command defined -- edit snapshot file")

        pid, wins = probe.run(command)
        if not wins:
            return result.failed(
                f"no window detected within {timeout}s "
                f"(command: {entry.command!r})"
            )
        uuid   = wins[0].internalId
        action = "pre-existing" if pid == 0 else f"launched PID {pid}"
        logger.ok(f"    Window identified: {uuid[:20]}...  ({action})")
        return result.identified(uuid, pid)

    except RuntimeError as exc:
        return result.failed(str(exc))


# == Phase 2: Move ============================================================

def move_entry(
    result:  RestoreResult,
    kwin:    KWinSession,
    dry_run: bool,
    logger:  ProgressWindowLogger,
) -> None:
    """
    Phase 2: move the window to its target desktop and screen.

    No maximize or state changes -- those happen in phase 3 after the
    settle delay.  Mutates result in place; sets status="failed" on error.
    """
    if result.status != "identified":
        return   # tray app, skipped, or already failed -- nothing to do

    entry = result.entry
    logger.info(f"  Moving: {entry.app_alias!r}")

    if dry_run:
        desktop_label = ("* (all desktops)" if result.wants_all
                         else repr(result.canonical_desktop))
        logger.info(f"    [dry-run] Would move to desktop={desktop_label} "
                    f"screen={result.canonical_screen!r}")
        return

    try:
        t0 = time.monotonic()

        try:
            kwin.windows.unminimize(result.uuid)
        except Exception as exc:
            logger.warn(f"    Could not unminimize before move (non-fatal): {exc}")

        if not result.wants_all and result.target_desktop is not None:
            kwin.windows.move_to_desktop(result.uuid, result.target_desktop)

        if result.target_screen is not None:
            kwin.windows.move_to_screen(result.uuid, result.target_screen)

        try:
            kwin.windows.minimize(result.uuid)
        except Exception as exc:
            logger.warn(f"    Could not re-minimize after move (non-fatal): {exc}")

        elapsed_ms = int((time.monotonic() - t0) * 1000)
        desktop_label = ("all desktops" if result.wants_all
                         else repr(result.canonical_desktop))
        logger.ok(f"    Moved to {desktop_label}/{result.canonical_screen!r}"
                  f"  ({elapsed_ms}ms)")

    except RuntimeError as exc:
        logger.warn(f"    Move failed: {exc}")
        result.failed(f"move: {exc}")


# == Phase 3: Finalise ========================================================

def finalise_entry(
    result:  RestoreResult,
    kwin:    KWinSession,
    cfg:     KWinConfig,
    dry_run: bool,
    logger:  ProgressWindowLogger,
) -> None:
    """
    Phase 3: apply final state and set onAllDesktops.

    The window arrives here already minimized (from the end of Phase 2).
    Four cases, in priority order:

    1. minimize  — target state is minimized; window is already there.
                   Set onAllDesktops if needed and return — no KWin calls.

    2. maximize  — maximize() implicitly unminimizes, so no prior unminimize
                   is needed.  Then raise_window() to bring it to the front.
                   The geometry check is skipped; maximize fills the screen
                   regardless of current size.

    3. tile      — unminimize, shrink check (safety net for oversized
                   windows), tile, raise_window().

    4. raise     — unminimize, shrink check, raise_window().

    raise_window() is called after every non-minimize operation so the
    window is guaranteed to be on top after placement.

    unmaximize() is intentionally NOT called here.  Phase 1 already calls
    unmaximize() + minimize() immediately after each window is identified,
    giving the app the full duration of Phase 2 and the settle delay to
    process the compositor configure event.  The window is therefore already
    in a normal unmaximized state by the time Phase 3 runs.

    onAllDesktops is set last — see ADR-260321-03.
    """
    if result.status != "identified":
        return   # nothing to finalise

    entry    = result.entry
    maximize = entry.maximized and not entry.minimized
    minimize = entry.minimized
    tile_pos = entry.tile.strip() if entry.tile else ""
    logger.info(f"  Finalising: {entry.app_alias!r}")

    if dry_run:
        if minimize:
            state = "minimize (already minimized — no-op)"
        elif maximize:
            state = "maximize + raise"
        elif tile_pos:
            state = f"tile {tile_pos!r} + raise"
        else:
            state = "raise"
        logger.info(f"    [dry-run] Would: {state}")
        if result.wants_all:
            logger.info(f"    [dry-run] Would set onAllDesktops")
        result.placed()
        return

    try:
        t0 = time.monotonic()

        # -- Case 1: already minimized — nothing to do -----------------------
        if minimize:
            if result.wants_all:
                kwin.windows.set_on_all_desktops(result.uuid, True)
            elapsed_ms = int((time.monotonic() - t0) * 1000)
            logger.ok(f"    Finalised [minimized — no-op]"
                      + ("  [all desktops]" if result.wants_all else "")
                      + f"  ({elapsed_ms}ms)")
            result.placed()
            return

        # -- Case 2: maximize — KWin implicitly unminimizes ------------------
        if maximize:
            # Brief settle before maximize: the window arrives here minimized
            # and KWin needs a moment to be ready to process setMaximize()
            # after the 3-second settle delay expires.  Without this, the
            # first window processed can land in a state where KWin records
            # it as maximized but the compositor has not yet applied the
            # geometry (visible as a small window with a restore button).
            time.sleep(0.25)
            kwin.windows.maximize(result.uuid)
            kwin.windows.raise_window(result.uuid)
            kwin.windows.ensure_maximized(
                result.uuid,
                width_tolerance  = cfg.maximize_width_tolerance,
                height_tolerance = cfg.maximize_height_tolerance,
                logger           = logger,
            )
            state = "maximized"

        else:
            # Cases 3 & 4: unminimize first, then shrink check
            kwin.windows.unminimize(result.uuid)

            try:
                geom = kwin.windows.get_screen_geometry(result.uuid)
                if geom.get("win_w", 0) > geom.get("scr_w", 9999):
                    logger.warn(f"    Window wider than screen — shrinking horizontally")
                if geom.get("win_h", 0) > geom.get("scr_h", 9999):
                    logger.warn(f"    Window taller than screen — shrinking vertically")
                if (geom.get("win_w", 0) > geom.get("scr_w", 9999) or
                        geom.get("win_h", 0) > geom.get("scr_h", 9999)):
                    kwin.windows.shrink_to_screen(result.uuid)
            except Exception:
                pass

            # -- Case 3: tile ------------------------------------------------
            if tile_pos:
                kwin.windows.tile(result.uuid, tile_pos)
                state = f"tiled-{tile_pos}"

            # -- Case 4: raise (default) -------------------------------------
            else:
                state = "raised"

            kwin.windows.raise_window(result.uuid)

        if result.wants_all:
            kwin.windows.set_on_all_desktops(result.uuid, True)

        elapsed_ms = int((time.monotonic() - t0) * 1000)
        logger.ok(f"    Finalised [{state}]"
                  + ("  [all desktops]" if result.wants_all else "")
                  + f"  ({elapsed_ms}ms)")
        result.placed()

    except RuntimeError as exc:
        logger.warn(f"    Finalise failed: {exc}")
        result.failed(f"finalise: {exc}")


# == Setup file resolution ====================================================

def resolve_setup_file(
    setup_arg: str | None,
    cfg:       KWinConfig,
) -> Path | None:
    """
    Locate the snapshot/setup file to restore from.

    If --setup was given explicitly, expand ~ and use it directly.
    Returns None if the path does not exist (caller emits the error).

    If --setup was not given, fall back to cfg.default_setup.  That value
    is treated as a bare filename (not a path) and searched in order:
      1. Current working directory
      2. ~/.config/wayland-desktop/    (the config directory)
      3. cfg.snapshot_dir       (the snapshots directory)

    Returns None if the file cannot be found in any of these locations.
    """
    if setup_arg:
        p = Path(setup_arg).expanduser()
        return p if p.exists() else None

    if not cfg.default_setup:
        return None

    filename   = cfg.default_setup
    config_dir = Path("~/.config/wayland-desktop").expanduser()
    for candidate in [
        Path(filename),
        config_dir / filename,
        cfg.snapshot_dir / filename,
    ]:
        resolved = candidate.expanduser().resolve()
        if resolved.exists():
            return resolved

    return None


# == Main =====================================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="kwin_restore.py",
        description="Restore a window layout from a kwin_snapshot.py YAML file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("app", nargs="?", default=None, metavar="APP",
        help="Restore only this app (alias or resourceClass). "
             "Equivalent to --filter APP.")
    parser.add_argument("--setup",         default="", metavar="FILE",
        help="Snapshot file to restore from.")
    parser.add_argument("--config",        default="", metavar="FILE")
    parser.add_argument("--log",           default="", metavar="FILE",
        help="Tee all output to FILE (ANSI codes stripped). "
             "Parent directories are created as needed.")
    parser.add_argument("--dry-run",       action="store_true",
        help="Show what would be done without launching or moving anything")
    parser.add_argument("--no-launch",     action="store_true",
        help="Skip launching apps; only place already-open windows")
    parser.add_argument("--timeout",       type=float, default=30.0,
        metavar="SECS", help="Per-app launch timeout in seconds (default: 30)")
    parser.add_argument("--delay",         type=int,   default=500,
        metavar="MS",
        help="Delay between app launches in phase 1, ms (default: 500)")
    parser.add_argument("--settle-delay",  type=float, default=3.0,
        metavar="SECS",
        help="Seconds to wait between phase 2 (move) and phase 3 (finalise) "
             "so KWin can commit screen re-associations before maximize "
             "(default: 3.0)")
    parser.add_argument("--verbose",       action="store_true",
        help="Print a debug line after every KWin script call "
             "(op name, result dict, elapsed ms)")
    parser.add_argument("--show-window",   action="store_true",
        help="Show the progress window regardless of the config setting")
    parser.add_argument("--no-window",     action="store_true",
        help="Suppress the progress window regardless of the config setting")
    parser.add_argument("--show-clicks",   action="store_true",
        help="Show click indicator dots at each injected pointer position "
             "during phase 4 input injection. Hidden by default.")
    parser.add_argument("--phase5-delay",  type=int,   default=400,
        metavar="MS",
        help="Milliseconds to wait after each desktop switch in phase 5 "
             "(re-tile all-desktops windows on every virtual desktop) "
             "(default: 400)")
    parser.add_argument("--filter",        action="append", default=[],
        dest="filters", metavar="APP",
        help="Only restore this app alias or resourceClass (repeatable)")
    args = parser.parse_args()

    # -- Install log tee (must be first, so all subsequent output is captured)
    if args.log:
        _install_log_tee(args.log)

    cfg = load_config(args.config or None)

    # -- Resolve setup file ---------------------------------------------------
    snapshot_path = resolve_setup_file(args.setup or None, cfg)

    if snapshot_path is None:
        if args.setup:
            error(f"Setup file not found: {args.setup}")
        elif cfg.default_setup:
            error(
                f"Default setup file {cfg.default_setup!r} not found. "
                f"Searched: current dir, ~/.config/wayland-desktop/, "
                f"{cfg.snapshot_dir}/"
            )
        else:
            error(
                "No setup file specified and no default_setup configured. "
                "Use --setup <file.yaml> or set default_setup in config.yaml."
            )
        sys.exit(1)

    try:
        snapshot = LayoutSnapshot.load(snapshot_path)
    except Exception as exc:
        error(f"Cannot load snapshot: {exc}")
        sys.exit(1)

    # -- Determine whether to show the progress window -----------------------
    # progress_window is a screen alias string (non-blank = show) or "" (off).
    # --show-window forces the window on; --no-window suppresses it.
    # Screen placement (move + keepBelow) is applied only when the config
    # provides a valid screen alias — not when --show-window alone is used.
    use_window = bool(cfg.progress_window)   # True when alias is non-blank
    if args.show_window: use_window = True
    if args.no_window:   use_window = False

    # Resolve and validate the screen alias when one is configured.
    # This is done before spawning the window so we fail fast on bad config.
    progress_screen_connector: str | None = None
    if cfg.progress_window:
        try:
            progress_screen_connector = cfg.get_progress_window_screen()
        except ValueError as exc:
            error(str(exc))
            sys.exit(1)

    # -- Create window and logger (logger works with win=None too) ------------
    win: ProgressWindow | None = None
    if use_window:
        win = ProgressWindow()
        win.show(initial_verbose=args.verbose)
        # If a screen alias was configured, move the window there and set
        # keepBelow so it stays behind other windows during the restore.
        if progress_screen_connector:
            win.move_to_screen(progress_screen_connector)
    logger = ProgressWindowLogger(win)

    # -- Build filter set -----------------------------------------------------
    filters: list[str] = list(args.filters)
    if args.app:
        filters.append(args.app)

    logger.head("=== KWin Layout Restore =============================================")
    logger.info(f"Setup         : {snapshot_path}")
    logger.info(f"Captured      : {snapshot.timestamp}  ({snapshot.hostname})")
    logger.info(f"Windows       : {len(snapshot.entries)}")
    logger.info(f"Settle delay  : {args.settle_delay}s")
    if args.dry_run:    logger.info("Mode          : DRY RUN (nothing will be changed)")
    if args.no_launch:  logger.info("Mode          : --no-launch (existing windows only)")
    if args.verbose:    logger.info("Mode          : --verbose (per-op debug output)")
    if use_window:      logger.info("Mode          : progress window active")
    if args.log:        logger.info(f"Log file      : {args.log}")
    if filters:         logger.info(f"Filter        : {filters}")

    entries = snapshot.entries
    if filters:
        resolved = set()
        for f in filters:
            resolved.add(cfg.resolve_resource_class(f))
            resolved.add(f)
        entries = [
            e for e in entries
            if e.resource_class in resolved
            or e.app_alias in resolved
            or any(f.lower() in e.resource_class.lower()
                   or f.lower() in e.app_alias.lower()
                   for f in filters)
        ]
        logger.info(f"Filtered to {len(entries)} entries")

    if not entries:
        logger.warn("No entries to restore.")
        if win:
            win.set_complete()
            win.wait_for_close()
        sys.exit(0)

    # -- Scan filtered entries for action / password tokens -------------------
    # Done after filtering so we only open connections for what will actually
    # run.  has_action_entries, has_pass_tokens, and pass_keys are all computed
    # in one pass so there is no duplicate scanning.
    has_action_entries = False
    has_pass_tokens    = False
    pass_keys: set[str] = set()
    if not args.dry_run:
        for e in entries:
            dsl = (e.input_actions or "").strip()
            if not dsl:
                continue
            has_action_entries = True
            if cfg.use_secret_service:
                try:
                    for a in parse_actions(dsl):
                        if a.kind == "password":
                            has_pass_tokens = True
                            pass_keys.add(a.params["key"])
                except Exception:
                    pass

    # -- Open InputInjector early so any auth dialog appears now, not mid-run -
    # If the saved restore token is stale the KDE "Allow wayland-desktop to control
    # input?" authorization dialog will appear here — before Phase 1 — at a
    # known, calm moment, alongside the Secret Service priming step below.
    injector: InputInjector | None = None
    if has_action_entries:
        try:
            injector = InputInjector()
            injector.open()
            logger.info("Input injection: portal session opened")
        except RuntimeError as exc:
            logger.warn(
                f"Input injection: cannot open portal session — "
                f"phase 4 will be skipped: {exc}"
            )
            injector = None

    # -- Prime Secret Service connection --------------------------------------
    # Connection opened now — before Phase 1 — so KeePassXC approval dialogs
    # appear at a known, calm moment.  Stays open through Phase 4.
    secret_service: SecretService | None = None
    if has_pass_tokens and pass_keys:
        try:
            secret_service = SecretService()
            secret_service.open()
            logger.info("Secret Service: connection opened")
            for key in sorted(pass_keys):
                try:
                    secret_service.get_password(key)
                    logger.info(f"Secret Service: primed {key!r}")
                except Exception as exc:
                    logger.warn(
                        f"Secret Service: could not prime {key!r}: {exc}"
                    )
        except RuntimeError as exc:
            logger.warn(
                f"Secret Service: cannot open — {{PASS}} tokens will "
                f"fail: {exc}"
            )
            secret_service = None

    session_state   = SessionState.load()
    results: list[RestoreResult] = []
    launch_delay_s  = args.delay / 1000.0

    # Initialised here (before the outer try:) so the except/finally handlers
    # below can always reference it, even if the exception fires before the
    # inner assignment inside the with-block.
    restore_desktop_id: str | None = None

    try:
        with KWinSession(verbose=args.verbose) as kwin:

            # Remember which desktop is active so we can restore it at the end.
            try:
                restore_desktop_id = kwin.desktops.current_desktop_id()
            except Exception:
                restore_desktop_id = None

            # -- Phase 1: Launch & identify -----------------------------------
            logger.head("Phase 1 -- Launching and identifying windows")
            for i, entry in enumerate(entries):

                # Sync verbose flag from window checkbox on each iteration
                if win and win.is_showing():
                    args.verbose = win.is_verbose()
                    kwin.windows.set_verbose(args.verbose)

                # Check for abort request from window
                if win and win.is_abort_requested():
                    logger.warn("Abort requested — stopping after phase 1")
                    break

                r = launch_entry(
                    entry     = entry,
                    kwin      = kwin,
                    cfg       = cfg,
                    no_launch = args.no_launch,
                    timeout   = args.timeout,
                    dry_run   = args.dry_run,
                    logger    = logger,
                )
                results.append(r)

                # Unmaximize then minimize immediately after identifying.
                # Unmaximizing first clears any geometry the app self-applied
                # during its own session restore (e.g. Brave restoring to its
                # own full-screen size).  This gives the app the entire duration
                # of phases 2 and the settle delay to process the compositor's
                # configure event before we touch it again in phase 3.
                if r.status == "identified" and not args.dry_run:
                    try:
                        kwin.windows.unmaximize(r.uuid)
                    except Exception:
                        pass  # non-fatal
                    try:
                        kwin.windows.minimize(r.uuid)
                    except Exception:
                        pass  # non-fatal -- phase 2 will still move it

                if i < len(entries) - 1 and not args.dry_run:
                    time.sleep(launch_delay_s)

            n_identified = sum(1 for r in results if r.status == "identified")
            logger.ok(f"Phase 1 complete: {n_identified} window(s) identified")

            # Write session state immediately after phase 1
            if not args.dry_run:
                for r in results:
                    if r.status == "identified" and r.uuid and r.entry.tracking_uuid:
                        session_state.upsert(make_entry(
                            tracking_uuid  = r.entry.tracking_uuid,
                            internal_id    = r.uuid,
                            app_alias      = r.entry.app_alias,
                            resource_class = r.entry.resource_class,
                            desktop        = r.entry.desktop_alias or r.entry.desktop,
                            screen         = r.entry.screen_alias  or r.entry.screen,
                        ))
                try:
                    session_state.save()
                    n_saved = sum(1 for r in results if r.status == "identified"
                                  and r.uuid and r.entry.tracking_uuid)
                    if n_saved:
                        logger.info(f"Session state written: {n_saved} "
                                    f"entr{'y' if n_saved == 1 else 'ies'} "
                                    f"({len(session_state._entries)} total in file)")
                except OSError as exc:
                    logger.warn(f"Could not write session state file: {exc} (non-fatal)")

            # -- Phase 2: Move all windows ------------------------------------
            logger.head("Phase 2 -- Moving windows to target desktops and screens")
            for r in results:

                if win and win.is_showing():
                    args.verbose = win.is_verbose()
                    kwin.windows.set_verbose(args.verbose)

                if win and win.is_abort_requested():
                    logger.warn("Abort requested — stopping after phase 2")
                    break

                move_entry(result=r, kwin=kwin, dry_run=args.dry_run,
                           logger=logger)

            n_moved = sum(1 for r in results if r.status == "identified")
            logger.ok(f"Phase 2 complete: {n_moved} window(s) moved")

            # -- Settle delay -------------------------------------------------
            if not args.dry_run and args.settle_delay > 0:
                logger.info(
                    f"Waiting {args.settle_delay}s for KWin to settle "
                    f"screen re-associations ..."
                )
                time.sleep(args.settle_delay)

            # -- Phase 3: Finalise state --------------------------------------
            logger.head("Phase 3 -- Finalising window state (maximize / minimize / raise)")
            for r in results:

                if win and win.is_showing():
                    args.verbose = win.is_verbose()
                    kwin.windows.set_verbose(args.verbose)

                if win and win.is_abort_requested():
                    logger.warn("Abort requested — stopping after phase 3")
                    break

                finalise_entry(result=r, kwin=kwin, cfg=cfg, dry_run=args.dry_run,
                               logger=logger)

            # -- Restore the originally active desktop (after phase 3) --------
            # Done here — before phase 4 input injection — so the user's
            # desktop is in a known state before any input actions fire.
            if restore_desktop_id and not args.dry_run:
                try:
                    restore_desktop = kwin.desktops.find_desktop(
                        id=restore_desktop_id
                    )
                    if restore_desktop:
                        kwin.desktops.switch_to_desktop(
                            restore_desktop, settle_s=0.2
                        )
                        logger.info(
                            f"Restored active desktop: "
                            f"{restore_desktop.name!r}"
                        )
                except Exception as exc:
                    logger.warn(
                        f"Could not restore original desktop: {exc} "
                        f"(non-fatal)"
                    )

            # -- Phase 4: Input actions ---------------------------------------
            action_entries = [
                r for r in results
                if r.status == "placed"
                and (r.entry.input_actions or "").strip()
            ]
            if action_entries:
                logger.head("Phase 4 -- Input actions")
                if args.dry_run:
                    for r in action_entries:
                        run_input_actions(r, None, kwin, logger, dry_run=True)
                elif injector is None:
                    logger.warn(
                        "  Portal session unavailable — skipping phase 4"
                    )
                else:
                    # Start click indicator only if --show-clicks is given
                    click_indicator = None
                    if args.show_clicks:
                        try:
                            click_indicator = ClickIndicator()
                            click_indicator.start()
                        except Exception as exc:
                            logger.warn(
                                f"  Cannot start click indicator (non-fatal): {exc}"
                            )
                            click_indicator = None
                    # Hide the progress window for the duration of phase 4 so
                    # it cannot obscure KeePassXC dialogs or tool windows.
                    logger.hide_window()
                    try:
                        for r in action_entries:
                            if win and win.is_showing():
                                args.verbose = win.is_verbose()
                                kwin.windows.set_verbose(args.verbose)
                            if win and win.is_abort_requested():
                                logger.warn(
                                    "Abort requested — stopping phase 4")
                                break
                            run_input_actions(
                                r, injector, kwin, logger, dry_run=False,
                                secret_service=secret_service,
                                click_indicator=click_indicator)
                    finally:
                        logger.show_window()
                        if click_indicator is not None:
                            click_indicator.stop()

            # Minimize the progress window going into Phase 5.  Phase 5
            # switches virtual desktops and re-tiles windows — the progress
            # window would appear on every desktop and interfere.  It is
            # raised again after Phase 5 completes.
            if win and win.is_showing():
                win.minimize_window()

            # -- Phase 5: Re-tile all-desktops windows ------------------------
            all_desktop_results = [
                r for r in results
                if r.status == "placed" and r.entry.on_all_desktops
            ]
            if all_desktop_results and not args.dry_run:
                logger.head(
                    "Phase 5 -- Re-tiling all-desktops windows on every desktop"
                )

                all_desktops = kwin.desktops.list_desktops()
                phase5_settle = args.phase5_delay / 1000.0

                for desktop in all_desktops:
                    if win and win.is_abort_requested():
                        logger.warn("Abort requested — stopping phase 5")
                        break

                    has_work = any(
                        r.entry.on_all_desktops for r in all_desktop_results
                    )
                    if not has_work:
                        continue

                    logger.info(
                        f"  Desktop: {desktop.name!r} ({desktop.number})"
                    )
                    try:
                        kwin.desktops.switch_to_desktop(
                            desktop, settle_s=phase5_settle
                        )
                    except RuntimeError as exc:
                        logger.warn(
                            f"    Could not switch to desktop "
                            f"{desktop.name!r}: {exc} — skipping"
                        )
                        continue

                    for r in all_desktop_results:
                        if win and win.is_abort_requested():
                            break

                        entry = r.entry
                        logger.info(f"    Re-tiling: {entry.app_alias!r}")

                        try:
                            if r.target_screen is not None:
                                kwin.windows.move_to_screen(
                                    r.uuid, r.target_screen
                                )

                            tile_pos = entry.tile.strip() if entry.tile else ""
                            maximize = entry.maximized and not entry.minimized
                            minimize = entry.minimized

                            if tile_pos:
                                kwin.windows.tile(r.uuid, tile_pos)
                                state = f"tiled-{tile_pos}"
                            elif maximize:
                                kwin.windows.maximize(r.uuid)
                                kwin.windows.ensure_maximized(
                                    r.uuid,
                                    width_tolerance  = cfg.maximize_width_tolerance,
                                    height_tolerance = cfg.maximize_height_tolerance,
                                    logger           = logger,
                                )
                                state = "maximized"
                            elif minimize:
                                kwin.windows.minimize(r.uuid)
                                state = "minimized"
                            else:
                                kwin.windows.raise_window(r.uuid)
                                state = "raised"

                            logger.ok(
                                f"      [{state}] on {desktop.name!r}"
                            )

                        except RuntimeError as exc:
                            logger.warn(
                                f"      Re-tile failed on {desktop.name!r}: "
                                f"{exc} (non-fatal)"
                            )

            elif all_desktop_results and args.dry_run:
                logger.head(
                    "Phase 5 -- Re-tiling all-desktops windows on every desktop"
                )
                logger.info(
                    f"  [dry-run] Would re-tile {len(all_desktop_results)} "
                    f"all-desktops window(s) across all virtual desktops"
                )
                for r in all_desktop_results:
                    tile_pos = r.entry.tile.strip() if r.entry.tile else ""
                    maximize = r.entry.maximized and not r.entry.minimized
                    state = (f"tile {tile_pos!r}" if tile_pos
                             else "maximize" if maximize else "raise")
                    logger.info(
                        f"    {r.entry.app_alias!r}  screen="
                        f"{r.canonical_screen!r}  state={state}"
                    )

            # -- Return to the desktop that was active when the script started -
            # Done last so all phases (including phase 4 input actions, which may
            # switch desktops) have fully completed before we move the user back.
            # raise_to_front() turns off keepBelow, unminimizes, and raises the
            # progress window so the user can see the completion summary.
            # It also covers the case where phase 4 left the window hidden.
            if win and win.is_showing():
                win.raise_to_front()
            else:
                # No progress window — still flush any dangling hide_window call.
                logger.show_window()
            if restore_desktop_id and not args.dry_run:
                try:
                    restore_desktop = kwin.desktops.find_desktop(
                        id=restore_desktop_id
                    )
                    if restore_desktop:
                        kwin.desktops.switch_to_desktop(
                            restore_desktop, settle_s=0.2
                        )
                        logger.info(
                            f"Returned to starting desktop: "
                            f"{restore_desktop.name!r}"
                        )
                except Exception as exc:
                    logger.warn(
                        f"Could not return to starting desktop: {exc} "
                        f"(non-fatal)"
                    )

    except RuntimeError as exc:
        # Ensure the progress window is visible before showing the error —
        # phase 4 may have hidden it and the exception aborted the raise_to_front
        # call that normally follows.  Turn off keepBelow so the window is
        # not buried behind the error state.
        if win and win.is_showing():
            win.raise_to_front()
        else:
            logger.show_window()
        # Best-effort: try to return the user to the desktop they started on.
        # Opens a fresh KWin session because the one inside the with-block may
        # already be closed or in an unknown state at this point.
        if restore_desktop_id:
            try:
                with KWinSession(verbose=False) as _kwin_err:
                    _d = _kwin_err.desktops.find_desktop(id=restore_desktop_id)
                    if _d:
                        _kwin_err.desktops.switch_to_desktop(_d, settle_s=0.2)
            except Exception:
                pass  # non-fatal: error reporting below takes priority
        logger.error(f"Session error: {exc}")
        if win:
            win.set_complete()
            win.wait_for_close()
        sys.exit(1)
    finally:
        if injector is not None:
            try:
                injector.close()
            except Exception:
                pass
            injector = None
        if secret_service is not None:
            secret_service.close()
            secret_service = None

    # -- Summary --------------------------------------------------------------
    logger.head("Summary")
    placed   = [r for r in results if r.status == "placed"]
    launched = [r for r in results if r.status == "launched"]
    skipped  = [r for r in results if r.status == "skipped"]
    failed   = [r for r in results if r.status == "failed"]

    logger.ok(f"Placed   : {len(placed)}")
    if launched:
        logger.ok(f"Launched : {len(launched)}  (tray apps -- no window placed)")
        for r in launched:
            logger.info(f"  {r.entry.app_alias}  PID {r.pid}")
    if skipped:
        logger.info(f"Skipped  : {len(skipped)}")
        for r in skipped:
            logger.info(f"  {r.entry.app_alias}: {r.reason}")
    if failed:
        logger.warn(f"Failed   : {len(failed)}")
        for r in failed:
            logger.warn(f"  {r.entry.app_alias}: {r.reason}")

    if not failed:
        logger.head("=== Done ============================================================")

    # -- Close progress window ------------------------------------------------
    if win and win.is_showing():
        win.set_complete()
        win.wait_for_close()

    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()




