#!/usr/bin/env python3
# =============================================================================
# kwin_snapshot.py
# Generated by: Claude Sonnet 4.6
#
# Captures the current KDE Plasma window layout to a YAML file.
# System windows (plasmashell, ibus, etc.) are excluded by default.
#
# The captured layout is always printed to stdout as YAML so you can
# review it immediately.  Use --dry-run to skip saving to disk.
#
# USAGE:
#   python3 kwin_snapshot.py [OPTIONS]
#
# OPTIONS:
#   --output FILE     Write snapshot to FILE
#                     (default: ~/.config/wayland-desktop/snapshots/YYYY-MM-DD_HHMM.yaml)
#   --include-system  Include compositor/system windows in snapshot
#   --config FILE     Use alternate config file
#                     (default: ~/.config/wayland-desktop/config.yaml)
#   --show-config     Print loaded aliases and exit
#   --dry-run         Print snapshot YAML to stdout without saving to disk
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kwin_lib.config   import load_config, KWinConfig
from kwin_lib.snapshot import capture_snapshot, SnapshotEntry, LayoutSnapshot
from kwin_lib          import KWinSession


class C:
    _t = sys.stdout.isatty()
    BOLD="\033[1m" if _t else ""; CYAN="\033[36m" if _t else ""
    GREEN="\033[32m" if _t else ""; YELLOW="\033[33m" if _t else ""
    RED="\033[31m" if _t else ""; RESET="\033[0m" if _t else ""

def info(m):  print(f"{C.CYAN}[INFO ] {C.RESET}{m}")
def ok(m):    print(f"{C.GREEN}[OK   ] {C.RESET}{m}")
def warn(m):  print(f"{C.YELLOW}[WARN ] {C.RESET}{m}")
def error(m): print(f"{C.RED}[ERROR] {C.RESET}{m}", file=sys.stderr)
def head(m):  print(f"\n{C.BOLD}{C.CYAN}{m}{C.RESET}")



def main() -> None:
    parser = argparse.ArgumentParser(
        prog="kwin_snapshot.py",
        description="Capture the current KDE Plasma window layout to YAML.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--output",         default="", metavar="FILE",
        help="Output file path (default: auto-named in snapshot_dir)")
    parser.add_argument("--include-system", action="store_true",
        help="Include system/compositor windows (plasmashell, etc.)")
    parser.add_argument("--config",         default="", metavar="FILE",
        help="Alternate config file path")
    parser.add_argument("--show-config",    action="store_true",
        help="Print loaded config aliases and exit")
    parser.add_argument("--dry-run",        action="store_true",
        help="Print snapshot to stdout without saving to file")
    args = parser.parse_args()

    # Load config
    cfg = load_config(args.config or None)

    if args.show_config:
        head("Loaded configuration")
        cfg.dump()
        sys.exit(0)

    head("═══ KWin Layout Snapshot ════════════════════════════════════════")
    info(f"Config : {args.config or '~/.config/wayland-desktop/config.yaml'}")
    if args.include_system:
        info("Mode   : all windows (including system)")
    else:
        info(f"Mode   : user windows only "
             f"({len(cfg.system_classes)} system classes filtered)")

    # Open KWin session and capture
    try:
        with KWinSession() as kwin:
            info("Enumerating windows via KWin scripting ...")
            snapshot = capture_snapshot(
                runner         = kwin._runner,
                config         = cfg,
                include_system = args.include_system,
            )
    except RuntimeError as exc:
        error(str(exc))
        sys.exit(1)

    count = len(snapshot.entries)
    ok(f"Captured {count} window(s)  [{snapshot.timestamp}]")

    if count == 0:
        warn("No user windows found. "
             "Use --include-system to see all windows.")
        sys.exit(0)

    # Always print the full YAML text to stdout.  This is the primary
    # human-readable output; the abbreviated summary of old versions has been
    # replaced by the YAML itself, which is more useful for review and diffing.
    head("Window layout (YAML)")
    yaml_text = snapshot.to_yaml_text(config=cfg)
    print(yaml_text)

    if args.dry_run:
        info("Dry run — output not saved to disk.")
        head("═══ Done ════════════════════════════════════════════════════════")
        print()
        sys.exit(0)

    # Determine output path
    if args.output:
        out_path = Path(args.output).expanduser()
    else:
        cfg.snapshot_dir.mkdir(parents=True, exist_ok=True)
        ts       = datetime.now().strftime("%Y-%m-%d_%H%M")
        out_path = cfg.snapshot_dir / f"{ts}.yaml"

    snapshot.save(out_path, config=cfg)
    ok(f"Snapshot saved to: {out_path}")

    head("═══ Done ════════════════════════════════════════════════════════")
    print()
    info("To restore this layout:")
    info(f"  python3 kwin_restore.py --setup {out_path}")


if __name__ == "__main__":
    main()
