#!/usr/bin/env python3
# =============================================================================
# kwin_probe.py  —  CLI wrapper for kwin_lib.WindowProbe
# Generated by: Claude Sonnet 4.6
#
# USAGE:
#   python3 kwin_probe.py [OPTIONS] -- <command> [args...]
#
# OPTIONS:
#   --timeout   SECS   Wait this long for a new window       (default: 30)
#   --class     NAME   Only report windows with this resourceClass
#   --count     N      Stop after N new windows              (default: 1)
#   --all              Collect all windows until timeout
#   --relaunch         Launch even if app is already running
#   --output    FILE   Write JSON report to FILE
#   --quiet            Suppress progress output
#
# EXAMPLES:
#   python3 kwin_probe.py -- thunderbird
#   python3 kwin_probe.py --class obsidian --timeout 45 -- obsidian
#   python3 kwin_probe.py --all --output report.json -- thunderbird
#   python3 kwin_probe.py --relaunch -- thunderbird
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from datetime import datetime

# Add parent directory to path so we can import kwin_lib from same folder
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kwin_lib import WindowProbe, WindowInfo


class C:
    _t     = sys.stdout.isatty()
    BOLD   = "\033[1m"  if _t else ""
    CYAN   = "\033[36m" if _t else ""
    GREEN  = "\033[32m" if _t else ""
    YELLOW = "\033[33m" if _t else ""
    RED    = "\033[31m" if _t else ""
    RESET  = "\033[0m"  if _t else ""

def info(m):  print(f"{C.CYAN}[INFO ] {C.RESET}{m}")
def ok(m):    print(f"{C.GREEN}[OK   ] {C.RESET}{m}")
def warn(m):  print(f"{C.YELLOW}[WARN ] {C.RESET}{m}")
def error(m): print(f"{C.RED}[ERROR] {C.RESET}{m}", file=sys.stderr)
def head(m):  print(f"\n{C.BOLD}{C.CYAN}{m}{C.RESET}")


_KEY_FIELDS = [
    ("resourceClass",   "resourceClass    (primary match key)"),
    ("resourceName",    "resourceName"),
    ("caption",         "caption / title"),
    ("desktopFileName", "desktopFileName  (app-id)"),
    ("pid",             "pid"),
    ("desktop_name",    "desktop"),
    ("screen_name",     "screen"),
    ("x",               "x"),
    ("y",               "y"),
    ("width",           "width"),
    ("height",          "height"),
    ("minimized",       "minimized"),
    ("maximized",       "maximized"),
    ("onAllDesktops",   "onAllDesktops"),
]


def print_window(win: WindowInfo) -> None:
    label = " [pre-existing]" if win.is_pre_existing else f" +{win.detected_ms}ms"
    print(f"\n{C.BOLD}Window: {win.internalId}{label}{C.RESET}")
    print("─" * 62)
    for attr, label_ in _KEY_FIELDS:
        val    = getattr(win, attr, "")
        colour = C.GREEN if val not in ("", 0, False) else C.YELLOW
        print(f"  {colour}{label_:<44}{C.RESET} {val!r}")
    if win.extra:
        print(f"\n  {C.BOLD}Extra:{C.RESET}")
        for k, v in sorted(win.extra.items()):
            print(f"  {k:<44} {v!r}")


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="kwin_probe.py",
        description="Identify windows created by a launched program.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--timeout",  type=float, default=30.0)
    parser.add_argument("--class",    dest="filter_class", default="")
    parser.add_argument("--count",    type=int, default=1)
    parser.add_argument("--all",      dest="collect_all", action="store_true")
    parser.add_argument("--relaunch", action="store_true")
    parser.add_argument("--output",   default="")
    parser.add_argument("--quiet",    action="store_true")
    parser.add_argument("command",    nargs=argparse.REMAINDER)
    args = parser.parse_args()

    cmd = args.command
    if cmd and cmd[0] == "--": cmd = cmd[1:]
    if not cmd:
        parser.print_help(); sys.exit(1)

    if not args.quiet:
        head("═══ KWin Window Probe ══════════════════════════════════════════")
        info(f"Command : {' '.join(cmd)}")
        info(f"Timeout : {args.timeout}s")
        if args.filter_class: info(f"Filter  : {args.filter_class}")
        if args.relaunch:     info("Relaunch: yes")

    probe = WindowProbe(
        timeout_secs = args.timeout,
        filter_class = args.filter_class,
        stop_count   = 0 if args.collect_all else args.count,
        relaunch     = args.relaunch,
    )

    try:
        app_pid, windows = probe.run(cmd)
    except RuntimeError as exc:
        error(str(exc)); sys.exit(1)

    if not windows:
        error(f"No windows detected within {args.timeout}s.")
        warn("  • App may already be running (use --relaunch)")
        warn("  • --class filter may be too strict")
        warn("  • Startup may exceed --timeout")
        sys.exit(1)

    if not args.quiet:
        head("Results")
        for win in windows:
            print_window(win)

        head("Summary")
        pid_str = "(pre-existing)" if app_pid == 0 else str(app_pid)
        info(f"PID              : {pid_str}")
        info(f"Windows detected : {len(windows)}")
        print()
        info("internalId handles:")
        for win in windows:
            marker = " [pre-existing]" if win.is_pre_existing else ""
            print(f"    {win.internalId}  [{win.display_name()}]{marker}")

    if args.output:
        report = {
            "timestamp": datetime.now().isoformat(),
            "command":   cmd,
            "pid":       app_pid,
            "windows": [
                {**{k: v for k, v in asdict(w).items() if k != "extra"},
                 "extra": w.extra}
                for w in windows
            ],
        }
        with open(args.output, "w") as f:
            json.dump(report, f, indent=2, default=str)
        if not args.quiet:
            ok(f"Report: {args.output}")

    if not args.quiet:
        head("═══ Done ════════════════════════════════════════════════════════")


if __name__ == "__main__":
    main()
