#!/usr/bin/env python3
# =============================================================================
# wayland/kwin_secret_service.py
# Generated by: Claude Sonnet 4.6
#
# Utility script for the org.freedesktop.secrets Secret Service protocol.
# Provides list and lookup operations against the default collection.
# Intended for use by restore-user-before and other shell scripts that need
# to retrieve secrets from KeePassXC at restore time.
#
# For the full diagnostic version (including introspect), see
# docs/dev/kwin_secret_service.py.
#
# COMMANDS
# --------
#   list [--verbose]
#       List all items in the default collection.  Prints label and UserName
#       attribute for each entry, sorted by label.  With --verbose, prints
#       all attributes for each item.  No secrets are fetched.
#
#   lookup <key>
#       Look up the item whose label exactly matches <key> and print its
#       secret to stdout.  <key> is the entry title as shown in KeePassXC.
#
# USAGE
# -----
#   python3 wayland/kwin_secret_service.py list
#   python3 wayland/kwin_secret_service.py list --verbose
#   python3 wayland/kwin_secret_service.py lookup "router-admin"
#
#   # Via the secret-service wrapper (from the project root):
#   secret-service list
#   secret-service lookup "router-admin"
#
# OPTIONS
#   --collection PATH   Override the collection D-Bus path.
#                       Default: /org/freedesktop/secrets/aliases/default
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import argparse
import sys

from gi.repository import GLib, Gio


# ── D-Bus constants ───────────────────────────────────────────────────────────

SS_BUS      = "org.freedesktop.secrets"
SS_PATH     = "/org/freedesktop/secrets"
SS_SERVICE  = "org.freedesktop.Secret.Service"
SS_COLL     = "org.freedesktop.Secret.Collection"
SS_ITEM     = "org.freedesktop.Secret.Item"
SS_SESSION  = "org.freedesktop.Secret.Session"
SS_PROMPT   = "org.freedesktop.Secret.Prompt"

DEFAULT_COLLECTION = "/org/freedesktop/secrets/aliases/default"


# ── Proxy helpers ─────────────────────────────────────────────────────────────

def _make_proxy(iface: str, path: str) -> Gio.DBusProxy:
    return Gio.DBusProxy.new_for_bus_sync(
        Gio.BusType.SESSION,
        Gio.DBusProxyFlags.NONE,
        None,
        SS_BUS, path, iface,
        None,
    )


def _call(proxy: Gio.DBusProxy, method: str, args: GLib.Variant) -> GLib.Variant:
    return proxy.call_sync(method, args, Gio.DBusCallFlags.NONE, -1, None)


def _get_prop(proxy: Gio.DBusProxy, prop: str):
    cached = proxy.get_cached_property(prop)
    if cached is not None:
        return cached.unpack()
    result = proxy.call_sync(
        "org.freedesktop.DBus.Properties.Get",
        GLib.Variant("(ss)", (proxy.get_interface_name(), prop)),
        Gio.DBusCallFlags.NONE, -1, None,
    )
    return result[0]


def _prompt_if_needed(prompt_path: str) -> None:
    if prompt_path == "/":
        return
    loop   = GLib.MainLoop()
    result = [None]
    conn   = Gio.bus_get_sync(Gio.BusType.SESSION, None)

    def on_completed(conn2, sender, obj_path, iface, signal, params, user_data):
        dismissed, _res = params
        result[0] = dismissed
        loop.quit()

    sub_id = conn.signal_subscribe(
        SS_BUS, SS_PROMPT, "Completed",
        prompt_path, None,
        Gio.DBusSignalFlags.NONE,
        on_completed, None,
    )
    prompt_proxy = _make_proxy(SS_PROMPT, prompt_path)
    _call(prompt_proxy, "Prompt", GLib.Variant("(s)", ("",)))
    GLib.timeout_add_seconds(60, loop.quit)
    loop.run()
    conn.signal_unsubscribe(sub_id)
    if result[0]:
        raise RuntimeError("Unlock prompt was dismissed.")


def _open_session() -> tuple[Gio.DBusProxy, str]:
    svc    = _make_proxy(SS_SERVICE, SS_PATH)
    result = _call(svc, "OpenSession",
                   GLib.Variant("(sv)", ("plain", GLib.Variant("s", ""))))
    return svc, result[1]


def _unlock_collection(svc: Gio.DBusProxy, collection_path: str) -> None:
    coll   = _make_proxy(SS_COLL, collection_path)
    locked = _get_prop(coll, "Locked")
    if not locked:
        return
    result      = _call(svc, "Unlock", GLib.Variant("(ao)", ([collection_path],)))
    prompt_path = result[1]
    _prompt_if_needed(prompt_path)
    coll2 = _make_proxy(SS_COLL, collection_path)
    if _get_prop(coll2, "Locked"):
        raise RuntimeError(
            "Collection is still locked after unlock attempt. "
            "KeePassXC may be closed or the unlock was cancelled."
        )


def _list_item_paths(collection_path: str) -> list[str]:
    return list(_get_prop(_make_proxy(SS_COLL, collection_path), "Items"))


def _item_label(item_path: str) -> str:
    return str(_get_prop(_make_proxy(SS_ITEM, item_path), "Label"))


def _item_attributes(item_path: str) -> dict[str, str]:
    raw = _get_prop(_make_proxy(SS_ITEM, item_path), "Attributes")
    return dict(raw) if raw else {}


def _item_secret(item_path: str, session_path: str, svc: Gio.DBusProxy) -> str:
    item = _make_proxy(SS_ITEM, item_path)
    try:
        result = _call(item, "GetSecret", GLib.Variant("(o)", (session_path,)))
    except Exception as exc:
        if "IsLocked" not in str(exc):
            raise
        # Per-item unlock required (KeePassXC approval dialog)
        unlock_result = _call(svc, "Unlock", GLib.Variant("(ao)", ([item_path],)))
        _prompt_if_needed(unlock_result[1])
        item   = _make_proxy(SS_ITEM, item_path)
        result = _call(item, "GetSecret", GLib.Variant("(o)", (session_path,)))
    return bytes(result[0][2]).decode("utf-8")


def _close_session(session_path: str) -> None:
    try:
        _call(_make_proxy(SS_SESSION, session_path), "Close", GLib.Variant("()", ()))
    except Exception:
        pass


# ── Commands ──────────────────────────────────────────────────────────────────

def cmd_list(args) -> int:
    """List all items in the collection with their labels."""
    collection_path = args.collection
    try:
        svc, session_path = _open_session()
    except Exception as exc:
        print(f"ERROR opening session: {exc}", file=sys.stderr)
        return 1
    try:
        _unlock_collection(svc, collection_path)
    except Exception as exc:
        print(f"ERROR unlocking collection: {exc}", file=sys.stderr)
        return 1
    try:
        item_paths = _list_item_paths(collection_path)
    except Exception as exc:
        print(f"ERROR listing items: {exc}", file=sys.stderr)
        return 1

    items = []
    for path in item_paths:
        try:
            label = _item_label(path)
            attrs = _item_attributes(path)
            items.append((label, attrs, path))
        except Exception as exc:
            items.append((f"(unreadable: {exc})", {}, path))
    items.sort(key=lambda t: t[0].lower())

    for label, attrs, path in items:
        if args.verbose:
            print(f"  Label   : {label}")
            print(f"  Path    : {path}")
            for k, v in sorted(attrs.items()):
                print(f"  {k:<12}: {v}")
            print()
        else:
            username = attrs.get("UserName", attrs.get("username", ""))
            user_part = f"  (UserName: {username})" if username else ""
            print(f"  {label}{user_part}")

    _close_session(session_path)
    return 0


def cmd_lookup(args) -> int:
    """Look up a secret by label and print it to stdout."""
    key             = args.key
    collection_path = args.collection
    try:
        svc, session_path = _open_session()
    except Exception as exc:
        print(f"ERROR opening session: {exc}", file=sys.stderr)
        return 1
    try:
        _unlock_collection(svc, collection_path)
        item_paths = _list_item_paths(collection_path)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        _close_session(session_path)
        return 1

    found_path = None
    for path in item_paths:
        try:
            if _item_label(path) == key:
                found_path = path
                break
        except Exception:
            continue

    if found_path is None:
        print(f"ERROR: No item found with label {key!r}.", file=sys.stderr)
        print("Use 'list' to see all available labels.", file=sys.stderr)
        _close_session(session_path)
        return 1

    try:
        secret = _item_secret(found_path, session_path, svc)
    except Exception as exc:
        print(f"ERROR retrieving secret: {exc}", file=sys.stderr)
        _close_session(session_path)
        return 1

    # Print secret with no trailing newline so callers can capture it cleanly
    # via: SECRET=$(secret-service lookup "key")
    print(secret, end="")
    _close_session(session_path)
    return 0


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="kwin_secret_service.py",
        description="List and look up secrets from the org.freedesktop.secrets Secret Service.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Commands:\n"
            "  list                List all item labels (and UserName attributes)\n"
            "  lookup <key>        Print the secret for the item with label <key>\n"
            "\n"
            "Note: lookup prints the secret with no trailing newline, suitable\n"
            "for shell capture:  SECRET=$(secret-service lookup \"my-key\")\n"
        ),
    )
    parser.add_argument(
        "--collection", default=DEFAULT_COLLECTION, metavar="PATH",
        help=f"Collection D-Bus path (default: {DEFAULT_COLLECTION})",
    )
    sub = parser.add_subparsers(dest="command")

    p_list = sub.add_parser("list", help="List all items")
    p_list.add_argument("--verbose", action="store_true",
                        help="Show all attributes for each item")

    p_lookup = sub.add_parser("lookup", help="Look up a secret by label")
    p_lookup.add_argument("key", help="Entry label (title) to look up")

    args = parser.parse_args()
    if args.command is None:
        parser.print_help()
        sys.exit(0)

    sys.exit({"list": cmd_list, "lookup": cmd_lookup}[args.command](args))


if __name__ == "__main__":
    main()
