#!/usr/bin/env python3
# =============================================================================
# kwin_realign.py
# Generated by: Claude Sonnet 4.6
#
# Drift-correction utility for wayland-desktop.
#
# Corrects window placement without launching any applications.  All windows
# must already be running; this script only moves and re-tiles them.
#
# Motivation
# ----------
# KWin stores tile position per (window, desktop) pair.  When kwin_restore.py
# places a window on desktop 1 and then sets it to appear on all desktops,
# the tile is correct on desktop 1 but may differ on other desktops.  After
# an extended period of inactivity (e.g. screen-lock unlock) the window
# positions can drift further.  This script corrects that drift.
#
# Loop structure
# --------------
# Outer loop: every virtual desktop in order.
#   Inner loop: every entry in the YAML setup file.
#     Default mode (no --all-apps):
#       Process only entries with on_all_desktops=True.
#     --all-apps mode:
#       Process entries with on_all_desktops=True on every desktop.
#       Process entries with a specific desktop only when the outer loop
#       is on that matching desktop.
#
# For each (desktop, entry) pair:
#   1. switch_to_desktop(desktop)
#   2. Locate the live window (session_state → resourceClass scan fallback)
#   3. move_to_screen to anchor the window on the correct screen
#   4. Apply tile / maximize / minimize / raise
#
# After all desktops are processed, the originally active desktop is restored.
#
# Window lookup
# -------------
# Primary:  session_state.json  tracking_uuid → internalId
#           Written by kwin_restore.py after phase 1; stale entries from
#           previous boot sessions are pruned automatically.
# Fallback: live scan of workspace.windowList() by resourceClass
#           Used when session state is absent, empty, or missing this entry.
#
# USAGE:
#   python3 kwin_realign.py [OPTIONS] [APP]
#
# ARGUMENTS:
#   APP                 (optional) Realign only this app (alias or
#                       resourceClass).  Equivalent to --filter APP.
#
# OPTIONS:
#   --setup FILE        Snapshot/setup file to read from.
#                       If omitted, reads default_setup from config.yaml and
#                       searches in: current dir, ~/.config/wayland-desktop/,
#                       snapshot_dir.
#   --config FILE       Alternate config file
#   --all-apps          Process all entries, not just on_all_desktops ones.
#                       Single-desktop entries are processed only on their
#                       own desktop.
#   --dry-run           Show what would be done without changing anything
#   --settle-delay MS   Milliseconds to wait after each desktop switch
#                       (default: 400)
#   --verbose           Print a debug line after every KWin script call
#   --show-window       Show the progress window regardless of config
#   --no-window         Suppress the progress window regardless of config
#   --filter APP        Only realign this app alias or resourceClass
#                       (repeatable; combined with APP positional)
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import argparse
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kwin_lib.config        import load_config, KWinConfig
from kwin_lib.models        import DesktopInfo, ScreenInfo
from kwin_lib.snapshot      import LayoutSnapshot, SnapshotEntry
from kwin_lib.session_state import SessionState
from kwin_lib               import KWinSession
from kwin_lib.progress_window import ProgressWindow, ProgressWindowLogger


# ── Screen resolution record ──────────────────────────────────────────────────

@dataclass
class ScreenResolution:
    """
    Holds all three stages of screen name resolution for one YAML entry,
    so that verbose logging can show the full alias → canonical → KWin chain
    at every point where a screen decision is made.

    yaml_value  : raw value from the YAML file (e.g. "main", "HDMI-A-2")
    canonical   : name after cfg.resolve_screen() (e.g. "HDMI-A-2")
                  equals yaml_value if no alias mapping exists
    screen_info : ScreenInfo found by kwin.desktops.find_screen(), or None
                  if KWin reports no screen with that connector name
    """
    yaml_value:  str
    canonical:   str
    screen_info: ScreenInfo | None


# ── Colour helpers ────────────────────────────────────────────────────────────

class C:
    _t = sys.stdout.isatty()
    BOLD   = "\033[1m"  if _t else ""; CYAN  = "\033[36m" if _t else ""
    GREEN  = "\033[32m" if _t else ""; YELLOW= "\033[33m" if _t else ""
    RED    = "\033[31m" if _t else ""; RESET = "\033[0m"  if _t else ""

def info(m):  print(f"{C.CYAN}[INFO ] {C.RESET}{m}")
def ok(m):    print(f"{C.GREEN}[OK   ] {C.RESET}{m}")
def warn(m):  print(f"{C.YELLOW}[WARN ] {C.RESET}{m}")
def error(m): print(f"{C.RED}[ERROR] {C.RESET}{m}", file=sys.stderr)
def head(m):  print(f"\n{C.BOLD}{C.CYAN}{m}{C.RESET}")


# ── Window lookup ─────────────────────────────────────────────────────────────

def find_window(
    entry:         SnapshotEntry,
    session_state: SessionState,
    kwin:          KWinSession,
    logger:        ProgressWindowLogger,
) -> str | None:
    """
    Locate the live internalId for a snapshot entry.

    Tries session_state first (tracking_uuid → internalId), then falls
    back to a live resourceClass scan.  Returns the internalId string on
    success, or None if the window cannot be found.

    The internalId from session_state may be stale if the app was
    restarted since the last kwin_restore.py run; the live scan handles
    that case.
    """
    # -- Primary: session state -----------------------------------------------
    if entry.tracking_uuid:
        se = session_state.get(entry.tracking_uuid)
        if se and se.internal_id:
            # Verify the window still exists by checking live list
            try:
                wins = kwin.windows.find_by_class(entry.resource_class)
                ids = {w.internalId.strip("{}") for w in wins}
                bare = se.internal_id.strip("{}")
                if bare in ids:
                    return se.internal_id
                # Session state is stale — fall through to live scan
                logger.info(
                    f"    Session state entry stale for "
                    f"{entry.app_alias!r} — falling back to class scan"
                )
            except Exception:
                pass  # fall through

    # -- Fallback: live resourceClass scan ------------------------------------
    try:
        wins = kwin.windows.find_by_class(entry.resource_class)
        if wins:
            return wins[0].internalId
    except Exception as exc:
        logger.warn(f"    Class scan failed for {entry.app_alias!r}: {exc}")

    return None


# ── Per-entry realign operation ───────────────────────────────────────────────

def realign_entry(
    entry:   SnapshotEntry,
    uuid:    str,
    screen_res: ScreenResolution | None,
    kwin:    KWinSession,
    cfg:     KWinConfig,
    logger:  ProgressWindowLogger,
    dry_run: bool,
    desktop_name: str,   # for log messages only
) -> bool:
    """
    Re-anchor and re-tile one window on the currently active desktop.

    Returns True on success, False if any operation failed.

    Operations (matching Phase 3 of kwin_restore.py):
      1. move_to_screen  — re-anchor on the correct screen
      2. tile / maximize / minimize / raise  — restore the target state

    We deliberately do NOT call unminimize/unmaximize here: realign is
    a correction pass, not a full restore.  If a window is minimized
    intentionally (e.g. a background app) we honour that state.
    """
    tile_pos = entry.tile.strip() if entry.tile else ""
    maximize = entry.maximized and not entry.minimized
    minimize = entry.minimized

    # Build a human-readable screen description for log lines.
    # Shows:  yaml="main"  →  canonical="HDMI-A-2"  or  (no screen)
    if screen_res is None:
        screen_label = "(no screen configured)"
        screen_info  = None
    elif screen_res.yaml_value == screen_res.canonical:
        # No alias mapping — yaml value IS the connector name
        screen_label = f"connector={screen_res.canonical!r}"
        screen_info  = screen_res.screen_info
    else:
        screen_label = (
            f"yaml={screen_res.yaml_value!r}  →  "
            f"canonical={screen_res.canonical!r}"
        )
        screen_info = screen_res.screen_info

    if screen_res is not None and screen_info is None:
        screen_label += "  [NOT FOUND IN KWIN — screen step skipped]"

    if dry_run:
        state = (f"tile {tile_pos!r}" if tile_pos
                 else "maximize" if maximize
                 else "minimize" if minimize
                 else "raise")
        logger.info(
            f"    [dry-run] {entry.app_alias!r}  "
            f"{screen_label}  state={state}  "
            f"desktop={desktop_name!r}"
        )
        return True

    try:
        if screen_info is not None:
            logger.info(f"    [move_to_screen]  {screen_label}")
            kwin.windows.move_to_screen(uuid, screen_info)
        else:
            logger.info(f"    [move_to_screen]  skipped — {screen_label}")

        if tile_pos:
            kwin.windows.tile(uuid, tile_pos)
            state = f"tiled-{tile_pos}"
        elif maximize:
            kwin.windows.maximize(uuid)
            kwin.windows.ensure_maximized(
                uuid,
                width_tolerance  = cfg.maximize_width_tolerance,
                height_tolerance = cfg.maximize_height_tolerance,
                logger           = logger,
            )
            state = "maximized"
        elif minimize:
            kwin.windows.minimize(uuid)
            state = "minimized"
        else:
            kwin.windows.raise_window(uuid)
            state = "raised"

        logger.ok(
            f"    [{state}] {entry.app_alias!r} on {desktop_name!r}"
        )
        return True

    except RuntimeError as exc:
        logger.warn(
            f"    Realign failed — {entry.app_alias!r} on "
            f"{desktop_name!r}: {exc}"
        )
        return False


# ── Setup file resolution (identical logic to kwin_restore.py) ────────────────

def resolve_setup_file(setup_arg: str | None, cfg: KWinConfig) -> Path | None:
    if setup_arg:
        p = Path(setup_arg).expanduser()
        return p if p.exists() else None

    if not cfg.default_setup:
        return None

    filename   = cfg.default_setup
    config_dir = Path("~/.config/wayland-desktop").expanduser()
    for candidate in [
        Path(filename),
        config_dir / filename,
        cfg.snapshot_dir / filename,
    ]:
        resolved = candidate.expanduser().resolve()
        if resolved.exists():
            return resolved

    return None


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="kwin_realign.py",
        description=(
            "Realign window positions and tiling without relaunching apps.\n"
            "Corrects drift that occurs after screen unlock or KWin recompose."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("app", nargs="?", default=None, metavar="APP",
        help="Realign only this app (alias or resourceClass). "
             "Equivalent to --filter APP.")
    parser.add_argument("--setup",        default="", metavar="FILE",
        help="Snapshot/setup file to read from.")
    parser.add_argument("--config",       default="", metavar="FILE",
        help="Alternate config file.")
    parser.add_argument("--all-apps",     action="store_true",
        help="Process all entries, not just on_all_desktops ones.  "
             "Single-desktop entries are processed only on their own desktop.")
    parser.add_argument("--dry-run",      action="store_true",
        help="Show what would be done without changing anything.")
    parser.add_argument("--settle-delay", type=int, default=400,
        metavar="MS",
        help="Milliseconds to wait after each desktop switch (default: 400).")
    parser.add_argument("--verbose",      action="store_true",
        help="Print a debug line after every KWin script call.")
    parser.add_argument("--show-window",  action="store_true",
        help="Show the progress window regardless of config setting.")
    parser.add_argument("--no-window",    action="store_true",
        help="Suppress the progress window regardless of config setting.")
    parser.add_argument("--filter",       action="append", default=[],
        dest="filters", metavar="APP",
        help="Only realign this app alias or resourceClass (repeatable).")
    args = parser.parse_args()

    cfg = load_config(args.config or None)

    # -- Resolve setup file ---------------------------------------------------
    snapshot_path = resolve_setup_file(args.setup or None, cfg)

    if snapshot_path is None:
        if args.setup:
            error(f"Setup file not found: {args.setup}")
        elif cfg.default_setup:
            error(
                f"Default setup file {cfg.default_setup!r} not found. "
                f"Searched: current dir, ~/.config/wayland-desktop/, "
                f"{cfg.snapshot_dir}/"
            )
        else:
            error(
                "No setup file specified and no default_setup configured. "
                "Use --setup <file.yaml> or set default_setup in config.yaml."
            )
        sys.exit(1)

    try:
        snapshot = LayoutSnapshot.load(snapshot_path)
    except Exception as exc:
        error(f"Cannot load snapshot: {exc}")
        sys.exit(1)

    # -- Progress window ------------------------------------------------------
    # progress_window is a screen alias string (non-blank = show) or "".
    # --show-window forces the window on; --no-window suppresses it.
    # Screen placement (move + keepBelow) is applied only when the config
    # provides a valid screen alias — not when --show-window alone is used.
    use_window = bool(cfg.progress_window)
    if args.show_window: use_window = True
    if args.no_window:   use_window = False

    # Resolve and validate the screen alias when one is configured.
    progress_screen_connector: str | None = None
    if cfg.progress_window:
        try:
            progress_screen_connector = cfg.get_progress_window_screen()
        except ValueError as exc:
            error(str(exc))
            sys.exit(1)

    win: ProgressWindow | None = None
    if use_window:
        win = ProgressWindow()
        win.show(initial_verbose=args.verbose)
        if progress_screen_connector:
            win.move_to_screen(progress_screen_connector)
    logger = ProgressWindowLogger(win)

    # -- Build filter set -----------------------------------------------------
    filters: list[str] = list(args.filters)
    if args.app:
        filters.append(args.app)

    logger.head("=== KWin Layout Realign ============================================")
    logger.info(f"Setup         : {snapshot_path}")
    logger.info(f"Captured      : {snapshot.timestamp}  ({snapshot.hostname})")
    logger.info(f"Settle delay  : {args.settle_delay}ms")
    if args.all_apps:  logger.info("Mode          : --all-apps (all entries)")
    if args.dry_run:   logger.info("Mode          : DRY RUN (nothing will be changed)")
    if args.verbose:   logger.info("Mode          : --verbose (per-op debug output)")
    if use_window:     logger.info("Mode          : progress window active")
    if filters:        logger.info(f"Filter        : {filters}")

    # -- Filter entries -------------------------------------------------------
    entries = snapshot.entries

    # Filter out tray-only apps — nothing to align without a window.
    entries = [e for e in entries if not e.ignore_window]

    if filters:
        resolved_filters = set()
        for f in filters:
            resolved_filters.add(cfg.resolve_resource_class(f))
            resolved_filters.add(f)
        entries = [
            e for e in entries
            if e.resource_class in resolved_filters
            or e.app_alias in resolved_filters
            or any(
                f.lower() in e.resource_class.lower()
                or f.lower() in e.app_alias.lower()
                for f in filters
            )
        ]
        logger.info(f"Filtered to {len(entries)} entries")

    if not entries:
        logger.warn("No entries to realign.")
        if win:
            win.raise_to_front()
            win.set_title("All done: Realign Completed (nothing to do)")
            win.set_complete()
            win.wait_for_close()
        sys.exit(0)

    # -- Load session state ---------------------------------------------------
    session_state = SessionState.load()
    if len(session_state) == 0:
        logger.info(
            "Session state is empty — will use live resourceClass scan for "
            "all window lookups"
        )

    settle_s = args.settle_delay / 1000.0

    n_ok   = 0
    n_skip = 0
    n_fail = 0

    try:
        with KWinSession(verbose=args.verbose) as kwin:

            # -- Remember which desktop is currently active -------------------
            try:
                original_desktop_id = kwin.desktops.current_desktop_id()
            except Exception:
                original_desktop_id = None

            # -- List screens that KWin currently reports --------------------
            # Logged unconditionally so drift due to connector name changes
            # (e.g. HDMI-A-1 vs HDMI-A-2 across reboots) is immediately
            # visible without needing --verbose.
            try:
                live_screens = kwin.desktops.list_screens()
                logger.info("Available screens (KWin):")
                for i, s in enumerate(live_screens):
                    logger.info(
                        f"  [{i}]  {s.name:<16}"
                        f"  top-left({s.x},{s.y})"
                        f"  {s.width}x{s.height}"
                    )
            except Exception as exc:
                logger.warn(f"Could not list screens: {exc}")
                live_screens = []

            # -- Build resolved screen map (entry → ScreenResolution) ---------
            # Done once up front to avoid repeated lookups per desktop.
            # Logs a resolution table so alias → canonical → KWin outcome is
            # visible at a glance — critical for diagnosing wrong-screen bugs.
            col = max((len(e.app_alias) for e in entries), default=8)
            screen_map: dict[int, ScreenResolution] = {}  # keyed by id(entry)

            # Detect duplicate app_alias values in the entry list so we can
            # warn when the old alias-keyed approach would have silently
            # overwritten earlier entries.
            alias_counts: dict[str, int] = {}
            for entry in entries:
                alias_counts[entry.app_alias] = \
                    alias_counts.get(entry.app_alias, 0) + 1

            logger.info("Screen resolution:")
            for entry in entries:
                yaml_val  = entry.screen_alias or entry.screen or ""
                canonical = cfg.resolve_screen(yaml_val) if yaml_val else ""
                if canonical:
                    found = kwin.desktops.find_screen(name=canonical)
                else:
                    found = None
                sr = ScreenResolution(
                    yaml_value  = yaml_val,
                    canonical   = canonical,
                    screen_info = found,
                )
                screen_map[id(entry)] = sr  # id(entry) is unique per entry object

                # Resolution table row
                if not yaml_val:
                    status = "(no screen in YAML)"
                elif yaml_val == canonical:
                    status = (
                        f"connector={canonical!r}  →  "
                        + ("FOUND" if found else "NOT FOUND IN KWIN")
                    )
                else:
                    status = (
                        f"yaml={yaml_val!r}  →  canonical={canonical!r}  →  "
                        + ("FOUND" if found else "NOT FOUND IN KWIN")
                    )

                # Flag duplicate aliases explicitly so the collision is visible.
                dup_tag = (
                    "  [duplicate alias]"
                    if alias_counts[entry.app_alias] > 1
                    else ""
                )

                if found is None and yaml_val:
                    logger.warn(
                        f"  {entry.app_alias:<{col}}  {status}"
                        f"  — screen step will be skipped{dup_tag}"
                    )
                else:
                    logger.info(
                        f"  {entry.app_alias:<{col}}  {status}{dup_tag}"
                    )

            # -- Outer loop: each virtual desktop in order --------------------
            all_desktops = kwin.desktops.list_desktops()
            logger.info(
                f"Virtual desktops: "
                f"{', '.join(d.name for d in all_desktops)}"
            )

            for desktop in all_desktops:
                if win and win.is_abort_requested():
                    logger.warn("Abort requested — stopping")
                    break

                # Determine which entries are relevant on this desktop:
                #   on_all_desktops → always relevant
                #   single-desktop  → only when --all-apps AND desktop matches
                relevant = []
                for entry in entries:
                    if entry.on_all_desktops:
                        relevant.append(entry)
                    elif args.all_apps:
                        canonical = cfg.resolve_desktop(
                            entry.desktop_alias or entry.desktop
                        )
                        if canonical == desktop.name:
                            relevant.append(entry)

                if not relevant:
                    continue  # nothing to do on this desktop — skip the switch

                logger.head(
                    f"Desktop: {desktop.name!r}  "
                    f"({len(relevant)} window(s) to realign)"
                )

                # Switch to this desktop.
                if not args.dry_run:
                    try:
                        kwin.desktops.switch_to_desktop(
                            desktop, settle_s=settle_s
                        )
                    except RuntimeError as exc:
                        logger.warn(
                            f"  Could not switch to desktop "
                            f"{desktop.name!r}: {exc} — skipping desktop"
                        )
                        n_skip += len(relevant)
                        continue
                else:
                    logger.info(
                        f"  [dry-run] Would switch to {desktop.name!r}"
                    )

                # Inner loop: relevant entries for this desktop.
                for entry in relevant:
                    if win and win.is_abort_requested():
                        break

                    # Sync verbose flag from progress window checkbox.
                    if win and win.is_showing():
                        args.verbose = win.is_verbose()
                        kwin.windows.set_verbose(args.verbose)

                    logger.info(f"  Entry: {entry.app_alias!r}")

                    # Find the live window.
                    uuid = find_window(entry, session_state, kwin, logger)
                    if uuid is None:
                        logger.warn(
                            f"    Window not found for "
                            f"{entry.app_alias!r} — skipping"
                        )
                        n_skip += 1
                        continue

                    logger.info(f"    Found: {uuid[:20]}...")

                    success = realign_entry(
                        entry        = entry,
                        uuid         = uuid,
                        screen_res   = screen_map.get(id(entry)),
                        kwin         = kwin,
                        cfg          = cfg,
                        logger       = logger,
                        dry_run      = args.dry_run,
                        desktop_name = desktop.name,
                    )
                    if success:
                        n_ok += 1
                    else:
                        n_fail += 1

            # -- Restore the originally active desktop ------------------------
            if original_desktop_id and not args.dry_run:
                try:
                    original_desktop = kwin.desktops.find_desktop(
                        id=original_desktop_id
                    )
                    if original_desktop:
                        kwin.desktops.switch_to_desktop(
                            original_desktop, settle_s=0.2
                        )
                        logger.info(
                            f"Restored active desktop: "
                            f"{original_desktop.name!r}"
                        )
                except Exception as exc:
                    logger.warn(
                        f"Could not restore original desktop: {exc} (non-fatal)"
                    )

    except RuntimeError as exc:
        error(f"Session error: {exc}")
        if win:
            win.raise_to_front()
            win.set_title("Error: Realign Failed, see log for details")
            win.set_complete()
            win.wait_for_close()
        sys.exit(1)

    # -- Summary --------------------------------------------------------------
    logger.head("Summary")
    logger.ok(f"Realigned : {n_ok}")
    if n_skip:
        logger.info(f"Skipped   : {n_skip}")
    if n_fail:
        logger.warn(f"Failed    : {n_fail}")

    logger.head("=== Done ===========================================================")

    # raise_to_front() clears keepBelow (set by move_to_screen at startup)
    # and raises the window so the user can see the summary and hit Close.
    if win and win.is_showing():
        win.raise_to_front()
        win.set_title("All done: Realign Completed")
        win.set_complete()
        win.wait_for_close()

    if n_fail:
        sys.exit(1)


if __name__ == "__main__":
    main()
