# =============================================================================
# kwin_lib/click_indicator.py
# Generated by: Claude Sonnet 4.6
#
# ClickIndicator: a child-process full-screen transparent overlay that paints
# a brief red dot with crosshair at each pointer position injected during
# phase 4 of kwin_restore.py.
#
# Architecture
# ────────────
# A single persistent QWidget covers the full virtual desktop (all monitors
# combined).  Its background is fully transparent; only the dots are visible.
# Each dot is a 48 px red filled circle with a white crosshair, painted at the
# requested position and erased after DOT_DURATION_MS by a QTimer.
#
# After the overlay is shown, a KWin JS script (injected via pydbus, matching
# by PID) sets keepAbove=true, onAllDesktops=true, and skipTaskbar=true so the
# overlay stays on top of all windows, is visible on every virtual desktop, and
# does not appear in the taskbar.
#
# Usage
# ─────
#   indicator = ClickIndicator()
#   indicator.start()            # spawn child, block until ready
#   indicator.show_click(x, y)   # non-blocking
#   indicator.stop()             # send sentinel, wait for child exit
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import multiprocessing
import sys
from pathlib import Path


# ── Display constants ─────────────────────────────────────────────────────────

DOT_DIAMETER_PX: int = 48        # diameter of the red dot
DOT_COLOUR:      str = "#FF2222" # filled circle colour
DOT_DURATION_MS: int = 1000      # how long each dot stays visible (ms)
QUEUE_POLL_MS:   int = 30        # queue drain interval (ms)


# ── Child process ─────────────────────────────────────────────────────────────

def _indicator_process(
    coord_queue:    multiprocessing.Queue,
    ready_event:    multiprocessing.Event,
    extra_sys_path: str,
) -> None:
    """Child: runs a full-screen transparent overlay showing click dots."""
    if extra_sys_path and extra_sys_path not in sys.path:
        sys.path.insert(0, extra_sys_path)

    try:
        from PyQt6.QtWidgets import QApplication, QWidget
        from PyQt6.QtCore    import Qt, QTimer, QRect
        from PyQt6.QtGui     import QPainter, QColor, QBrush, QPen
    except ImportError as exc:
        ready_event.set()
        print(f"[click_indicator] PyQt6 not available: {exc}", file=sys.stderr)
        return

    import os
    import tempfile

    app = QApplication.instance() or QApplication(sys.argv)
    app.setApplicationName("kwin-click-indicator")

    # Compute the bounding rectangle of all screens combined.
    virtual_geom = QRect()
    for screen in app.screens():
        virtual_geom = virtual_geom.united(screen.geometry())

    # Each active dot: {"x": float, "y": float}
    active_dots: list[dict] = []

    class OverlayWidget(QWidget):
        """
        Single persistent full-screen transparent overlay.
        Dots are stored in active_dots and painted on each update().
        """
        def __init__(self) -> None:
            super().__init__()
            self.setWindowFlags(
                Qt.WindowType.FramelessWindowHint  |
                Qt.WindowType.WindowStaysOnTopHint |
                Qt.WindowType.Window
            )
            self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
            self.setAttribute(Qt.WidgetAttribute.WA_ShowWithoutActivating)
            self.setAttribute(Qt.WidgetAttribute.WA_TransparentForMouseEvents)
            self.setGeometry(virtual_geom)
            self.show()

        def add_dot(self, x: float, y: float) -> None:
            """Add a dot at absolute compositor coords and schedule removal."""
            # Translate to overlay-local coordinates
            ox = x - virtual_geom.x()
            oy = y - virtual_geom.y()
            entry: dict = {"x": ox, "y": oy}
            active_dots.append(entry)
            self.update()

            t = QTimer(self)
            t.setSingleShot(True)
            def remove(e=entry):
                try:
                    active_dots.remove(e)
                except ValueError:
                    pass
                self.update()
            t.timeout.connect(remove)
            t.start(DOT_DURATION_MS)

        def paintEvent(self, event) -> None:  # type: ignore[override]
            if not active_dots:
                return
            painter = QPainter(self)
            painter.setRenderHint(QPainter.RenderHint.Antialiasing)
            d   = DOT_DIAMETER_PX
            r   = d // 2
            arm = r - 4

            for dot in active_dots:
                cx = int(dot["x"])
                cy = int(dot["y"])

                # Filled red circle centred on (cx, cy)
                painter.setBrush(QBrush(QColor(DOT_COLOUR)))
                painter.setPen(Qt.PenStyle.NoPen)
                painter.drawEllipse(cx - r, cy - r, d, d)

                # White crosshair
                pen = QPen(QColor("#ffffff"))
                pen.setWidth(2)
                painter.setPen(pen)
                painter.drawLine(cx,       cy - arm, cx,       cy + arm)
                painter.drawLine(cx - arm, cy,       cx + arm, cy)

            painter.end()

    overlay = OverlayWidget()

    # ── KWin flags: keepAbove, onAllDesktops, skipTaskbar ────────────────────
    # Injected 500 ms after show() so KWin has time to register the window.

    def _set_kwin_flags() -> None:
        pid = os.getpid()
        try:
            from pydbus import SessionBus
            bus       = SessionBus()
            scripting = bus.get("org.kde.KWin", "/Scripting")
            js = (
                f"var ws=workspace.windowList();"
                f"for(var i=0;i<ws.length;i++){{"
                f"if(Number(ws[i].pid)==={pid}){{"
                f"ws[i].keepAbove=true;"
                f"ws[i].onAllDesktops=true;"
                f"ws[i].skipTaskbar=true;"
                f"break;}}}}"
            )
            fd, path = tempfile.mkstemp(suffix=".js", prefix="kwin_ci_")
            os.close(fd)
            with open(path, "w") as fh:
                fh.write(js)
            scripting.loadScript(path)
            scripting.start()
            # Remove the temp file after KWin has had time to load it
            QTimer.singleShot(800, lambda: _unlink(path))
        except Exception:
            pass  # non-fatal — dots still appear, just may not be on top

    def _unlink(path: str) -> None:
        try:
            os.unlink(path)
        except Exception:
            pass

    QTimer.singleShot(500, _set_kwin_flags)

    # ── Queue drain ───────────────────────────────────────────────────────────

    def drain() -> None:
        while True:
            try:
                item = coord_queue.get_nowait()
            except Exception:
                break
            if item is None:   # sentinel: quit
                app.quit()
                return
            if item == "hide":
                overlay.hide()
                return
            if item == "show":
                overlay.show()
                return
            x, y = item
            overlay.add_dot(x, y)

    poll_timer = QTimer()
    poll_timer.timeout.connect(drain)
    poll_timer.start(QUEUE_POLL_MS)

    ready_event.set()   # unblock ClickIndicator.start() in the parent
    app.exec()


# ── ClickIndicator ────────────────────────────────────────────────────────────

class ClickIndicator:
    """
    Manages a child process running a full-screen transparent overlay that
    displays a brief red dot at each injected pointer position.

    All methods are no-ops when the child is not running.
    """

    def __init__(self) -> None:
        ctx = multiprocessing.get_context("spawn")
        self._coord_queue: multiprocessing.Queue = ctx.Queue()
        self._ready_event: multiprocessing.Event = ctx.Event()
        self._process: multiprocessing.Process | None = None
        self._extra_sys_path = str(Path(__file__).resolve().parent.parent)

    def start(self) -> None:
        """Spawn the child process and block until the overlay is ready."""
        if self._process and self._process.is_alive():
            return
        ctx = multiprocessing.get_context("spawn")
        self._process = ctx.Process(
            target = _indicator_process,
            args   = (
                self._coord_queue,
                self._ready_event,
                self._extra_sys_path,
            ),
            daemon = True,
        )
        self._process.start()
        self._ready_event.wait(timeout=10.0)

    def show_click(self, x: float, y: float) -> None:
        """Send a coordinate to the child overlay (non-blocking)."""
        if self._process and self._process.is_alive():
            try:
                self._coord_queue.put_nowait((x, y))
            except Exception:
                pass

    def hide(self) -> None:
        """Hide the overlay so it cannot block input to other windows."""
        if self._process and self._process.is_alive():
            try:
                self._coord_queue.put_nowait("hide")
            except Exception:
                pass

    def show(self) -> None:
        """Show the overlay again after it was hidden."""
        if self._process and self._process.is_alive():
            try:
                self._coord_queue.put_nowait("show")
            except Exception:
                pass

    def stop(self) -> None:
        """Send the quit sentinel and wait for the child to exit."""
        if self._process and self._process.is_alive():
            try:
                self._coord_queue.put_nowait(None)
            except Exception:
                pass
            self._process.join(timeout=3.0)
            if self._process.is_alive():
                self._process.terminate()
        self._process = None

    def is_running(self) -> bool:
        return bool(self._process and self._process.is_alive())
