# =============================================================================
# kwin_lib/models.py
# Generated by: Claude Sonnet 4.6
#
# Data models shared across all library modules.
# All classes are plain dataclasses — no D-Bus dependency.
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


@dataclass
class DesktopInfo:
    """A KWin virtual desktop."""
    id:     str    # UUID string — required for w.desktops assignment
    name:   str    # Human-readable name, e.g. "Main", "Job 1"
    number: int    # 1-based X11 desktop number

    def __str__(self) -> str:
        return f"Desktop({self.number}, {self.name!r}, {self.id})"


@dataclass
class ScreenInfo:
    """A connected output / monitor as reported by workspace.screens."""
    name:   str    # Connector name, e.g. "HDMI-A-2", "DP-4"
    x:      int    # Top-left x in compositor coordinate space
    y:      int    # Top-left y in compositor coordinate space
    width:  int
    height: int
    model:  str = ""    # e.g. "LG FULL HD"
    manufacturer: str = ""

    @property
    def centre_x(self) -> int:
        return self.x + self.width // 2

    @property
    def centre_y(self) -> int:
        return self.y + self.height // 2

    def contains_point(self, px: int, py: int) -> bool:
        return self.x <= px < self.x + self.width and \
               self.y <= py < self.y + self.height

    def __str__(self) -> str:
        return (f"Screen({self.name!r}, "
                f"{self.x},{self.y} {self.width}x{self.height})")


@dataclass
class WindowInfo:
    """
    All KWin-reported properties for one window.

    internalId is the stable UUID handle used for all subsequent operations.
    detected_ms is milliseconds after app launch when the window appeared;
    0 means the window was pre-existing (app was already running).
    """
    internalId:      str
    detected_ms:     int  = 0

    resourceClass:   str  = ""
    resourceName:    str  = ""
    caption:         str  = ""
    desktopFileName: str  = ""
    pid:             int  = 0

    # Current placement (as reported at identification time)
    desktop_id:      str  = ""    # UUID of current virtual desktop
    desktop_name:    str  = ""    # Human name of current virtual desktop
    screen_name:     str  = ""    # Connector name of current screen

    x:               int  = 0
    y:               int  = 0
    width:           int  = 0
    height:          int  = 0

    minimized:       bool = False
    maximized:       bool = False
    fullScreen:      bool = False
    onAllDesktops:   bool = False

    # Any additional properties KWin returned
    extra: dict[str, Any] = field(default_factory=dict)

    @property
    def is_pre_existing(self) -> bool:
        """True when the app was already running at probe time."""
        return self.detected_ms == 0

    def display_name(self) -> str:
        parts = [p for p in (self.resourceClass, self.caption) if p]
        return " / ".join(parts) if parts else "(unknown)"

    def __str__(self) -> str:
        return (f"Window({self.internalId}, {self.resourceClass!r}, "
                f"{self.caption!r})")


def window_from_kwin_dict(d: dict[str, Any], detected_ms: int = 0) -> WindowInfo:
    """
    Build a WindowInfo from the raw dict a KWin script sends via callDBus().
    Tolerates missing keys gracefully.
    """
    def s(k: str) -> str:
        return str(d.get(k) or "").strip()
    def i(k: str) -> int:
        try: return int(d.get(k) or 0)
        except (TypeError, ValueError): return 0
    def b(k: str) -> bool:
        v = d.get(k)
        if isinstance(v, bool): return v
        if isinstance(v, str):  return v.lower() == "true"
        return bool(v) if v is not None else False

    known = {
        "internalId", "resourceClass", "resourceName", "caption",
        "desktopFileName", "pid", "desktopId", "desktopName", "outputName",
        "x", "y", "width", "height",
        "minimized", "maximized", "fullScreen", "onAllDesktops",
    }
    extra = {k: v for k, v in d.items() if k not in known}

    return WindowInfo(
        internalId      = s("internalId"),
        detected_ms     = detected_ms,
        resourceClass   = s("resourceClass"),
        resourceName    = s("resourceName"),
        caption         = s("caption"),
        desktopFileName = s("desktopFileName"),
        pid             = i("pid"),
        desktop_id      = s("desktopId"),
        desktop_name    = s("desktopName"),
        screen_name     = s("outputName"),
        x               = i("x"),
        y               = i("y"),
        width           = i("width"),
        height          = i("height"),
        minimized       = b("minimized"),
        maximized       = b("maximized"),
        fullScreen      = b("fullScreen"),
        onAllDesktops   = b("onAllDesktops"),
        extra           = extra,
    )
