# =============================================================================
# kwin_lib/probe.py
# Generated by: Claude Sonnet 4.6
#
# Window identification: launches a program and detects its new window(s)
# via the KWin scripting windowAdded signal.
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import os
import subprocess
import tempfile
import threading
import time
from datetime import datetime
from typing import Any

from pydbus import SessionBus

from .bus import KWinBus, GLibLoop
from .models import WindowInfo, window_from_kwin_dict


PROBE_SERVICE = "org.probe.KWinProbe"
PROBE_PATH    = "/Receiver"
PROBE_IFACE   = "org.probe.KWinProbe"

PROBE_XML = f"""
<node>
  <interface name='{PROBE_IFACE}'>
    <method name='receiveSnapshot'>
      <arg type='s' name='json_data' direction='in'/>
    </method>
    <method name='receiveWindowAdded'>
      <arg type='s' name='json_data' direction='in'/>
    </method>
  </interface>
</node>
"""

# The KWin JS watcher script — injected once, stays loaded until probe finishes
_WATCHER_SCRIPT = f"""
// kwin_lib watcher — snapshot + windowAdded hook
var _svc="{PROBE_SERVICE}",_path="{PROBE_PATH}",_iface="{PROBE_IFACE}";

function winToObj(w) {{
    return {{
        internalId:      String(w.internalId      || ""),
        resourceClass:   String(w.resourceClass   || ""),
        resourceName:    String(w.resourceName    || ""),
        caption:         String(w.caption         || ""),
        desktopFileName: String(w.desktopFileName || ""),
        pid:             Number(w.pid             || 0),
        desktopId:   w.desktops&&w.desktops.length>0
                         ? String(w.desktops[0].id||"")   : "",
        desktopName: w.desktops&&w.desktops.length>0
                         ? String(w.desktops[0].name||"") : "",
        outputName:      String(w.output ? (w.output.name||"") : ""),
        x:               Number(w.x      || 0),
        y:               Number(w.y      || 0),
        width:           Number(w.width  || 0),
        height:          Number(w.height || 0),
        minimized:       Boolean(w.minimized),
        maximized:       Boolean(w.maximized),
        fullScreen:      Boolean(w.fullScreen),
        onAllDesktops:   Boolean(w.onAllDesktops),
    }};
}}

// Step 1: snapshot existing windows
try {{
    var existing = workspace.windowList();
    var snap = [];
    for (var i = 0; i < existing.length; i++) {{
        try {{ snap.push(winToObj(existing[i])); }} catch(e) {{}}
    }}
    callDBus(_svc, _path, _iface, "receiveSnapshot",
             JSON.stringify({{ windows: snap }}));
}} catch(e) {{
    callDBus(_svc, _path, _iface, "receiveSnapshot",
             JSON.stringify({{ windows: [], error: String(e) }}));
}}

// Step 2: hook windowAdded
try {{
    workspace.windowAdded.connect(function(w) {{
        try {{
            callDBus(_svc, _path, _iface, "receiveWindowAdded",
                     JSON.stringify(winToObj(w)));
        }} catch(e) {{}}
    }});
}} catch(e) {{}}
"""


class _ProbeReceiver:
    """Internal D-Bus receiver for the probe watcher script."""
    dbus = PROBE_XML

    def __init__(self, filter_class: str = "") -> None:
        self.filter_class       = filter_class.lower()
        self.snapshot_ids:  set[str]           = set()
        self.snapshot_wins: list[dict[str, Any]] = []
        self.new_windows:   list[WindowInfo]   = []
        self.snapshot_ready                    = threading.Event()
        self.window_added                      = threading.Event()
        self._lock                             = threading.Lock()
        self.launch_ms: int                    = 0

    def receiveSnapshot(self, json_data: str) -> None:
        import json
        try:
            data = json.loads(json_data)
            wins = data.get("windows", [])
            ids  = {w.get("internalId", "") for w in wins}
            with self._lock:
                self.snapshot_ids  = ids
                self.snapshot_wins = wins
            self.snapshot_ready.set()
        except Exception:
            self.snapshot_ready.set()   # unblock even on error

    def receiveWindowAdded(self, json_data: str) -> None:
        import json
        try:
            d   = json.loads(json_data)
            uid = d.get("internalId", "")
            ms  = int(time.monotonic() * 1000) - self.launch_ms
            win = window_from_kwin_dict(d, detected_ms=ms)

            with self._lock:
                if uid in self.snapshot_ids:
                    return   # pre-existing window

            if self.filter_class and win.resourceClass.lower() != self.filter_class:
                return

            with self._lock:
                self.new_windows.append(win)
            self.window_added.set()
        except Exception:
            pass


def _guess_class(command: list[str]) -> str:
    """Infer a likely resourceClass from the launch command."""
    if not command:
        return ""
    exe = os.path.basename(command[0]).lower()
    # Skip interpreter invocations
    if exe in ("python", "python3", "python3.13", "bash", "sh", "ruby", "node"):
        return ""
    return exe


def _find_existing(
    snapshot_wins: list[dict[str, Any]],
    match_class:   str,
) -> WindowInfo | None:
    """Search the pre-launch snapshot for a window matching match_class."""
    if not match_class:
        return None
    mc = match_class.lower()
    for d in snapshot_wins:
        if str(d.get("resourceClass") or "").lower() == mc:
            return window_from_kwin_dict(d, detected_ms=0)
    return None


class WindowProbe:
    """
    Launches a program and returns the WindowInfo of its new window.

    If the app is already running and relaunch=False (default), the existing
    window is returned immediately without launching a new instance.

    Usage:
        probe = WindowProbe()
        pid, windows = probe.run(["thunderbird"])
        uuid = windows[0].internalId
    """

    def __init__(
        self,
        timeout_secs: float = 30.0,
        filter_class: str   = "",
        stop_count:   int   = 1,     # 0 = collect all until timeout
        relaunch:     bool  = False,
    ) -> None:
        self.timeout_secs = timeout_secs
        self.filter_class = filter_class
        self.stop_count   = stop_count
        self.relaunch     = relaunch

    def run(self, command: list[str]) -> tuple[int, list[WindowInfo]]:
        """
        Launch *command* and return (pid, windows).
        pid is 0 if the app was already running and relaunch=False.
        Raises RuntimeError on infrastructure failures.
        """
        bus      = SessionBus()
        receiver = _ProbeReceiver(filter_class=self.filter_class)

        try:
            registration = bus.publish(PROBE_SERVICE, (PROBE_PATH, receiver))
        except Exception as exc:
            raise RuntimeError(
                f"Cannot publish probe receiver '{PROBE_SERVICE}': {exc}\n"
                "Is another WindowProbe instance already running?"
            ) from exc

        loop = GLibLoop()
        loop.start()

        scripting = bus.get("org.kde.KWin", "/Scripting")

        # Write and load watcher script
        fd, js_path = tempfile.mkstemp(suffix=".js", prefix="kwin_probe_")
        os.close(fd)
        script_id = None

        try:
            with open(js_path, "w") as f:
                f.write(_WATCHER_SCRIPT)
            script_id = scripting.loadScript(js_path)
            scripting.start()
        except Exception as exc:
            self._cleanup(loop, registration, scripting, script_id, js_path)
            raise RuntimeError(f"Failed to load watcher script: {exc}") from exc

        # Wait for snapshot
        if not receiver.snapshot_ready.wait(timeout=5.0):
            self._cleanup(loop, registration, scripting, script_id, js_path)
            raise RuntimeError(
                "Watcher script did not send snapshot within 5s. "
                "KWin scripting may be unavailable."
            )

        # Check for pre-existing window (unless --relaunch)
        if not self.relaunch:
            match_class = self.filter_class or _guess_class(command)
            existing    = _find_existing(receiver.snapshot_wins, match_class)
            if existing is not None:
                self._cleanup(loop, registration, scripting, script_id, js_path)
                return 0, [existing]

        # Launch the app
        receiver.launch_ms = int(time.monotonic() * 1000)
        proc = subprocess.Popen(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        app_pid = proc.pid

        # Wait for new windows
        deadline = time.monotonic() + self.timeout_secs
        while time.monotonic() < deadline:
            remaining = deadline - time.monotonic()
            receiver.window_added.wait(timeout=min(remaining, 1.0))
            receiver.window_added.clear()
            with receiver._lock:
                count = len(receiver.new_windows)
            if self.stop_count and count >= self.stop_count:
                break

        with receiver._lock:
            results = list(receiver.new_windows)

        self._cleanup(loop, registration, scripting, script_id, js_path)
        return app_pid, results

    @staticmethod
    def _cleanup(loop, registration, scripting, script_id, js_path) -> None:
        try:
            if script_id is not None:
                scripting.unloadScript(str(script_id))
        except Exception: pass
        try: os.unlink(js_path)
        except OSError:   pass
        try: loop.stop()
        except Exception: pass
        try: registration.unpublish()
        except Exception: pass
