# =============================================================================
# kwin_lib/progress_window.py
# Generated by: Claude Sonnet 4.6
#
# ProgressWindow: a child-process Qt window that displays kwin_restore.py
# log output in real time, with a Verbose checkbox and an Abort/Close button.
#
# Architecture
# ────────────
# The Qt window runs entirely in a child process (multiprocessing, spawn
# method).  The parent (kwin_restore.py) communicates with it via:
#
#   cmd_queue    (Queue)       parent → child: log messages, set_complete
#   verbose_val  (Value 'b')   child → parent: Verbose checkbox state
#   abort_val    (Value 'b')   child → parent: Abort button pressed
#   ready_event  (Event)       child → parent: window is visible and ready
#
# A QTimer in the child drains cmd_queue every 50 ms and updates the display.
#
# After the window appears, a best-effort KWin D-Bus script sets
# onAllDesktops=true so the window remains visible while the restore
# switches between virtual desktops.
#
# When progress_window in config.yaml contains a screen alias, the parent
# calls win.move_to_screen(connector) after win.show(), which also sets
# keepBelow=true.  The window is minimized at the end of Phase 4 and raised
# (keepBelow cleared) at the end of Phase 5.
#
# Usage (from kwin_restore.py)
# ─────────────────────────────
#   win    = ProgressWindow()
#   win.show(initial_verbose=args.verbose)   # spawns child, blocks until ready
#   win.move_to_screen("HDMI-A-1")           # optional: move + keepBelow
#   logger = ProgressWindowLogger(win)
#   logger.head("=== KWin Layout Restore ===")
#   logger.info("Phase 1 ...")
#   logger.ok("Done")
#   win.minimize_window()                    # end of Phase 4
#   win.raise_to_front()                     # end of Phase 5
#   win.set_complete()                       # Abort → Close button
#   win.wait_for_close()                     # blocks until user dismisses
#
# ProgressWindowLogger mirrors every message to both the terminal and the
# window.  When win=None it writes to the terminal only — no code changes
# are needed at call sites when the window is disabled.
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import json
import multiprocessing
import os
import sys
import tempfile
from pathlib import Path

# ── Display constants — edit these to adjust the window's appearance ──────────

LOG_FONT_FAMILY: str = ""    # empty → system fixed-width font
LOG_FONT_SIZE:   int = 0     # 0 → system default point size

WINDOW_MIN_W: int = 720
WINDOW_MIN_H: int = 420

# Queue command tags (parent → child)
_CMD_LOG          = "log"
_CMD_COMPLETE     = "complete"
_CMD_HIDE         = "hide"
_CMD_SHOW         = "show"
# Move window to a named screen (connector string) and set keepBelow=true.
# Queued by the parent after win.show() when progress_window has a screen alias.
_CMD_MOVE_TO_SCREEN = "move_to_screen"
# Minimize the progress window (used at end of Phase 4).
_CMD_MINIMIZE     = "minimize"
# Turn off keepBelow, unminimize, and raise the window to the front
# (used at end of Phase 5 so the user can see the completion summary).
_CMD_RAISE_TO_FRONT = "raise_to_front"

# Dark-terminal colour scheme for the log pane
_BG_COLOUR = "#1e1e1e"

# (foreground_hex, bold)
_LEVEL_STYLE: dict[str, tuple[str, bool]] = {
    "head":  ("#00e5ff", True ),   # cyan bold  — phase headings
    "ok":    ("#69f0ae", False),   # green      — [OK   ]
    "warn":  ("#ffd740", False),   # amber      — [WARN ]
    "error": ("#ff5252", False),   # red        — [ERROR]
    "info":  ("#e0e0e0", False),   # near-white — [INFO ]
    "dbg":   ("#9e9e9e", False),   # mid-grey   — [DBG  ]
}

# Queue command tags (parent → child)
_CMD_LOG      = "log"
_CMD_COMPLETE = "complete"
_CMD_HIDE     = "hide"
_CMD_SHOW     = "show"


# ── Child-process entry point — must be module-level for pickling ─────────────

def _window_process(
    cmd_queue,
    verbose_val,
    abort_val,
    ready_event,
    extra_sys_path: str,
) -> None:
    """
    Child process entry point.  Runs the Qt event loop.

    All Qt code lives inside this function so the parent process can import
    progress_window.py without requiring PyQt6 to be installed.
    """
    if extra_sys_path and extra_sys_path not in sys.path:
        sys.path.insert(0, extra_sys_path)

    try:
        from PyQt6.QtWidgets import (
            QApplication, QMainWindow, QWidget,
            QVBoxLayout, QHBoxLayout,
            QTextEdit, QPushButton, QCheckBox,
        )
        from PyQt6.QtCore import QTimer
        from PyQt6.QtGui  import (
            QFont, QFontDatabase, QColor,
            QTextCharFormat, QTextCursor,
        )
    except ImportError as exc:
        print(f"[progress_window] PyQt6 not available — window disabled: {exc}",
              file=sys.stderr)
        ready_event.set()   # unblock parent so it does not hang
        return

    def _unlink(path: str) -> None:
        try:
            os.unlink(path)
        except Exception:
            pass

    # ── Qt window (runs in child process only) ────────────────────────────────

    class _Win(QMainWindow):

        def __init__(self) -> None:
            super().__init__()
            self._complete = False
            self._setup_ui()
            # Default size; Qt/KWin will place the window
            self.resize(WINDOW_MIN_W, 500)
            # Drain cmd_queue on a 250ms heartbeat
            self._timer = QTimer(self)
            self._timer.timeout.connect(self._drain)
            self._timer.start(250)
            # After KWin has registered the window, set it on all desktops.
            # keepBelow is NOT set here — it is applied only when the parent
            # sends _CMD_MOVE_TO_SCREEN (i.e. when a screen alias is configured).
            QTimer.singleShot(1200, self._set_on_all_desktops)

        def _setup_ui(self) -> None:
            self.setWindowTitle("KWin Layout Restore  \u26a0  DO NOT CLICK OR TYPE")
            self.setMinimumSize(WINDOW_MIN_W, WINDOW_MIN_H)

            central = QWidget(self)
            self.setCentralWidget(central)
            vbox = QVBoxLayout(central)
            vbox.setContentsMargins(6, 6, 6, 6)
            vbox.setSpacing(4)

            # Log pane — read-only, dark background, monospace font
            self._log = QTextEdit(self)
            self._log.setReadOnly(True)
            self._log.setStyleSheet(
                f"QTextEdit {{"
                f"  background-color: {_BG_COLOUR};"
                f"  border: 1px solid #444444;"
                f"}}"
            )
            if LOG_FONT_FAMILY:
                font = QFont(LOG_FONT_FAMILY)
            else:
                font = QFontDatabase.systemFont(
                    QFontDatabase.SystemFont.FixedFont
                )
            if LOG_FONT_SIZE > 0:
                font.setPointSize(LOG_FONT_SIZE)
            self._log.setFont(font)
            vbox.addWidget(self._log, stretch=1)

            # Bottom bar: [Verbose checkbox] <stretch> [Abort/Close button]
            bar  = QWidget(self)
            hbox = QHBoxLayout(bar)
            hbox.setContentsMargins(0, 2, 0, 0)

            self._verbose_cb = QCheckBox("Verbose", bar)
            self._verbose_cb.setChecked(bool(verbose_val.value))
            self._verbose_cb.stateChanged.connect(self._on_verbose)
            hbox.addWidget(self._verbose_cb)
            hbox.addStretch()

            self._btn = QPushButton("Abort", bar)
            self._btn.setFixedWidth(90)
            self._btn.clicked.connect(self._on_btn)
            hbox.addWidget(self._btn)

            vbox.addWidget(bar, stretch=0)

        def closeEvent(self, event) -> None:  # type: ignore[override]
            self._timer.stop()
            event.accept()

        # ── Slot: verbose checkbox toggled ────────────────────────────────────

        def _on_verbose(self, _state: int) -> None:
            verbose_val.value = 1 if self._verbose_cb.isChecked() else 0

        # ── Slot: Abort / Close button ────────────────────────────────────────

        def _on_btn(self) -> None:
            if self._complete:
                self.close()
            else:
                abort_val.value = 1
                self._btn.setText("Aborting\u2026")
                self._btn.setEnabled(False)

        # ── Queue drain (called every 250 ms by QTimer) ───────────────────────

        def _drain(self) -> None:
            # Process up to 20 messages per tick
            for _ in range(20):
                try:
                    cmd = cmd_queue.get_nowait()
                except Exception:
                    break
                kind = cmd[0]
                if kind == _CMD_LOG:
                    self._append(cmd[1], cmd[2])
                elif kind == _CMD_COMPLETE:
                    self._complete = True
                    self._btn.setText("Close")
                    self._btn.setEnabled(True)
                elif kind == _CMD_HIDE:
                    self.hide()
                elif kind == _CMD_SHOW:
                    self.show()
                    self.raise_()
                elif kind == _CMD_MOVE_TO_SCREEN:
                    # Schedule the move 1500ms after this tick so it runs
                    # after _set_on_all_desktops (which fires at 1200ms from
                    # window creation).  The lambda captures the connector name.
                    screen_name = cmd[1]
                    QTimer.singleShot(
                        1500,
                        lambda sn=screen_name: self._move_to_screen(sn),
                    )
                elif kind == _CMD_MINIMIZE:
                    # Small delay so KWin has settled before we minimise.
                    QTimer.singleShot(200, self._do_minimize)
                elif kind == _CMD_RAISE_TO_FRONT:
                    # Small delay so KWin has settled before we raise.
                    QTimer.singleShot(200, self._do_raise_to_front)

        # ── Append a coloured line to the log pane ────────────────────────────

        def _append(self, level: str, message: str) -> None:
            colour, bold = _LEVEL_STYLE.get(level, ("#e0e0e0", False))
            cursor = self._log.textCursor()
            cursor.movePosition(QTextCursor.MoveOperation.End)
            fmt = QTextCharFormat()
            fmt.setForeground(QColor(colour))
            fmt.setFontWeight(700 if bold else 400)
            cursor.insertText(message + "\n", fmt)
            self._log.setTextCursor(cursor)
            self._log.ensureCursorVisible()

        # ── Best-effort: put window on all KWin virtual desktops ──────────────

        def _set_on_all_desktops(self) -> None:
            # Sets onAllDesktops=true so the window stays visible while the
            # restore switches between virtual desktops.
            # keepBelow is handled separately by _move_to_screen — it is only
            # engaged when the parent sends _CMD_MOVE_TO_SCREEN.
            pid = os.getpid()
            self._run_kwin_script(
                f"var ws=workspace.windowList();"
                f"for(var i=0;i<ws.length;i++){{"
                f"if(Number(ws[i].pid)==={pid}){{"
                f"ws[i].onAllDesktops=true;"
                f"break;}}}}"
            )

        # ── Move window to a specific screen and set keepBelow=true ──────────

        def _move_to_screen(self, screen_name: str) -> None:
            # Finds the window by PID, moves it to the named screen connector,
            # and sets keepBelow=true so it stays behind other windows.
            pid = os.getpid()
            # screen_name is a KWin connector string (e.g. "DP-4")
            js = (
                f"var ws=workspace.windowList();"
                f"for(var i=0;i<ws.length;i++){{"
                f"if(Number(ws[i].pid)==={pid}){{"
                f"var sc=workspace.screens;"
                f"for(var j=0;j<sc.length;j++){{"
                f"if(sc[j].name==={screen_name!r}){{"
                f"ws[i].screen=sc[j];break;}}}}"
                f"ws[i].keepBelow=true;"
                f"break;}}}}"
            )
            self._run_kwin_script(js)

        # ── Minimize the progress window ──────────────────────────────────────

        def _do_minimize(self) -> None:
            pid = os.getpid()
            self._run_kwin_script(
                f"var ws=workspace.windowList();"
                f"for(var i=0;i<ws.length;i++){{"
                f"if(Number(ws[i].pid)==={pid}){{"
                f"ws[i].minimized=true;"
                f"break;}}}}"
            )

        # ── Turn off keepBelow, unminimize, and raise to front ────────────────

        def _do_raise_to_front(self) -> None:
            pid = os.getpid()
            self._run_kwin_script(
                f"var ws=workspace.windowList();"
                f"for(var i=0;i<ws.length;i++){{"
                f"if(Number(ws[i].pid)==={pid}){{"
                f"ws[i].keepBelow=false;"
                f"ws[i].minimized=false;"
                f"workspace.activeWindow=ws[i];"
                f"break;}}}}"
            )

        # ── Helper: load and run a KWin D-Bus script ──────────────────────────

        def _run_kwin_script(self, js: str) -> None:
            """Write js to a temp file, load it via KWin scripting D-Bus."""
            try:
                from pydbus import SessionBus
                bus       = SessionBus()
                scripting = bus.get("org.kde.KWin", "/Scripting")
                fd, path = tempfile.mkstemp(suffix=".js", prefix="kwin_pw_")
                os.close(fd)
                with open(path, "w") as fh:
                    fh.write(js)
                scripting.loadScript(path)
                scripting.start()
                # Remove the temp file after KWin has had time to load it
                QTimer.singleShot(800, lambda: _unlink(path))
            except Exception:
                pass  # non-fatal

    # ── Start event loop ──────────────────────────────────────────────────────

    app = QApplication(sys.argv)
    app.setApplicationName("kwin-restore-progress")

    win = _Win()
    win.show()
    win.raise_()
    win.activateWindow()
    ready_event.set()   # unblock ProgressWindow.show() in the parent

    app.exec()


# ── ProgressWindow — parent-side proxy ───────────────────────────────────────

class ProgressWindow:
    """
    Parent-side controller for the progress window child process.

    Spawn the child with show(); communicate via log(), set_complete(), and
    the is_verbose() / is_abort_requested() state readers.  Block until the
    user dismisses the window with wait_for_close().
    """

    def __init__(self) -> None:
        # Parent directory of kwin_lib — passed to child so imports work
        self._extra_sys_path = str(Path(__file__).resolve().parent.parent)

        ctx = multiprocessing.get_context("spawn")
        self._cmd_queue   = ctx.Queue()
        self._verbose_val = ctx.Value("b", 0)   # signed char: 0=False 1=True
        self._abort_val   = ctx.Value("b", 0)
        self._ready_event = ctx.Event()
        self._process: multiprocessing.Process | None = None

    def show(self, initial_verbose: bool = False) -> None:
        """Spawn the child process and block until the window is visible."""
        if self._process and self._process.is_alive():
            return
        self._verbose_val.value = 1 if initial_verbose else 0
        ctx = multiprocessing.get_context("spawn")
        self._process = ctx.Process(
            target = _window_process,
            args   = (
                self._cmd_queue,
                self._verbose_val,
                self._abort_val,
                self._ready_event,
                self._extra_sys_path,
            ),
            daemon = False,
        )
        self._process.start()
        # Block until the child signals it is ready, or give up after 15s
        self._ready_event.wait(timeout=15.0)

    def log(self, level: str, message: str) -> None:
        """Queue a log message for display in the window (non-blocking)."""
        if self.is_showing():
            try:
                self._cmd_queue.put_nowait((_CMD_LOG, level, message))
            except Exception:
                pass

    def is_verbose(self) -> bool:
        """Return the current state of the Verbose checkbox."""
        return bool(self._verbose_val.value)

    def is_abort_requested(self) -> bool:
        """Return True if the user has clicked the Abort button."""
        return bool(self._abort_val.value)

    def set_complete(self) -> None:
        """
        Signal that the restore is finished.
        Switches the Abort button to Close in the window.
        """
        if self.is_showing():
            try:
                self._cmd_queue.put_nowait((_CMD_COMPLETE,))
            except Exception:
                pass

    def hide_window(self) -> None:
        """Temporarily hide the progress window (e.g. while a dialog needs focus)."""
        if self.is_showing():
            try:
                self._cmd_queue.put_nowait((_CMD_HIDE,))
            except Exception:
                pass

    def show_window(self) -> None:
        """Re-show the progress window after it was hidden."""
        if self.is_showing():
            try:
                self._cmd_queue.put_nowait((_CMD_SHOW,))
            except Exception:
                pass

    def move_to_screen(self, screen_connector: str) -> None:
        """
        Move the window to the named KWin screen connector and set keepBelow.

        screen_connector is the canonical connector name (e.g. "DP-4"), not an
        alias.  The move is deferred inside the child process so it runs after
        the onAllDesktops script (which fires 1200ms after window creation).
        This method is a no-op when the window is not showing.
        """
        if self.is_showing():
            try:
                self._cmd_queue.put_nowait((_CMD_MOVE_TO_SCREEN, screen_connector))
            except Exception:
                pass

    def minimize_window(self) -> None:
        """
        Minimize the progress window via KWin.

        Called at the end of Phase 4 so the window is out of the way during
        Phase 5 desktop switching.
        """
        if self.is_showing():
            try:
                self._cmd_queue.put_nowait((_CMD_MINIMIZE,))
            except Exception:
                pass

    def raise_to_front(self) -> None:
        """
        Turn off keepBelow, unminimize, and raise the window to the front.

        Called at the end of Phase 5 so the user can see the completion
        summary.
        """
        if self.is_showing():
            try:
                self._cmd_queue.put_nowait((_CMD_RAISE_TO_FRONT,))
            except Exception:
                pass

    def wait_for_close(self) -> None:
        """Block until the user closes the progress window."""
        if self._process and self._process.is_alive():
            self._process.join()

    def is_showing(self) -> bool:
        """True while the child process is alive."""
        return bool(self._process and self._process.is_alive())


# ── ProgressWindowLogger — unified terminal + window output ──────────────────

class ProgressWindowLogger:
    """
    Mirrors log output to both the terminal and an optional ProgressWindow.

    Exposes info/ok/warn/error/head methods matching the logging functions in
    kwin_restore.py.  When win=None (or window has closed) it writes to the
    terminal only — callers need no if-guards.

    Also proxies is_verbose() and is_abort_requested() from the window so
    callers can query window state through a single object.
    """

    _t      = sys.stdout.isatty()
    _BOLD   = "\033[1m"  if _t else ""
    _CYAN   = "\033[36m" if _t else ""
    _GREEN  = "\033[32m" if _t else ""
    _YELLOW = "\033[33m" if _t else ""
    _RED    = "\033[31m" if _t else ""
    _RESET  = "\033[0m"  if _t else ""

    def __init__(self, win: ProgressWindow | None) -> None:
        self._win = win

    # ── Logging methods ───────────────────────────────────────────────────────

    def info(self, m: str) -> None:
        print(f"{self._CYAN}[INFO ] {self._RESET}{m}")
        self._send("info", f"[INFO ] {m}")

    def ok(self, m: str) -> None:
        print(f"{self._GREEN}[OK   ] {self._RESET}{m}")
        self._send("ok", f"[OK   ] {m}")

    def warn(self, m: str) -> None:
        print(f"{self._YELLOW}[WARN ] {self._RESET}{m}")
        self._send("warn", f"[WARN ] {m}")

    def error(self, m: str) -> None:
        print(f"{self._RED}[ERROR] {self._RESET}{m}", file=sys.stderr)
        self._send("error", f"[ERROR] {m}")

    def head(self, m: str) -> None:
        print(f"\n{self._BOLD}{self._CYAN}{m}{self._RESET}")
        self._send("head", m)

    def _send(self, level: str, message: str) -> None:
        if self._win and self._win.is_showing():
            self._win.log(level, message)

    # ── Window state proxies ──────────────────────────────────────────────────

    def is_verbose(self) -> bool:
        """Current state of the Verbose checkbox (False when no window)."""
        if self._win and self._win.is_showing():
            return self._win.is_verbose()
        return False

    def is_abort_requested(self) -> bool:
        """True if the Abort button has been clicked (False when no window)."""
        if self._win and self._win.is_showing():
            return self._win.is_abort_requested()
        return False

    def hide_window(self) -> None:
        """Hide the progress window so dialogs behind it are accessible."""
        if self._win and self._win.is_showing():
            self._win.hide_window()

    def show_window(self) -> None:
        """Re-show the progress window after it was hidden."""
        if self._win and self._win.is_showing():
            self._win.show_window()
