# =============================================================================
# kwin_lib/session_state.py
# Generated by: Claude Sonnet 4.6
#
# Manages the session state file (~/.config/wayland-desktop/session_state.json),
# which maps each snapshot entry's tracking_uuid to the live internalId of
# the window that was placed at restore time.
#
# This is the adopted alternative to Qt dynamic properties (setProperty /
# property), which were confirmed unavailable in the KWin JS sandbox on
# 2026-03-21.  See ADR-260321-01.
#
# File format (JSON):
#   {
#     "<tracking_uuid>": {
#       "internalId":     "<kwin internalId UUID>",
#       "app_alias":      "thunderbird",
#       "resource_class": "thunderbird-esr",
#       "desktop":        "Main",
#       "screen":         "main",
#       "placed_at":      "2026-03-21T21:55:00"
#     },
#     ...
#   }
#
# Entries are session-scoped: they are valid only until the next reboot.
# On load, entries from previous boot sessions are pruned automatically
# using /proc/uptime to determine the current session start time.
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import json
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any


# Default path for the session state file
STATE_PATH = Path("~/.config/wayland-desktop/session_state.json").expanduser()


# ── SessionEntry ──────────────────────────────────────────────────────────────

@dataclass
class SessionEntry:
    """
    One entry in the session state file.

    Maps a snapshot tracking_uuid to the live internalId of the window that
    was placed at restore time, plus enough metadata for diagnostics and
    stale-entry detection.
    """
    tracking_uuid: str   # UUID from snapshot YAML (stable across restores)
    internal_id:   str   # KWin internalId (session-scoped; changes on reboot)
    app_alias:     str   # friendly name from config, or resourceClass
    resource_class: str  # KWin resourceClass
    desktop:       str   # desktop alias or canonical name at restore time
    screen:        str   # screen alias or connector name at restore time
    placed_at:     str   # ISO timestamp of when this entry was written

    def to_dict(self) -> dict[str, Any]:
        return {
            "internalId":     self.internal_id,
            "app_alias":      self.app_alias,
            "resource_class": self.resource_class,
            "desktop":        self.desktop,
            "screen":         self.screen,
            "placed_at":      self.placed_at,
        }

    @classmethod
    def from_dict(cls, tracking_uuid: str, d: dict[str, Any]) -> "SessionEntry":
        return cls(
            tracking_uuid = tracking_uuid,
            internal_id   = str(d.get("internalId",     "")),
            app_alias     = str(d.get("app_alias",      "")),
            resource_class= str(d.get("resource_class", "")),
            desktop       = str(d.get("desktop",        "")),
            screen        = str(d.get("screen",         "")),
            placed_at     = str(d.get("placed_at",      "")),
        )


# ── SessionState ──────────────────────────────────────────────────────────────

class SessionState:
    """
    In-memory representation of the session state file.

    Usage pattern in kwin_restore.py:
        state = SessionState.load()
        # ... restore windows ...
        state.upsert(SessionEntry(...))
        state.save()

    Usage pattern in kwin_realign.py:
        state = SessionState.load()
        entry = state.get("a3f2b8c1-...")
        if entry:
            # scan workspace.windowList() for entry.internal_id
    """

    def __init__(self) -> None:
        # Keyed by tracking_uuid
        self._entries: dict[str, SessionEntry] = {}

    # ── Loading ───────────────────────────────────────────────────────────────

    @classmethod
    def load(cls, path: Path | str | None = None) -> "SessionState":
        """
        Load the session state file.

        Automatically prunes entries from previous boot sessions: any entry
        whose placed_at timestamp predates the current boot time is stale and
        is discarded.  If the file does not exist, returns an empty state.

        Args:
            path: Path to the state file.  Defaults to STATE_PATH.
        """
        state = cls()
        fpath = Path(path).expanduser() if path else STATE_PATH

        if not fpath.exists():
            return state

        try:
            raw = json.loads(fpath.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            # Corrupt or unreadable — start fresh rather than crash
            return state

        boot_time = _boot_time()

        for tracking_uuid, entry_dict in raw.items():
            entry = SessionEntry.from_dict(tracking_uuid, entry_dict)

            # Prune entries from previous boot sessions
            if entry.placed_at:
                try:
                    placed = datetime.fromisoformat(entry.placed_at)
                    if placed < boot_time:
                        continue   # stale — belongs to a previous session
                except ValueError:
                    pass   # unparseable timestamp — keep the entry

            state._entries[tracking_uuid] = entry

        return state

    # ── Mutation ──────────────────────────────────────────────────────────────

    def upsert(self, entry: SessionEntry) -> None:
        """
        Add or update an entry.  If an entry with the same tracking_uuid
        already exists, it is replaced (handles the case where the same app
        is re-restored mid-session after being closed).
        """
        self._entries[entry.tracking_uuid] = entry

    def remove(self, tracking_uuid: str) -> bool:
        """Remove an entry by tracking_uuid.  Returns True if it existed."""
        return self._entries.pop(tracking_uuid, None) is not None

    # ── Query ─────────────────────────────────────────────────────────────────

    def get(self, tracking_uuid: str) -> SessionEntry | None:
        """Return the entry for a tracking_uuid, or None if not found."""
        return self._entries.get(tracking_uuid)

    def get_by_internal_id(self, internal_id: str) -> SessionEntry | None:
        """
        Reverse lookup: find the entry whose internalId matches.
        O(n) scan — only used for diagnostics; normal path uses get().
        """
        bare = internal_id.strip("{}")
        for entry in self._entries.values():
            if entry.internal_id.strip("{}") == bare:
                return entry
        return None

    def all_entries(self) -> list[SessionEntry]:
        """Return all entries, sorted by app_alias for consistent display."""
        return sorted(self._entries.values(), key=lambda e: e.app_alias.lower())

    def __len__(self) -> int:
        return len(self._entries)

    # ── Persistence ───────────────────────────────────────────────────────────

    def save(self, path: Path | str | None = None) -> None:
        """
        Write the current state to the JSON file.

        The file is written atomically: the data is assembled in memory, then
        written to a temporary file in the same directory, then renamed over
        the target.  This prevents a partial write from corrupting the state
        file if the process is interrupted.

        Args:
            path: Destination path.  Defaults to STATE_PATH.
        """
        fpath = Path(path).expanduser() if path else STATE_PATH
        fpath.parent.mkdir(parents=True, exist_ok=True)

        payload: dict[str, Any] = {}
        for tracking_uuid, entry in self._entries.items():
            payload[tracking_uuid] = entry.to_dict()

        # Write to a sibling temp file, then rename atomically
        tmp = fpath.with_suffix(".json.tmp")
        try:
            tmp.write_text(
                json.dumps(payload, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            tmp.replace(fpath)
        except OSError:
            tmp.unlink(missing_ok=True)
            raise

    # ── Diagnostics ───────────────────────────────────────────────────────────

    def dump(self) -> None:
        """Print all entries to stdout (for --show-state or debugging)."""
        if not self._entries:
            print("  (empty)")
            return
        for entry in self.all_entries():
            print(f"  {entry.tracking_uuid}")
            print(f"    app       : {entry.app_alias}  ({entry.resource_class})")
            print(f"    internalId: {entry.internal_id}")
            print(f"    placement : {entry.desktop} / {entry.screen}")
            print(f"    placed_at : {entry.placed_at}")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _boot_time() -> datetime:
    """
    Return the approximate system boot time by reading /proc/uptime.

    /proc/uptime contains two fields: seconds since boot, and idle seconds.
    We subtract uptime from now to get the boot timestamp.

    Falls back to 24 hours ago if /proc/uptime is unavailable (non-Linux).
    """
    try:
        uptime_s = float(Path("/proc/uptime").read_text().split()[0])
        # Subtract a small buffer (60s) to avoid pruning entries written
        # just before a very recent reboot where clock drift could cause
        # placed_at to appear fractionally before boot_time.
        return datetime.now() - timedelta(seconds=uptime_s) - timedelta(seconds=60)
    except Exception:
        return datetime.now() - timedelta(hours=24)


def make_entry(
    tracking_uuid: str,
    internal_id:   str,
    app_alias:     str,
    resource_class: str,
    desktop:       str,
    screen:        str,
) -> SessionEntry:
    """
    Convenience constructor that fills in placed_at with the current time.
    Used by kwin_restore.py after each successful placement.
    """
    return SessionEntry(
        tracking_uuid = tracking_uuid,
        internal_id   = internal_id,
        app_alias     = app_alias,
        resource_class= resource_class,
        desktop       = desktop,
        screen        = screen,
        placed_at     = datetime.now().isoformat(timespec="seconds"),
    )
