# =============================================================================
# kwin_lib/snapshot.py
# Generated by: Claude Sonnet 4.6
#
# Captures the current window layout as a structured snapshot, suitable for
# saving to YAML and later restoring with kwin_restore.py.
#
# For each user-facing window the snapshot records:
#   - resourceClass and app alias (from config)
#   - desktop name and alias
#   - screen name and alias
#   - maximized / minimized state
#   - geometry (x, y, width, height) — for non-maximized windows
#   - launch command (from .desktop file Exec= line when available)
#   - single_instance flag (from config, or heuristic default)
#
# System windows (plasmashell, ibus, etc.) are excluded by default.
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import os
import re
import shlex
import subprocess
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

from .config import KWinConfig, get_config
from .bus    import KWinBus, ScriptRunner
from .models import window_from_kwin_dict


# ── Desktop file search paths ─────────────────────────────────────────────────

_DESKTOP_SEARCH_PATHS: list[Path] = [
    Path("~/.local/share/applications").expanduser(),
    Path("/usr/share/applications"),
    Path("/usr/local/share/applications"),
    Path("/var/lib/flatpak/exports/share/applications"),
    Path(os.environ.get("XDG_DATA_HOME", "~/.local/share")).expanduser()
    / "applications",
]

# Field codes to strip from Exec= lines (per freedesktop.org spec)
_FIELD_CODE_RE = re.compile(r"%[fFuUdDnNickKvmb%]")


def find_desktop_file(desktop_name: str) -> Path | None:
    """
    Locate a .desktop file by its base name (without extension).
    Searches user-local paths before system paths.
    Returns the first match, or None.
    """
    if not desktop_name:
        return None
    filename = desktop_name if desktop_name.endswith(".desktop") \
               else f"{desktop_name}.desktop"
    for base in _DESKTOP_SEARCH_PATHS:
        candidate = base / filename
        if candidate.exists():
            return candidate
    return None


def parse_exec_from_desktop(path: Path) -> str:
    """
    Extract and clean the Exec= command from a .desktop file.
    Strips field codes (%f, %u, etc.), %env wrappers, and env var prefixes.
    Returns an empty string if Exec= is not found or cannot be parsed.
    """
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""

    # Find Exec= in [Desktop Entry] section
    in_entry = False
    for line in content.splitlines():
        stripped = line.strip()
        if stripped == "[Desktop Entry]":
            in_entry = True
            continue
        if stripped.startswith("[") and stripped != "[Desktop Entry]":
            if in_entry:
                break   # left the Desktop Entry section
        if not in_entry:
            continue
        if stripped.startswith("Exec="):
            raw = stripped[5:].strip()
            # Strip field codes
            cmd = _FIELD_CODE_RE.sub("", raw).strip()
            # Strip env var prefixes like  env FOO=bar actual-command
            if cmd.startswith("env "):
                parts = shlex.split(cmd)
                # Drop "env" and any KEY=VALUE tokens
                cmd = " ".join(
                    p for p in parts[1:]
                    if "=" not in p
                )
            return cmd.strip()
    return ""


def resolve_command(
    resource_class:   str,
    desktop_filename: str,
    config:           KWinConfig,
) -> str:
    """
    Best-effort: determine the shell command to relaunch this app.

    Resolution order:
      1. Explicit command override in config apps section
      2. Exec= from .desktop file named by desktopFileName
      3. Exec= from .desktop file named by resourceClass
      4. resourceClass itself as a bare command (last resort)
    """
    # 1. Config override
    ac = config.app_by_resource_class(resource_class)
    if ac and ac.command_override:
        return ac.command_override

    # 2. .desktop via desktopFileName
    if desktop_filename:
        path = find_desktop_file(desktop_filename)
        if path:
            cmd = parse_exec_from_desktop(path)
            if cmd:
                return cmd

    # 3. .desktop via resourceClass
    if resource_class:
        path = find_desktop_file(resource_class)
        if path:
            cmd = parse_exec_from_desktop(path)
            if cmd:
                return cmd

    # 4. Bare resourceClass as fallback
    return resource_class


# ── Snapshot entry ────────────────────────────────────────────────────────────

@dataclass
class SnapshotEntry:
    """One window in a layout snapshot."""

    # Identity
    resource_class:   str           # canonical KWin resourceClass
    app_alias:        str           # friendly alias from config, or resourceClass
    desktop_filename: str           # KWin desktopFileName (.desktop base name)

    # Placement (canonical names)
    desktop:          str           # canonical desktop name, e.g. "Plumbing"
    desktop_alias:    str           # alias if defined, e.g. "Plumbing"
    screen:           str           # connector name, e.g. "HDMI-A-2"
    screen_alias:     str           # alias if defined, e.g. "main"

    # State
    maximized:        bool
    minimized:        bool
    on_all_desktops:  bool

    # Geometry (always stored; useful if not maximized)
    x:                int
    y:                int
    width:            int
    height:           int

    # Restoration
    command:          str           # shell command to launch this app
    single_instance:  bool          # skip if already open on restore
    # If True, the app launches to the system tray and never shows a main
    # window.  kwin_restore.py will launch it and immediately move on without
    # waiting for a window to appear.  No placement is performed.
    ignore_window:    bool          = False
    # Launch priority group (0–99, default 50).  Lower values launch first.
    # All entries sharing the same priority are processed together as one batch;
    # batches are separated by a settling pause (PRIORITY_BETWEEN_DELAY in
    # kwin_restore.py) so that high-VRAM applications (e.g. Ollama,
    # plasma-systemmonitor) can complete their GPU memory allocations before
    # lower-priority apps start.  See ADR-260402-01.
    priority:         int           = 50
    # Tile position to apply in phase 3 instead of maximizing.
    # Values: left, right, top, bottom, top-left, top-right,
    #         bottom-left, bottom-right.  Empty string means no tile.
    tile:             str           = ""

    # Session tracking — assigned at snapshot time, stamped onto the KWin
    # window object as a Qt dynamic property ("kwinlib_uuid") at restore time.
    # Allows the realign utility to find any window by UUID scan rather than
    # relying on internalId, which changes between reboots.
    # A new UUID is generated only if the field is absent (e.g. old snapshots).
    tracking_uuid:    str = ""

    # Input actions — DSL string executed against this window in phase 4.
    # Populated by hand after capture; never written by kwin_snapshot.py.
    # See docs/SNAPSHOT.md for the full DSL reference and YAML examples.
    input_actions:    str = ""

    # Metadata
    caption:          str = ""      # window title at snapshot time (FYI only)
    pid:              int = 0       # PID at snapshot time (FYI only)

    def to_dict(self) -> dict[str, Any]:
        """
        Return a clean dict suitable for YAML serialisation.

        Windows that appear on all desktops use desktop: '*' rather than
        the on_all_desktops flag, keeping the representation consistent
        with how the rest of the library accepts desktop specifications.
        The on_all_desktops field is omitted from the output entirely.
        """
        if self.on_all_desktops:
            desktop_val = "*"
        else:
            desktop_val = self.desktop_alias

        return {
            "app":              self.app_alias,
            "resource_class":   self.resource_class,
            "desktop_filename": self.desktop_filename,
            "desktop":          desktop_val,
            "screen":           self.screen_alias,
            "maximized":        self.maximized,
            "minimized":        self.minimized,
            "x":                self.x,
            "y":                self.y,
            "width":            self.width,
            "height":           self.height,
            "command":          self.command,
            "single_instance":  self.single_instance,
            "ignore_window":    self.ignore_window,
            "priority":         self.priority,
            "tile":             self.tile,
            # Session tracking UUID — stamped onto the KWin window object
            # at restore time as Qt dynamic property "kwinlib_uuid".
            "tracking_uuid":    self.tracking_uuid,
            # Input actions — DSL string for phase 4 keyboard/mouse injection.
            # Leave empty; fill in by hand after capture.
            # See docs/SNAPSHOT.md for the full DSL reference and YAML examples.
            "input_actions":    self.input_actions,
            # Informational — not used by restore
            "_caption":         self.caption,
            "_pid":             self.pid,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "SnapshotEntry":
        """
        Reconstruct from a dict loaded from YAML.

        Handles both the current format (desktop: '*') and the legacy
        format (on_all_desktops: true) so older snapshot files remain
        readable after upgrading.

        If tracking_uuid is absent (old snapshot file), a fresh UUID is
        generated so the entry is immediately usable for restore+stamp.
        """
        import uuid as _uuid

        desktop_raw     = str(d.get("desktop", ""))
        on_all_desktops = (
            desktop_raw in ("*", "all")
            or bool(d.get("on_all_desktops", False))
        )
        desktop_val = "*" if on_all_desktops else desktop_raw

        # Preserve existing UUID if present; generate a new one if absent.
        # This ensures old snapshot files gain a UUID automatically on first
        # load, which will be stamped onto the window at restore time.
        tracking_uuid = str(d.get("tracking_uuid", "") or "").strip()
        if not tracking_uuid:
            tracking_uuid = str(_uuid.uuid4())

        return cls(
            resource_class   = str(d.get("resource_class",   "")),
            app_alias        = str(d.get("app",              "")),
            desktop_filename = str(d.get("desktop_filename", "")),
            desktop          = desktop_val,
            desktop_alias    = desktop_val,
            screen           = str(d.get("screen",           "")),
            screen_alias     = str(d.get("screen",           "")),
            maximized        = bool(d.get("maximized",        False)),
            minimized        = bool(d.get("minimized",        False)),
            on_all_desktops  = on_all_desktops,
            x                = int(d.get("x",                 0)),
            y                = int(d.get("y",                 0)),
            width            = int(d.get("width",             0)),
            height           = int(d.get("height",            0)),
            command          = str(d.get("command",           "")),
            single_instance  = bool(d.get("single_instance",  False)),
            ignore_window    = bool(d.get("ignore_window",     False)),
            priority         = max(0, min(99, int(d.get("priority", 50) or 50))),
            tile             = str(d.get("tile",               "")).strip(),
            tracking_uuid    = tracking_uuid,
            input_actions    = str(d.get("input_actions",      "") or "").strip(),
            caption          = str(d.get("_caption",          "")),
            pid              = int(d.get("_pid",              0)),
        )


# ── Layout snapshot ───────────────────────────────────────────────────────────

@dataclass
class LayoutSnapshot:
    """A complete snapshot of the current window layout."""
    timestamp:   str
    hostname:    str
    entries:     list[SnapshotEntry] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "meta": {
                "timestamp": self.timestamp,
                "hostname":  self.hostname,
                "note": (
                    "Restore with: python3 kwin_restore.py <this_file>\n"
                    "Edit 'command' fields if an app doesn't launch correctly.\n"
                    "Set single_instance: true to skip apps already running.\n"
                    "Fields prefixed with _ are informational only."
                ),
            },
            "windows": [e.to_dict() for e in self.entries],
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "LayoutSnapshot":
        meta    = d.get("meta", {})
        entries = [SnapshotEntry.from_dict(e) for e in d.get("windows", [])]
        return cls(
            timestamp = str(meta.get("timestamp", "")),
            hostname  = str(meta.get("hostname",  "")),
            entries   = entries,
        )

    def _write_yaml(self, out, config: Any = None) -> None:
        """
        Write the snapshot as formatted YAML to any file-like object.

        Called by both save() (real file) and to_yaml_text() (StringIO) so
        both paths produce byte-for-byte identical output.

        The output is grouped by virtual desktop in config order.  Within
        each desktop group, entries are sorted alphabetically by app alias
        so that successive snapshots diff cleanly and predictably.
        Windows visible on all desktops appear last under 'All desktops'.

        Args:
            out:    Any object with a write(str) method.
            config: KWinConfig used for desktop sort order and alias display.
                    If None, desktops sort alphabetically, aliases not applied.
        """
        import yaml as _yaml
        from itertools import groupby

        # ── Build desktop order from config ──────────────────────────────────
        # Config desktops dict is insertion-ordered (Python 3.7+); the user
        # maintains it in the order they want desktops to appear in snapshots.
        config_order = list(config.desktops.values()) if config is not None else []

        def desktop_sort_key(entry: "SnapshotEntry") -> tuple:
            """
            Three-level sort key: (group, desktop_position, app_alias).
              group 0 — windows on a specific desktop (sorted by config order)
              group 1 — all-desktops windows (sorted last)
            Within each desktop, entries sort alphabetically by app_alias so
            that snapshots diff cleanly regardless of capture order.
            """
            app_key = entry.app_alias.lower()
            if entry.on_all_desktops or entry.desktop == "*":
                return (1, "", app_key)
            canonical = entry.desktop
            try:
                pos = config_order.index(canonical)
            except ValueError:
                pos = len(config_order)   # unknown desktops sort after known ones
            return (0, f"{pos:06d}{canonical}", app_key)

        sorted_entries = sorted(self.entries, key=desktop_sort_key)

        # ── Group entries by desktop ──────────────────────────────────────────
        def group_key(entry: "SnapshotEntry") -> str:
            return "*" if (entry.on_all_desktops or entry.desktop == "*") \
                       else entry.desktop

        groups: list[tuple[str, list["SnapshotEntry"]]] = []
        for desktop_key, grp in groupby(sorted_entries, key=group_key):
            groups.append((desktop_key, list(grp)))

        # ── Helper: serialise one entry to indented YAML lines ────────────────
        def entry_to_yaml_lines(e: "SnapshotEntry") -> list[str]:
            """
            Render one entry dict as a YAML block-sequence item.
            yaml.dump produces "key: value\n..." lines; we prefix the first
            line with '- ' and subsequent lines with '  ' to nest it under
            the parent 'windows:' sequence.
            """
            d = e.to_dict()
            raw = _yaml.dump(
                d,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
            ).rstrip("\n")
            lines = raw.split("\n")
            result = ["- " + lines[0]]
            result += ["  " + l for l in lines[1:]]
            return result

        # ── Write header ──────────────────────────────────────────────────────
        out.write("# =============================================================================\n")
        out.write(f"# KWin desktop layout snapshot\n")
        out.write(f"# Captured: {self.timestamp}  host: {self.hostname}\n")
        out.write("#\n")
        out.write("# Restore with: python3 kwin_restore.py --setup <this_file>\n")
        out.write("# Edit 'command' fields if an app doesn't launch correctly.\n")
        out.write("# Set single_instance: true to skip apps already running.\n")
        out.write("# Fields prefixed with _ are informational only.\n")
        out.write("# desktop: '*' means the window appears on ALL virtual desktops.\n")
        out.write("# input_actions: DSL string for keyboard/mouse setup in phase 4.\n")
        out.write("#   Leave blank or fill in by hand. See docs/SNAPSHOT.md.\n")
        out.write("# priority: launch order group (0=first launched, 99=last; default 50).\n")
        out.write("#   Entries sharing a priority value are processed as one batch.\n")
        out.write("# =============================================================================\n")
        out.write("\n")
        out.write(f"meta:\n")
        out.write(f"  timestamp: '{self.timestamp}'\n")
        out.write(f"  hostname:  '{self.hostname}'\n")
        out.write("\n")
        out.write("windows:\n")

        # ── Write desktop groups ──────────────────────────────────────────────
        first_group = True
        for desktop_key, entries in groups:
            if desktop_key == "*":
                heading = "All desktops"
            else:
                alias = (config.alias_desktop(desktop_key)
                         if config else desktop_key)
                heading = f"{alias}  ({desktop_key})" if alias != desktop_key \
                          else desktop_key

            separator = "=" * (len(heading) + 4)
            # One extra blank line between desktop sections (each entry already
            # writes two trailing blank lines, giving two total between groups).
            if not first_group:
                out.write("\n")
            first_group = False

            out.write(f"  # {separator}\n")
            out.write(f"  # | {heading} |\n")
            out.write(f"  # {separator}\n")
            out.write("\n")

            for entry in entries:
                lines = entry_to_yaml_lines(entry)
                for line in lines:
                    out.write(f"  {line}\n")
                out.write("\n\n")   # two blank lines between entries

    def to_yaml_text(self, config: Any = None) -> str:
        """
        Return the complete snapshot as a formatted YAML string.

        Produces the same output as save() but returns it as a string
        rather than writing to disk.  Used by kwin_snapshot.py to print
        the layout to stdout immediately after capture.
        """
        import io
        buf = io.StringIO()
        self._write_yaml(buf, config)
        return buf.getvalue()

    def save(self, path: Path | str, config: Any = None) -> None:
        """
        Write the snapshot to a YAML file.

        The output is grouped by virtual desktop in config order, with
        entries within each desktop sorted alphabetically by app alias
        for consistent, diff-friendly output.  All-desktops windows appear
        last.

        Args:
            path:   Destination file path (parent directories are created).
            config: KWinConfig used for desktop sort order and alias display.
                    If None, desktops sort alphabetically.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            self._write_yaml(f, config)

    @classmethod
    def load(cls, path: Path | str) -> "LayoutSnapshot":
        """Load a snapshot from a YAML file."""
        import yaml
        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        return cls.from_dict(data)


# ── Snapshot capture ──────────────────────────────────────────────────────────

# The JS used to enumerate all windows with full placement data
_ENUMERATE_JS = """
var wins   = workspace.windowList();
var result = [];
for (var i = 0; i < wins.length; i++) {
    var w = wins[i];
    try {
        result.push({
            internalId:      String(w.internalId      || ""),
            resourceClass:   String(w.resourceClass   || ""),
            resourceName:    String(w.resourceName    || ""),
            caption:         String(w.caption         || ""),
            desktopFileName: String(w.desktopFileName || ""),
            pid:             Number(w.pid             || 0),
            desktopId:   w.desktops&&w.desktops.length>0
                             ? String(w.desktops[0].id||"")   : "",
            desktopName: w.desktops&&w.desktops.length>0
                             ? String(w.desktops[0].name||"") : "",
            outputName:      String(w.output ? (w.output.name||"") : ""),
            x:               Number(w.x      || 0),
            y:               Number(w.y      || 0),
            width:           Number(w.width  || 0),
            height:          Number(w.height || 0),
            minimized:       Boolean(w.minimized),
            maximized:       Boolean(w.maximized),
            fullScreen:      Boolean(w.fullScreen),
            onAllDesktops:   Boolean(w.onAllDesktops),
        });
    } catch(e) {}
}
send({ windows: result });
"""


def capture_snapshot(
    runner:          ScriptRunner,
    config:          KWinConfig | None = None,
    include_system:  bool              = False,
) -> LayoutSnapshot:
    """
    Enumerate all open windows and return a LayoutSnapshot.

    Each entry receives a freshly generated tracking_uuid.  This UUID is
    later stamped onto the live KWin window object as a Qt dynamic property
    ("kwinlib_uuid") by kwin_restore.py, enabling the realign utility to
    find any window by UUID scan rather than by fragile internalId matching.

    Args:
        runner:         ScriptRunner connected to a live KWin session
        config:         KWinConfig for alias resolution (uses get_config() if None)
        include_system: If True, include system/compositor windows in the snapshot
    """
    import socket
    import uuid as _uuid
    from datetime import datetime

    cfg = config if config is not None else get_config()

    result = runner.run("enumerate_windows", _ENUMERATE_JS)
    if "fatalError" in result:
        raise RuntimeError(f"Window enumeration failed: {result['fatalError']}")
    if "timeout" in result:
        raise RuntimeError("Window enumeration timed out")

    raw_windows = result.get("windows", [])
    entries: list[SnapshotEntry] = []

    for w in raw_windows:
        rc = str(w.get("resourceClass") or "")

        # Filter system windows unless explicitly included
        if not include_system and cfg.is_system_window(rc):
            continue

        # Skip windows with no resourceClass (shouldn't happen, but defensive)
        if not rc:
            continue

        desktop_name  = str(w.get("desktopName") or "")
        screen_name   = str(w.get("outputName")  or "")
        df            = str(w.get("desktopFileName") or "")

        # Resolve command
        command = resolve_command(rc, df, cfg)

        entries.append(SnapshotEntry(
            resource_class   = rc,
            app_alias        = cfg.alias_resource_class(rc),
            desktop_filename = df,
            desktop          = desktop_name,
            desktop_alias    = cfg.alias_desktop(desktop_name),
            screen           = screen_name,
            screen_alias     = cfg.alias_screen(screen_name),
            maximized        = bool(w.get("maximized")),
            minimized        = bool(w.get("minimized")),
            on_all_desktops  = bool(w.get("onAllDesktops")),
            x                = int(w.get("x",      0)),
            y                = int(w.get("y",      0)),
            width            = int(w.get("width",  0)),
            height           = int(w.get("height", 0)),
            command          = command,
            single_instance  = cfg.is_single_instance(rc),
            ignore_window    = cfg.is_ignore_window(rc),
            priority         = 50,   # default; set by hand in the YAML after capture
            tile             = cfg.get_tile(rc),
            tracking_uuid    = str(_uuid.uuid4()),   # unique per window per snapshot
            caption          = str(w.get("caption") or ""),
            pid              = int(w.get("pid") or 0),
        ))

    return LayoutSnapshot(
        timestamp = datetime.now().isoformat(timespec="seconds"),
        hostname  = socket.gethostname(),
        entries   = entries,
    )
