# =============================================================================
# kwin_lib/window.py
# Generated by: Claude Sonnet 4.6
#
# Window mutation operations — all implemented as KWin JS scripts that call
# back to Python via callDBus().
#
# Key design notes from testing:
#   • frameGeometry position (x, y) can be set; size is ignored by Wayland
#     apps (the compositor cannot force a client to resize)
#   • Screen assignment uses workspace.sendClientToScreen(window, output);
#     the output object is found by iterating workspace.screens by name.
#     Note: __w.output.name does NOT update within the same script execution
#     after sendClientToScreen() -- fire-and-trust, same as tile().
#   • Desktop assignment uses w.desktops = [desktopObject]
#   • w.output is read-only; sendToOutput() does not exist in this KWin
#   • Qt.rect() is not available in the scripting sandbox
#   • setMaximize(h, v), minimized, activeWindow all work as expected
#   • Spin-wait loops (Date.now()) are used for intra-script delays because
#     KWin's JS sandbox has no async/await or setTimeout
#
# Result shape convention:
#   Every JS send() call returns at minimum:
#     { ok: bool, op: string }
#   Plus op-specific fields as documented per method.
#   elapsed_ms is injected by ScriptRunner.run() on the Python side.
#
# Verbose mode:
#   Construct WindowManager with verbose=True to print a debug line after
#   every KWin script call showing the op name, result dict, and timing.
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations
from typing import Any

from .bus import KWinBus, ScriptRunner
from .models import DesktopInfo, ScreenInfo, WindowInfo, window_from_kwin_dict


# ── JS fragments shared by all window scripts ─────────────────────────────────

# Finds __w by UUID; sends an error and falls through if not found.
# The caller's JS body is injected between _FIND_OPEN and _FIND_CLOSE.
_FIND_OPEN = """\
var __bare = "{uuid}";
var __wins = workspace.windowList();
var __w    = null;
for (var i = 0; i < __wins.length; i++) {{
    if (String(__wins[i].internalId).replace(/[{{}}]/g,"") === __bare) {{
        __w = __wins[i]; break;
    }}
}}
if (!__w) {{ send({{ ok: false, op: "{op}", error: "window not found", uuid: __bare }}); }}
else {{
"""

_FIND_CLOSE = "}"


def _find_block(uuid: str, op: str) -> tuple[str, str]:
    """Return (open_block, close_block) for injecting around a JS body."""
    bare = uuid.strip("{}")
    return _FIND_OPEN.format(uuid=bare, op=op), _FIND_CLOSE


class WindowManager:
    """
    High-level window operations.  All mutations are executed inside a KWin
    JS script via the scripting engine, with results returned via callDBus().

    All methods raise RuntimeError on failure unless noted otherwise.

    Args:
        kwin:    KWinBus instance connected to the session bus.
        runner:  ScriptRunner instance for executing JS snippets.
        verbose: If True, print a debug line after every KWin script call
                 showing the op name, result dict, and elapsed time.
    """

    def __init__(
        self,
        kwin:    KWinBus,
        runner:  ScriptRunner,
        verbose: bool = False,
    ) -> None:
        self._kwin    = kwin
        self._runner  = runner
        self._verbose = verbose

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _run_window_op(
        self,
        uuid:     str,
        op:       str,
        js_inner: str,
    ) -> dict[str, Any]:
        """
        Run a KWin JS script that operates on a single window.

        Wraps js_inner with the standard window-find preamble and error
        handler, runs the script, checks for common failure modes, and
        returns the result dict (which always includes elapsed_ms from
        ScriptRunner).

        Args:
            uuid:     Window internalId (with or without braces).
            op:       Operation name — used in error messages and JS send().
            js_inner: JS body to execute once the window is found in __w.
                      Must end with a send({ok:true, op:"...", ...}) call.

        Raises:
            RuntimeError: on timeout, load error, fatal JS error, or any
                          error key in the result dict.
        """
        open_b, close_b = _find_block(uuid, op)
        result = self._runner.run(op, f"""
{open_b}
{js_inner}
{close_b}
""")
        if self._verbose:
            ms = result.get("elapsed_ms", "?")
            print(f"  [DBG] {op:30s} -> {result}  ({ms}ms)")
        self._check(result, op)
        return result

    @staticmethod
    def _check(result: dict[str, Any], op: str) -> None:
        """Raise RuntimeError for common failure modes."""
        if result.get("timeout"):
            raise RuntimeError(f"{op}: KWin script timed out")
        if "loadError" in result:
            raise RuntimeError(f"{op}: script load failed: {result['loadError']}")
        if "fatalError" in result:
            raise RuntimeError(f"{op}: {result['fatalError']}")
        if "error" in result:
            raise RuntimeError(f"{op}: {result['error']}")

    # ── Runtime configuration ─────────────────────────────────────────────────

    def set_verbose(self, verbose: bool) -> None:
        """Update the verbose flag at runtime (e.g. from a window checkbox)."""
        self._verbose = verbose

    # ── Query ─────────────────────────────────────────────────────────────────

    def get_info(self, uuid: str) -> WindowInfo:
        """
        Return current WindowInfo for a window by internalId UUID.
        Uses KWin's getWindowInfo() D-Bus method directly (no script needed).
        Raises RuntimeError if the window is not found.
        """
        props = self._kwin.get_window_info(uuid)
        if props is None:
            raise RuntimeError(f"Window not found or closed: {uuid}")

        normalised = dict(props)
        normalised.setdefault("internalId", uuid)
        for src, dst in [
            ("desktopId",        "desktopId"),
            ("x11DesktopNumber", "desktopId"),
        ]:
            if src in normalised and "desktopId" not in normalised:
                normalised["desktopId"] = normalised[src]

        return window_from_kwin_dict(normalised)

    def find_by_class(self, resource_class: str) -> list[WindowInfo]:
        """
        Return all open windows whose resourceClass matches (case-insensitive).
        Uses a KWin script to enumerate workspace.windowList().
        """
        rc = resource_class.lower()
        result = self._runner.run("find_by_class", f"""
var rc   = "{rc}";
var wins = workspace.windowList();
var arr  = [];
for (var i = 0; i < wins.length; i++) {{
    var w = wins[i];
    if (String(w.resourceClass||"").toLowerCase() === rc) {{
        arr.push({{
            internalId:      String(w.internalId      || ""),
            resourceClass:   String(w.resourceClass   || ""),
            resourceName:    String(w.resourceName    || ""),
            caption:         String(w.caption         || ""),
            desktopFileName: String(w.desktopFileName || ""),
            pid:             Number(w.pid             || 0),
            desktopId:   w.desktops&&w.desktops.length>0
                             ? String(w.desktops[0].id||"")   : "",
            desktopName: w.desktops&&w.desktops.length>0
                             ? String(w.desktops[0].name||"") : "",
            outputName:      String(w.output ? (w.output.name||"") : ""),
            x:               Number(w.x      || 0),
            y:               Number(w.y      || 0),
            width:           Number(w.width  || 0),
            height:          Number(w.height || 0),
            minimized:       Boolean(w.minimized),
            maximized:       Boolean(w.maximized),
            fullScreen:      Boolean(w.fullScreen),
            onAllDesktops:   Boolean(w.onAllDesktops),
        }});
    }}
}}
send({{ windows: arr }});
""")
        if self._verbose:
            ms = result.get("elapsed_ms", "?")
            n  = len(result.get("windows", []))
            print(f"  [DBG] {'find_by_class':30s} -> {n} window(s)  ({ms}ms)")
        if "fatalError" in result:
            raise RuntimeError(f"find_by_class error: {result['fatalError']}")
        if "timeout" in result:
            raise RuntimeError("find_by_class timed out")
        return [window_from_kwin_dict(d) for d in result.get("windows", [])]

    # ── Desktop operations ────────────────────────────────────────────────────

    def move_to_desktop(self, uuid: str, desktop: DesktopInfo) -> None:
        """
        Move a window to a virtual desktop.
        The window will no longer be visible on its previous desktop.
        Use set_on_all_desktops(uuid, True) to make it visible everywhere.

        Result fields: ok, op, landed_on (desktop UUID read-back),
                       worked (bool — landed_on == target).
        """
        target_id = desktop.id
        result = self._run_window_op(uuid, "move_to_desktop", f"""
    var targetId = "{target_id}";
    var desks    = workspace.desktops;
    var target   = null;
    for (var i = 0; i < desks.length; i++) {{
        if (String(desks[i].id||"") === targetId) {{
            target = desks[i]; break;
        }}
    }}
    if (!target) {{
        send({{ ok: false, op: "move_to_desktop",
                error: "desktop not found in workspace.desktops",
                id: targetId }});
    }} else {{
        __w.desktops = [target];
        var pause = Date.now(); while(Date.now()-pause < 200) {{}}
        var ds       = __w.desktops;
        var landedOn = ds&&ds.length>0 ? String(ds[0].id||"") : "";
        send({{ ok: true, op: "move_to_desktop",
                landed_on: landedOn,
                worked:    landedOn === targetId }});
    }}
""")
        if not result.get("worked"):
            raise RuntimeError(
                f"move_to_desktop: expected {target_id!r}, "
                f"got {result.get('landed_on')!r}")

    def set_on_all_desktops(self, uuid: str, on_all: bool) -> None:
        """
        Make a window visible on all virtual desktops (or restrict it).

        Result fields: ok, op, read_back (bool — value of onAllDesktops
                       read back after the assignment).
        """
        val = "true" if on_all else "false"
        self._run_window_op(uuid, "set_on_all_desktops", f"""
    __w.onAllDesktops = {val};
    var pause = Date.now(); while(Date.now()-pause < 100) {{}}
    send({{ ok: true, op: "set_on_all_desktops",
            read_back: Boolean(__w.onAllDesktops) }});
""")

    # ── Screen operations ─────────────────────────────────────────────────────

    def move_to_screen(self, uuid: str, screen: ScreenInfo) -> None:
        """
        Move a window to a specific screen using workspace.sendClientToScreen().

        This is the proper KWin API for screen assignment — it takes a window
        object and an output object directly, with no geometry tricks.
        Confirmed working via Test N (2026-03-22).

        No read-back verification is performed: __w.output.name does not
        update within the same script execution (stale property, same issue
        as tile()).  The call is fire-and-trust; if the screen name is not
        found at all, an error is returned and RuntimeError is raised.

        Result fields: ok, op.
        """
        self._run_window_op(uuid, "move_to_screen", f"""
    var targetOutput = null;
    var allScreens   = workspace.screens;
    for (var i = 0; i < allScreens.length; i++) {{
        if (String(allScreens[i].name) === "{screen.name}") {{
            targetOutput = allScreens[i];
            break;
        }}
    }}
    if (!targetOutput) {{
        send({{ ok: false, op: "move_to_screen",
                error: "screen not found: {screen.name}" }});
    }} else {{
        workspace.sendClientToScreen(__w, targetOutput);
        // No read-back: __w.output.name does not update within the same
        // script execution (stale property -- same issue as tile()).
        send({{ ok: true, op: "move_to_screen" }});
    }}
""")

    def get_screen_geometry(self, uuid: str) -> dict:
        """
        Return the geometry of the screen the window is currently on,
        along with the window's own geometry.

        Returns a dict with keys:
          win_x, win_y, win_w, win_h   -- current window geometry
          scr_x, scr_y, scr_w, scr_h  -- screen geometry
          screen_name                  -- output name
        """
        return self._run_window_op(uuid, "get_screen_geometry", """
    var out = __w.output;
    send({
        ok:          true,
        op:          "get_screen_geometry",
        win_x:       Number(__w.frameGeometry.x),
        win_y:       Number(__w.frameGeometry.y),
        win_w:       Number(__w.frameGeometry.width),
        win_h:       Number(__w.frameGeometry.height),
        scr_x:       out ? Number(out.geometry.x)      : 0,
        scr_y:       out ? Number(out.geometry.y)      : 0,
        scr_w:       out ? Number(out.geometry.width)  : 9999,
        scr_h:       out ? Number(out.geometry.height) : 9999,
        screen_name: out ? String(out.name)            : "",
    });
""")

    # ── Minimize / unminimize ─────────────────────────────────────────────────

    def minimize(self, uuid: str) -> None:
        """
        Minimize (iconify) a window.

        Result fields: ok, op, minimized (bool read-back).
        """
        self._run_window_op(uuid, "minimize", """
    __w.minimized = true;
    var pause = Date.now(); while(Date.now()-pause < 200) {}
    send({ ok: true, op: "minimize", minimized: Boolean(__w.minimized) });
""")

    def unminimize(self, uuid: str) -> None:
        """
        Un-minimize a window without changing its maximize state.

        Use this in phase 2 (before move_to_screen) and in phase 3
        (before applying maximize/tile/raise) so the window has on-screen
        geometry when KWin processes the subsequent operation.

        Result fields: ok, op, minimized (bool read-back -- should be false).
        """
        self._run_window_op(uuid, "unminimize", """
    __w.minimized = false;
    var pause = Date.now(); while(Date.now()-pause < 300) {}
    send({ ok: true, op: "unminimize", minimized: Boolean(__w.minimized) });
""")

    # ── Maximize / restore ────────────────────────────────────────────────────

    def maximize(self, uuid: str) -> None:
        """
        Maximize a window horizontally and vertically.

        Result fields: ok, op, maximized (bool read-back).
        """
        self._set_maximize(uuid, h=True, v=True, op="maximize")

    def unmaximize(self, uuid: str) -> None:
        """
        Remove maximization.

        Result fields: ok, op, maximized (bool read-back).
        """
        self._run_window_op(uuid, "unmaximize", """
    __w.setMaximize(false, false);
    var pause = Date.now(); while(Date.now()-pause < 200) {}
    send({ ok: true, op: "unmaximize", maximized: Boolean(__w.maximized) });
""")

    def maximize_horizontal(self, uuid: str) -> None:
        """Maximize horizontally only."""
        self._set_maximize(uuid, h=True, v=False, op="maximize_h")

    def maximize_vertical(self, uuid: str) -> None:
        """Maximize vertically only."""
        self._set_maximize(uuid, h=False, v=True, op="maximize_v")

    def _set_maximize(self, uuid: str, h: bool, v: bool, op: str) -> None:
        hv = "true" if h else "false"
        vv = "true" if v else "false"
        self._run_window_op(uuid, op, f"""
    __w.setMaximize({hv}, {vv});
    var pause = Date.now(); while(Date.now()-pause < 200) {{}}
    send({{ ok: true, op: "{op}", maximized: Boolean(__w.maximized) }});
""")

    def restore(self, uuid: str) -> None:
        """
        Un-minimize and un-maximize a window.

        Result fields: ok, op, minimized, maximized (bool read-backs).
        """
        self._run_window_op(uuid, "restore", """
    __w.minimized = false;
    __w.setMaximize(false, false);
    var pause = Date.now(); while(Date.now()-pause < 200) {}
    send({ ok: true, op: "restore",
           minimized: Boolean(__w.minimized),
           maximized: Boolean(__w.maximized) });
""")

    # ── Raise / focus ─────────────────────────────────────────────────────────

    def ensure_maximized(
        self,
        uuid:              str,
        width_tolerance:   int = 0,
        height_tolerance:  int = 0,
        logger:            object = None,
    ) -> bool:
        """
        Verify that a window visually fills its screen after maximize().

        Background: on some screens (e.g. high-DPI displays) KWin sets the
        maximized flag but the Wayland client does not immediately resize to
        fill the screen.  The window reports maximized=True in the KWin
        property but its frameGeometry is still the pre-maximize size.

        This method reads back the window and screen geometry and, if the
        window is not within tolerance of the screen dimensions, performs one
        retry: unmaximize() to fully clear state on both sides, then
        maximize() again to issue a fresh configure event.

        Args:
            uuid:             internalId of the window.
            width_tolerance:  pixels by which window width may fall short of
                              screen width and still be considered correct.
            height_tolerance: pixels by which window height may fall short of
                              screen height (e.g. taskbar height).
            logger:           optional ProgressWindowLogger for warn() output.

        Returns:
            True  if the window geometry looks correct (or became correct
                  after the retry).
            False if the geometry is still wrong after one retry.  A warning
                  is logged but no further action is taken.
        """
        def _warn(msg: str) -> None:
            if logger is not None:
                logger.warn(msg)

        try:
            geom = self.get_screen_geometry(uuid)
        except RuntimeError as exc:
            _warn(f"    ensure_maximized: geometry read failed: {exc}")
            return False

        win_w = geom.get("win_w", 0)
        win_h = geom.get("win_h", 0)
        scr_w = geom.get("scr_w", 9999)
        scr_h = geom.get("scr_h", 9999)

        expected_w = scr_w - width_tolerance
        expected_h = scr_h - height_tolerance

        if win_w >= expected_w and win_h >= expected_h:
            return True   # geometry is correct — nothing to do

        # Geometry mismatch — log details and retry.
        _warn(
            f"    ensure_maximized: window {win_w}x{win_h} "
            f"< expected {expected_w}x{expected_h} "
            f"(screen {scr_w}x{scr_h}, "
            f"tol {width_tolerance}x{height_tolerance}) "
            f"— retrying unmaximize + maximize"
        )

        try:
            self.unmaximize(uuid)
            self.maximize(uuid)
        except RuntimeError as exc:
            _warn(f"    ensure_maximized: retry failed: {exc}")
            return False

        # Read geometry once more to confirm.
        try:
            geom2 = self.get_screen_geometry(uuid)
            win_w2 = geom2.get("win_w", 0)
            win_h2 = geom2.get("win_h", 0)
            if win_w2 >= expected_w and win_h2 >= expected_h:
                return True
            _warn(
                f"    ensure_maximized: still wrong after retry — "
                f"window {win_w2}x{win_h2}, expected {expected_w}x{expected_h}"
            )
            return False
        except RuntimeError:
            return False   # can't confirm; treat as unknown

    def raise_window(self, uuid: str) -> None:
        """
        Raise and focus a window.

        Result fields: ok, op.
        """
        self._run_window_op(uuid, "raise_window", """
    workspace.activeWindow = __w;
    var pause = Date.now(); while(Date.now()-pause < 200) {}
    send({ ok: true, op: "raise_window" });
""")

    # ── Geometry ──────────────────────────────────────────────────────────────

    def move(self, uuid: str, x: int, y: int) -> None:
        """
        Move a window to absolute compositor coordinates (x, y).

        Note: on Wayland, window size cannot be changed via the compositor;
        only position is honoured.  To resize, use maximize() instead.

        Result fields: ok, op, x, y (read-back position).
        """
        self._run_window_op(uuid, "move", f"""
    var ww = Number(__w.frameGeometry.width  || 0);
    var wh = Number(__w.frameGeometry.height || 0);
    __w.frameGeometry = {{ x: {x}, y: {y}, width: ww, height: wh }};
    var pause = Date.now(); while(Date.now()-pause < 150) {{}}
    send({{ ok: true, op: "move",
            x: Number(__w.frameGeometry.x),
            y: Number(__w.frameGeometry.y) }});
""")

    def shrink_to_screen(self, uuid: str) -> None:
        """
        Shrink a window to fit within its current screen if it is oversized.

        Calls slotWindowShrinkHorizontal() if window width > screen width,
        and slotWindowShrinkVertical() if window height > screen height.
        Used as a safety step in phase 3 after unminimize, before
        maximize/tile/raise.

        Result fields: ok, op, shrank_h, shrank_v, win_w, win_h.
        """
        self._run_window_op(uuid, "shrink_to_screen", """
    var out  = __w.output;
    var scrW = out ? Number(out.geometry.width)  : 9999;
    var scrH = out ? Number(out.geometry.height) : 9999;
    var winW = Number(__w.frameGeometry.width);
    var winH = Number(__w.frameGeometry.height);

    var shrankH = false;
    var shrankV = false;

    if (winW > scrW) {
        workspace.activeWindow = __w;
        var p1 = Date.now(); while(Date.now()-p1 < 100) {}
        workspace.slotWindowShrinkHorizontal();
        var p2 = Date.now(); while(Date.now()-p2 < 400) {}
        shrankH = true;
    }
    if (winH > scrH) {
        workspace.activeWindow = __w;
        var p3 = Date.now(); while(Date.now()-p3 < 100) {}
        workspace.slotWindowShrinkVertical();
        var p4 = Date.now(); while(Date.now()-p4 < 400) {}
        shrankV = true;
    }

    send({
        ok:       true,
        op:       "shrink_to_screen",
        shrank_h: shrankH,
        shrank_v: shrankV,
        win_w:    Number(__w.frameGeometry.width),
        win_h:    Number(__w.frameGeometry.height),
    });
""")

    # ── Tile ──────────────────────────────────────────────────────────────────

    def tile(self, uuid: str, position: str) -> None:
        """
        Snap a window to a tile position using KWin's built-in slot methods.

        Confirmed working on KDE Plasma 6 / Wayland (2026-03-22).
        See docs/dev/kwin_tile_test.md for the full test results.

        The slot operates on workspace.activeWindow, so the target window is
        set as active before the slot is called.  A 600ms pause follows to
        give KWin time to commit the tile geometry before the next operation.
        We do not read back the geometry — the stale-read issue documented in
        kwin_tile_test.md means the read-back is unreliable within the same
        script, and we do not need it for the move-then-maximize workflow.

        Args:
            uuid:     internalId of the target window.
            position: one of: left, right, top, bottom,
                              top-left, top-right, bottom-left, bottom-right

        Result fields: ok, op, slot.
        """
        slot_map = {
            "left":         "slotWindowQuickTileLeft",
            "right":        "slotWindowQuickTileRight",
            "top":          "slotWindowQuickTileTop",
            "bottom":       "slotWindowQuickTileBottom",
            "top-left":     "slotWindowQuickTileTopLeft",
            "top-right":    "slotWindowQuickTileTopRight",
            "bottom-left":  "slotWindowQuickTileBottomLeft",
            "bottom-right": "slotWindowQuickTileBottomRight",
        }
        slot = slot_map.get(position.lower())
        if not slot:
            raise RuntimeError(
                f"tile: unknown position {position!r}. "
                f"Valid values: {', '.join(slot_map)}"
            )

        self._run_window_op(uuid, "tile", f"""
    // Tile slot methods operate on the active window
    workspace.activeWindow = __w;
    var pause = Date.now(); while(Date.now()-pause < 100) {{}}

    workspace["{slot}"]();

    // Wait for KWin to commit the tile geometry before the next operation.
    // We intentionally do not read back geometry here -- the read-back is
    // unreliable within the same script execution (see kwin_tile_test.md).
    var pause2 = Date.now(); while(Date.now()-pause2 < 600) {{}}

    send({{ ok: true, op: "tile", slot: "{slot}" }});
""")
