#!/usr/bin/env python3
# =============================================================================
# kwin_lib_test.py  —  Integration test / sanity check for kwin_lib
# Generated by: Claude Sonnet 4.6
#
# Tests the library against your live KWin session without launching any apps.
# Verifies: KWinSession opens cleanly, desktop/screen enumeration, window
# query by resourceClass, and the WindowManager API against an existing window.
#
# USAGE:
#   python3 kwin_lib_test.py
#   python3 kwin_lib_test.py --mutate   # also test move/maximize operations
#   python3 kwin_lib_test.py --class thunderbird-esr --mutate
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



import argparse
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "wayland"))

from kwin_lib import KWinSession, WindowInfo


class C:
    _t = sys.stdout.isatty()
    BOLD="\033[1m" if _t else ""; CYAN="\033[36m" if _t else ""
    GREEN="\033[32m" if _t else ""; YELLOW="\033[33m" if _t else ""
    RED="\033[31m" if _t else ""; RESET="\033[0m" if _t else ""

def ok(m):   print(f"{C.GREEN}  ✓ {C.RESET}{m}")
def fail(m): print(f"{C.RED}  ✗ {C.RESET}{m}")
def info(m): print(f"{C.CYAN}    {m}{C.RESET}")
def head(m): print(f"\n{C.BOLD}{C.CYAN}{m}{C.RESET}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mutate", action="store_true",
        help="Run mutation tests (maximize/minimize/restore) on found window")
    parser.add_argument("--class", dest="rc", default="thunderbird-esr",
        help="resourceClass to test window operations on (default: thunderbird-esr)")
    args = parser.parse_args()

    head("═══ kwin_lib integration test ═══════════════════════════════════")

    with KWinSession() as kwin:

        # ── Test 1: Session opens ─────────────────────────────────────────
        head("Test 1 — KWinSession opens cleanly")
        ok("KWinSession connected to KWin D-Bus")
        ok(f"DesktopManager: {kwin.desktops}")
        ok(f"WindowManager : {kwin.windows}")
        ok(f"WindowProbe   : {kwin.probe}")

        # ── Test 2: Desktop enumeration ───────────────────────────────────
        head("Test 2 — Virtual desktop enumeration")
        desktops = kwin.desktops.list_desktops()
        ok(f"{len(desktops)} desktops found")
        for d in desktops:
            info(f"  {d.number:>2}. {d.name:<20}  {d.id}")

        current_id = kwin.desktops.current_desktop_id()
        current    = next((d for d in desktops if d.id == current_id), None)
        ok(f"Current desktop: {current.name!r}" if current else
           f"Current desktop ID: {current_id}")

        # Test lookup
        d = kwin.desktops.find_desktop(name=desktops[0].name)
        ok(f"find_desktop(name={desktops[0].name!r}) → {d}")
        d = kwin.desktops.find_desktop(number=1)
        ok(f"find_desktop(number=1) → {d}")

        # ── Test 3: Screen enumeration ────────────────────────────────────
        head("Test 3 — Screen enumeration")
        screens = kwin.desktops.list_screens()
        ok(f"{len(screens)} screens found")
        for s in screens:
            info(f"  {s.name:<14}  {s.x},{s.y}  {s.width}x{s.height}"
                 f"  {s.manufacturer} {s.model}")

        # ── Test 4: Find windows by resourceClass ─────────────────────────
        head(f"Test 4 — find_by_class({args.rc!r})")
        wins = kwin.windows.find_by_class(args.rc)
        if not wins:
            fail(f"No windows found with resourceClass={args.rc!r}")
            info("Pass --class <resourceClass> to test a different app")
        else:
            ok(f"{len(wins)} window(s) found")
            for w in wins:
                info(f"  {w.internalId}")
                info(f"    caption  : {w.caption!r}")
                info(f"    desktop  : {w.desktop_name!r}")
                info(f"    screen   : {w.screen_name!r}")
                info(f"    geometry : {w.x},{w.y}  {w.width}x{w.height}")
                info(f"    maximized: {w.maximized}  minimized: {w.minimized}")

            # ── Test 5: get_info ──────────────────────────────────────────
            head("Test 5 — get_info() via D-Bus getWindowInfo")
            uuid = wins[0].internalId
            try:
                info2 = kwin.windows.get_info(uuid)
                ok(f"get_info({uuid[:20]}…) returned WindowInfo")
                info(f"  caption: {info2.caption!r}")
            except Exception as exc:
                fail(f"get_info failed: {exc}")

            # ── Test 6: Mutation tests (--mutate only) ────────────────────
            if args.mutate:
                head("Test 6 — Mutation tests (--mutate)")
                w    = wins[0]
                uuid = w.internalId
                info(f"Target: {uuid}")
                info(f"  Current state: maximized={w.maximized}, "
                     f"minimized={w.minimized}")

                try:
                    # Unmaximize
                    kwin.windows.unmaximize(uuid)
                    ok("unmaximize()")

                    # Maximize
                    kwin.windows.maximize(uuid)
                    ok("maximize()")

                    # Minimize
                    kwin.windows.minimize(uuid)
                    ok("minimize()")

                    # Restore
                    kwin.windows.restore(uuid)
                    ok("restore()")

                    # Raise
                    kwin.windows.raise_window(uuid)
                    ok("raise_window()")

                    # Move to first different desktop
                    other = next(
                        (d for d in desktops if d.id != w.desktop_id),
                        None
                    )
                    if other:
                        kwin.windows.move_to_desktop(uuid, other)
                        ok(f"move_to_desktop({other.name!r})")
                        # Restore original desktop
                        orig = kwin.desktops.find_desktop(id=w.desktop_id)
                        if orig:
                            kwin.windows.move_to_desktop(uuid, orig)
                            ok(f"  Restored to {orig.name!r}")

                    # place() compound operation
                    target_d = kwin.desktops.find_desktop(id=w.desktop_id)
                    target_s = kwin.desktops.find_screen(name=w.screen_name)
                    if target_d and target_s:
                        kwin.windows.place(uuid,
                                           desktop=target_d,
                                           screen=target_s,
                                           maximize=True)
                        ok(f"place(desktop={target_d.name!r}, "
                           f"screen={target_s.name!r}, maximize=True)")

                except RuntimeError as exc:
                    fail(f"Mutation failed: {exc}")
            else:
                info("(pass --mutate to test move/maximize operations)")

    head("═══ Done ════════════════════════════════════════════════════════")


if __name__ == "__main__":
    main()
