#!/usr/bin/env python3
# =============================================================================
# kwin_geometry_screen_test.py
# Generated by: Claude Sonnet 4.6
#
# PURPOSE:
#   Targeted fix test for the two issues found in kwin_mutation_test.py:
#
#   Issue 1 — Qt.rect() not available:
#     Tests alternative ways to set window geometry without Qt.rect():
#       a) Plain JS object:  w.frameGeometry = {x, y, width, height}
#       b) w.geometry assignment (older property name)
#       c) Individual property setters: w.x = ..., w.width = ...
#
#   Issue 2 — w.sendToOutput() doesn't exist:
#     Tests alternative ways to assign a window to a screen:
#       a) Direct property assignment: w.output = screenObject
#       b) Geometry-based: move window into screen's coordinate space
#          (KWin associates a window with the screen its centre point is on)
#
# USAGE:
#   python3 kwin_geometry_screen_test.py --id "{uuid}" --screen "DP-4"
#
#   --id      internalId of window to test on (from kwin_window_probe.py)
#   --screen  Name of a DIFFERENT screen to test moving to (e.g. DP-4)
#             Must differ from the window's current screen.
#             Defaults to the first screen that isn't the window's current one.
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import threading
import time

from pydbus import SessionBus
from gi.repository import GLib


KWIN_SERVICE     = "org.kde.KWin"
SCRIPTING_PATH   = "/Scripting"
RECEIVER_SERVICE = "org.probe.KWinGeoTest"
RECEIVER_PATH    = "/Receiver"
RECEIVER_IFACE   = "org.probe.KWinGeoTest"


class C:
    _t     = sys.stdout.isatty()
    BOLD   = "\033[1m"  if _t else ""
    CYAN   = "\033[36m" if _t else ""
    GREEN  = "\033[32m" if _t else ""
    YELLOW = "\033[33m" if _t else ""
    RED    = "\033[31m" if _t else ""
    RESET  = "\033[0m"  if _t else ""

def info(m):  print(f"{C.CYAN}[INFO ] {C.RESET}{m}")
def ok(m):    print(f"{C.GREEN}[OK   ] {C.RESET}{m}")
def warn(m):  print(f"{C.YELLOW}[WARN ] {C.RESET}{m}")
def error(m): print(f"{C.RED}[ERROR] {C.RESET}{m}", file=sys.stderr)
def head(m):  print(f"\n{C.BOLD}{C.CYAN}{m}{C.RESET}")
def result_line(label, value, good=True):
    colour = C.GREEN if good else C.RED
    marker = "✓" if good else "✗"
    print(f"  {colour}{marker}{C.RESET}  {label:<40} {value!r}")


# ── D-Bus receiver ────────────────────────────────────────────────────────────

RECEIVER_XML = f"""
<node>
  <interface name='{RECEIVER_IFACE}'>
    <method name='receiveResult'>
      <arg type='s' name='test_name' direction='in'/>
      <arg type='s' name='json_data' direction='in'/>
    </method>
  </interface>
</node>
"""


class Receiver:
    dbus = RECEIVER_XML

    def __init__(self):
        self._results: dict[str, object] = {}
        self._events:  dict[str, threading.Event] = {}
        self._lock = threading.Lock()

    def expect(self, name: str) -> threading.Event:
        ev = threading.Event()
        with self._lock:
            self._events[name] = ev
        return ev

    def receiveResult(self, test_name: str, json_data: str) -> None:
        try:    data = json.loads(json_data)
        except: data = {"parseError": json_data[:300]}
        with self._lock:
            self._results[test_name] = data
            ev = self._events.get(test_name)
        if ev: ev.set()

    def get(self, name: str) -> object:
        with self._lock:
            return self._results.get(name)


class ScriptRunner:
    def __init__(self, scripting, receiver: Receiver):
        self.scripting = scripting
        self.receiver  = receiver

    def run(self, name: str, js_body: str, timeout: float = 6.0) -> dict:
        js = f"""
var _svc="{RECEIVER_SERVICE}",_path="{RECEIVER_PATH}",_iface="{RECEIVER_IFACE}",_name="{name}";
function send(d){{callDBus(_svc,_path,_iface,"receiveResult",_name,JSON.stringify(d));}}
try{{ {js_body} }}catch(e){{send({{fatalError:String(e)}});}}
"""
        js_fd, js_path = tempfile.mkstemp(suffix=".js", prefix=f"kwin_geo_{name}_")
        os.close(js_fd)
        ev = self.receiver.expect(name)
        script_id = None
        try:
            with open(js_path, "w") as f: f.write(js)
            script_id = self.scripting.loadScript(js_path)
            self.scripting.start()
        except Exception as exc:
            os.unlink(js_path)
            return {"loadError": str(exc)}
        ev.wait(timeout=timeout)
        try:
            if script_id is not None: self.scripting.unloadScript(str(script_id))
        except: pass
        try: os.unlink(js_path)
        except: pass
        result = self.receiver.get(name)
        return result if result is not None else {"timeout": True}


# ── Tests ─────────────────────────────────────────────────────────────────────

def test_geometry_setters(runner: ScriptRunner, window_id: str) -> dict:
    """
    Test which method of setting frameGeometry actually works without Qt.rect().
    Each approach is tried in sequence.  After each attempt we read back the
    geometry to verify it was actually applied.
    """
    head("Test 1 — Geometry setter alternatives (no Qt.rect)")
    bare = window_id.strip("{}")

    result = runner.run("geo_setters", f"""
var targetId = "{bare}";
var wins = workspace.windowList();
var w = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === targetId) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{ send({{error: "window not found"}}); }}

// Capture original geometry for restoration
var origX = Number(w.frameGeometry.x);
var origY = Number(w.frameGeometry.y);
var origW = Number(w.frameGeometry.width);
var origH = Number(w.frameGeometry.height);

// Un-maximize first so geometry changes are visible
var wasMax = Boolean(w.maximized);
if (wasMax) w.setMaximize(false, false);

var results = {{}};

// ── Approach A: plain JS object ────────────────────────────────────────────
try {{
    w.frameGeometry = {{ x: origX, y: origY, width: 820, height: 620 }};
    var g = w.frameGeometry;
    results.plainObject = {{
        attempted: true,
        width:  Number(g.width),
        height: Number(g.height),
        worked: Number(g.width) === 820 && Number(g.height) === 620,
    }};
}} catch(e) {{
    results.plainObject = {{ attempted: true, error: String(e) }};
}}

// ── Approach B: w.geometry (alternative property name) ────────────────────
try {{
    w.geometry = {{ x: origX, y: origY, width: 840, height: 640 }};
    var g2 = w.frameGeometry;
    results.geometryProp = {{
        attempted: true,
        width:  Number(g2.width),
        height: Number(g2.height),
        worked: Number(g2.width) === 840 && Number(g2.height) === 640,
    }};
}} catch(e) {{
    results.geometryProp = {{ attempted: true, error: String(e) }};
}}

// ── Approach C: QRect-like object with constructor ────────────────────────
try {{
    var rect = Object.create(null);
    rect.x = origX; rect.y = origY; rect.width = 860; rect.height = 660;
    w.frameGeometry = rect;
    var g3 = w.frameGeometry;
    results.objectCreate = {{
        attempted: true,
        width:  Number(g3.width),
        height: Number(g3.height),
        worked: Number(g3.width) === 860 && Number(g3.height) === 660,
    }};
}} catch(e) {{
    results.objectCreate = {{ attempted: true, error: String(e) }};
}}

// ── Restore ────────────────────────────────────────────────────────────────
try {{
    w.frameGeometry = {{ x: origX, y: origY, width: origW, height: origH }};
    if (wasMax) w.setMaximize(true, true);
    results.restored = true;
}} catch(e) {{
    results.restoreError = String(e);
}}

send({{ original: {{x:origX,y:origY,w:origW,h:origH}}, results: results }});
""", timeout=8.0)

    if "fatalError" in result:
        error(f"Fatal: {result['fatalError']}")
        return result

    orig    = result.get("original", {})
    results = result.get("results", {})

    info(f"Original geometry: {orig.get('x')},{orig.get('y')}  "
         f"{orig.get('w')}x{orig.get('h')}")
    print()

    best = None
    for approach, label in [
        ("plainObject",  "Plain JS object  { x, y, width, height }"),
        ("geometryProp", "w.geometry = { x, y, width, height }"),
        ("objectCreate", "Object.create(null) with properties"),
    ]:
        r = results.get(approach, {})
        if "error" in r:
            result_line(label, f"ERROR: {r['error']}", good=False)
        elif r.get("worked"):
            result_line(label, f"WORKS  (read back {r['width']}x{r['height']})", good=True)
            if best is None: best = approach
        elif "timeout" in result:
            result_line(label, "TIMEOUT", good=False)
        else:
            result_line(label,
                f"SILENT FAIL — set but read back {r.get('width')}x{r.get('height')}",
                good=False)

    restored = results.get("restored", False)
    print()
    if restored:
        ok(f"Original geometry restored: "
           f"{orig.get('x')},{orig.get('y')}  {orig.get('w')}x{orig.get('h')}")
    else:
        warn(f"Restore failed: {results.get('restoreError', '?')}")

    if best:
        print()
        ok(f"Best approach for library: '{best}'")
    else:
        warn("No geometry setter approach worked — library will need workaround")

    return {"best_approach": best, "results": results}


def test_screen_assignment(runner: ScriptRunner, window_id: str,
                            target_screen: str) -> dict:
    """
    Test which method of assigning a window to a specific screen works.
    Tries:
      a) w.output = screenObject  (direct property assignment)
      b) Geometry-based: move window centre into target screen's rect
    Reads back w.output.name after each attempt to verify.
    """
    head(f"Test 2 — Screen assignment  (target: '{target_screen}')")
    bare = window_id.strip("{}")

    result = runner.run("screen_assign", f"""
var targetId     = "{bare}";
var targetScreen = "{target_screen}";
var wins = workspace.windowList();
var w = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === targetId) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{ send({{error: "window not found"}}); }}

var origOutput = String(w.output ? (w.output.name || "") : "");
var origGeo    = {{ x: Number(w.frameGeometry.x),   y: Number(w.frameGeometry.y),
                    width: Number(w.frameGeometry.width),
                    height: Number(w.frameGeometry.height) }};
var wasMax     = Boolean(w.maximized);
if (wasMax) w.setMaximize(false, false);

// Find the target screen object from workspace.screens
var targetScr = null;
var targetGeo = null;
var screens   = workspace.screens;
for (var i = 0; i < screens.length; i++) {{
    if (String(screens[i].name || "") === targetScreen) {{
        targetScr = screens[i];
        targetGeo = screens[i].geometry;
        break;
    }}
}}

var results = {{ origOutput: origOutput }};

if (!targetScr) {{
    send({{ error: "target screen '" + targetScreen + "' not found",
            availableScreens: (function(){{
                var ns=[];
                for(var i=0;i<screens.length;i++) ns.push(String(screens[i].name||""));
                return ns;
            }})()
         }});
}}

// ── Approach A: direct output property assignment ─────────────────────────
try {{
    w.output = targetScr;
    var readBack = String(w.output ? (w.output.name || "") : "");
    results.directAssign = {{
        attempted: true,
        readBack:  readBack,
        worked:    readBack === targetScreen,
    }};
}} catch(e) {{
    results.directAssign = {{ attempted: true, error: String(e) }};
}}

// Read back after brief pause
var t = Date.now(); while(Date.now()-t < 300) {{}}
results.directAssignAfterPause = String(w.output ? (w.output.name||"") : "");

// ── Restore to original screen before trying approach B ──────────────────
try {{
    w.frameGeometry = origGeo;
}} catch(e) {{}}

// ── Approach B: move window centre-point into target screen geometry ──────
// KWin associates a window with whichever screen contains its centre point.
try {{
    var cx = Number(targetGeo.x) + Math.floor(Number(targetGeo.width)  / 2);
    var cy = Number(targetGeo.y) + Math.floor(Number(targetGeo.height) / 2);
    // Place window so its centre is at (cx, cy)
    var newX = cx - Math.floor(origGeo.width  / 2);
    var newY = cy - Math.floor(origGeo.height / 2);
    w.frameGeometry = {{ x: newX, y: newY,
                          width: origGeo.width, height: origGeo.height }};
    var t2 = Date.now(); while(Date.now()-t2 < 300) {{}}
    var readBack2 = String(w.output ? (w.output.name || "") : "");
    results.geometryBased = {{
        attempted: true,
        movedTo:   {{ x: newX, y: newY }},
        readBack:  readBack2,
        worked:    readBack2 === targetScreen,
    }};
}} catch(e) {{
    results.geometryBased = {{ attempted: true, error: String(e) }};
}}

// ── Restore to original screen and position ───────────────────────────────
try {{
    w.frameGeometry = origGeo;
    if (wasMax) w.setMaximize(true, true);
    results.restored = true;
}} catch(e) {{
    results.restoreError = String(e);
}}

send({{ results: results, targetGeo: {{
    x: Number(targetGeo.x), y: Number(targetGeo.y),
    width: Number(targetGeo.width), height: Number(targetGeo.height)
}} }});
""", timeout=8.0)

    if "fatalError" in result:
        error(f"Fatal: {result['fatalError']}")
        return result
    if "error" in result:
        warn(f"Screen not found: {result['error']}")
        info(f"Available: {result.get('availableScreens', [])}")
        return result

    res = result.get("results", {})
    tg  = result.get("targetGeo", {})

    info(f"Original screen : {res.get('origOutput')!r}")
    info(f"Target screen   : {target_screen!r}  "
         f"({tg.get('x')},{tg.get('y')}  {tg.get('width')}x{tg.get('height')})")
    print()

    best = None
    for approach, label in [
        ("directAssign",   "Direct: w.output = screenObject"),
        ("geometryBased",  "Geometry: move centre-point into screen rect"),
    ]:
        r = res.get(approach, {})
        if "error" in r:
            result_line(label, f"ERROR: {r['error']}", good=False)
        elif r.get("worked"):
            result_line(label, f"WORKS  (read back {r['readBack']!r})", good=True)
            if best is None: best = approach
        else:
            result_line(label,
                f"SILENT FAIL — read back {r.get('readBack')!r}", good=False)

    # Show the post-pause read for direct assign (sometimes async)
    pause_val = res.get("directAssignAfterPause", "?")
    info(f"  directAssign after 300ms pause: {pause_val!r}")

    print()
    restored = res.get("restored", False)
    if restored:
        ok("Original position restored")
    else:
        warn(f"Restore failed: {res.get('restoreError', '?')}")

    if best:
        print()
        ok(f"Best approach for library: '{best}'")
    else:
        warn("No screen assignment approach worked")
        info("Library will need to use geometry-based positioning instead,")
        info("relying on the caller to provide absolute coordinates.")

    return {"best_approach": best, "results": res}


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="kwin_geometry_screen_test.py",
        description="Targeted test for Qt.rect alternative and screen assignment.",
    )
    parser.add_argument("--id", dest="window_id", required=True, metavar="UUID",
        help="internalId of window to test (from kwin_window_probe.py)")
    parser.add_argument("--screen", dest="target_screen", default="", metavar="NAME",
        help="Screen name to test moving to (e.g. DP-4). "
             "Must differ from window's current screen.")
    args = parser.parse_args()

    head("═══ KWin Geometry & Screen Assignment Test ═════════════════════")
    info(f"Window ID     : {args.window_id}")
    info(f"Target screen : {args.target_screen or '(will pick automatically)'}")

    bus      = SessionBus()
    receiver = Receiver()

    try:
        reg = bus.publish(RECEIVER_SERVICE, (RECEIVER_PATH, receiver))
    except Exception as exc:
        error(f"Cannot publish receiver: {exc}")
        sys.exit(1)

    loop = GLib.MainLoop()
    threading.Thread(target=loop.run, daemon=True).start()

    scripting = bus.get(KWIN_SERVICE, SCRIPTING_PATH)
    runner    = ScriptRunner(scripting, receiver)

    try:
        # Test 1: geometry setters
        geo_result = test_geometry_setters(runner, args.window_id)

        # Test 2: screen assignment
        # If no --screen given, pick the first screen not matching current output
        target_screen = args.target_screen
        if not target_screen:
            # Quick script to find current output and pick a different one
            r = runner.run("find_other_screen", f"""
var targetId = "{args.window_id.strip('{}')}";
var wins = workspace.windowList();
var currentOutput = "";
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === targetId) {{
        currentOutput = String(wins[i].output ? wins[i].output.name || "" : "");
        break;
    }}
}}
var screens = workspace.screens;
var other = "";
for (var i = 0; i < screens.length; i++) {{
    if (String(screens[i].name||"") !== currentOutput) {{
        other = String(screens[i].name||"");
        break;
    }}
}}
send({{ currentOutput: currentOutput, otherScreen: other }});
""")
            current = r.get("currentOutput", "")
            target_screen = r.get("otherScreen", "")
            info(f"Window is on   : {current!r}")
            info(f"Auto-selected  : {target_screen!r}")

        if target_screen:
            screen_result = test_screen_assignment(
                runner, args.window_id, target_screen)
        else:
            warn("Could not determine a target screen — skipping Test 2")

    finally:
        loop.quit()
        try: reg.unpublish()
        except: pass

    head("═══ Done ════════════════════════════════════════════════════════")


if __name__ == "__main__":
    main()
