#!/usr/bin/env python3
# =============================================================================
# kwin_desktop_assign_test.py
# Generated by: Claude Sonnet 4.6
#
# PURPOSE:
#   Tests virtual desktop assignment and window focus/raise operations —
#   the two remaining untested operations before writing the library.
#
#   Tests:
#     1. Move window to a different virtual desktop via w.desktops = [obj]
#     2. Raise/focus a window via workspace.activeWindow = w
#     3. Minimize/restore via w.minimized
#
#   All tests restore original state afterwards.
#
# USAGE:
#   python3 kwin_desktop_assign_test.py --id "{uuid}"
#
#   --id       internalId of window to test (from kwin_window_probe.py)
#   --desktop  Name of desktop to test moving to (default: auto-picks
#              a desktop different from the window's current one)
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import threading

from pydbus import SessionBus
from gi.repository import GLib

KWIN_SERVICE     = "org.kde.KWin"
SCRIPTING_PATH   = "/Scripting"
VDM_PATH         = "/VirtualDesktopManager"
RECEIVER_SERVICE = "org.probe.KWinDesktopTest"
RECEIVER_PATH    = "/Receiver"
RECEIVER_IFACE   = "org.probe.KWinDesktopTest"


class C:
    _t     = sys.stdout.isatty()
    BOLD   = "\033[1m"  if _t else ""
    CYAN   = "\033[36m" if _t else ""
    GREEN  = "\033[32m" if _t else ""
    YELLOW = "\033[33m" if _t else ""
    RED    = "\033[31m" if _t else ""
    RESET  = "\033[0m"  if _t else ""

def info(m):  print(f"{C.CYAN}[INFO ] {C.RESET}{m}")
def ok(m):    print(f"{C.GREEN}[OK   ] {C.RESET}{m}")
def warn(m):  print(f"{C.YELLOW}[WARN ] {C.RESET}{m}")
def error(m): print(f"{C.RED}[ERROR] {C.RESET}{m}", file=sys.stderr)
def head(m):  print(f"\n{C.BOLD}{C.CYAN}{m}{C.RESET}")
def rline(label, value, good=True):
    c = C.GREEN if good else C.RED
    m = "✓" if good else "✗"
    print(f"  {c}{m}{C.RESET}  {label:<44} {value!r}")


RECEIVER_XML = f"""
<node>
  <interface name='{RECEIVER_IFACE}'>
    <method name='receiveResult'>
      <arg type='s' name='test_name' direction='in'/>
      <arg type='s' name='json_data' direction='in'/>
    </method>
  </interface>
</node>
"""


class Receiver:
    dbus = RECEIVER_XML
    def __init__(self):
        self._results: dict = {}
        self._events:  dict = {}
        self._lock = threading.Lock()
    def expect(self, name):
        ev = threading.Event()
        with self._lock: self._events[name] = ev
        return ev
    def receiveResult(self, test_name, json_data):
        try:    data = json.loads(json_data)
        except: data = {"parseError": json_data[:300]}
        with self._lock:
            self._results[test_name] = data
            ev = self._events.get(test_name)
        if ev: ev.set()
    def get(self, name):
        with self._lock: return self._results.get(name)


class ScriptRunner:
    def __init__(self, scripting, receiver):
        self.scripting = scripting
        self.receiver  = receiver

    def run(self, name, js_body, timeout=8.0):
        js = f"""
var _s="{RECEIVER_SERVICE}",_p="{RECEIVER_PATH}",_i="{RECEIVER_IFACE}",_n="{name}";
function send(d){{callDBus(_s,_p,_i,"receiveResult",_n,JSON.stringify(d));}}
try{{ {js_body} }}catch(e){{send({{fatalError:String(e)}});}}
"""
        fd, path = tempfile.mkstemp(suffix=".js", prefix=f"kwin_dt_{name}_")
        os.close(fd)
        ev = self.receiver.expect(name)
        sid = None
        try:
            with open(path, "w") as f: f.write(js)
            sid = self.scripting.loadScript(path)
            self.scripting.start()
        except Exception as exc:
            os.unlink(path)
            return {"loadError": str(exc)}
        ev.wait(timeout=timeout)
        try:
            if sid is not None: self.scripting.unloadScript(str(sid))
        except: pass
        try: os.unlink(path)
        except: pass
        r = self.receiver.get(name)
        return r if r is not None else {"timeout": True}


# ── Tests ─────────────────────────────────────────────────────────────────────

def test_desktop_assignment(runner: ScriptRunner, bus,
                             window_id: str, target_desktop_name: str) -> dict:
    head("Test 1 — Virtual desktop assignment")
    bare = window_id.strip("{}")

    # Get desktop list from VirtualDesktopManager for reliable UUID lookup
    vdm      = bus.get(KWIN_SERVICE, VDM_PATH)
    vdm_list = list(vdm.desktops)   # list of (x11number, uuid, name)

    info(f"Available desktops:")
    desktop_map = {}   # name → uuid
    for item in vdm_list:
        num, uid, name = int(item[0]), str(item[1]), str(item[2])
        desktop_map[name] = uid
        info(f"  {num:>2}. {name:<20}  {uid}")

    # Auto-pick target if not specified
    if not target_desktop_name:
        # Find current desktop of window, pick a different one
        r = runner.run("find_current_desktop", f"""
var targetId = "{bare}";
var wins = workspace.windowList();
for (var i = 0; i < wins.length; i++) {{
    var w = wins[i];
    if (String(w.internalId).replace(/[{{}}]/g,"") === targetId) {{
        var ds = w.desktops;
        send({{
            currentDesktopId:   ds && ds.length > 0 ? String(ds[0].id||"")   : "",
            currentDesktopName: ds && ds.length > 0 ? String(ds[0].name||"") : "",
        }});
        break;
    }}
}}
""")
        current_name = r.get("currentDesktopName", "")
        info(f"Window is on desktop: {current_name!r}")
        # Pick first desktop that isn't current
        for item in vdm_list:
            if str(item[2]) != current_name:
                target_desktop_name = str(item[2])
                break

    if not target_desktop_name or target_desktop_name not in desktop_map:
        warn(f"Target desktop {target_desktop_name!r} not found")
        return {}

    target_uuid = desktop_map[target_desktop_name]
    info(f"Target desktop: {target_desktop_name!r}  ({target_uuid})\n")

    result = runner.run("desktop_assign", f"""
var targetId      = "{bare}";
var targetDeskId  = "{target_uuid}";
var wins          = workspace.windowList();
var w             = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === targetId) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{ send({{error: "window not found"}}); }}

// Capture original desktop
var origDesktopId   = "";
var origDesktopName = "";
try {{
    var ods = w.desktops;
    if (ods && ods.length > 0) {{
        origDesktopId   = String(ods[0].id   || "");
        origDesktopName = String(ods[0].name || "");
    }}
}} catch(e) {{}}

var results = {{ origDesktopId: origDesktopId, origDesktopName: origDesktopName }};

// ── Approach A: find target desktop object and assign array ───────────────
try {{
    var allDesks    = workspace.desktops;
    var targetDesk  = null;
    for (var i = 0; i < allDesks.length; i++) {{
        if (String(allDesks[i].id||"") === targetDeskId) {{
            targetDesk = allDesks[i];
            break;
        }}
    }}

    if (!targetDesk) {{
        results.approachA = {{ error: "target desktop object not found in workspace.desktops" }};
    }} else {{
        // Assign: w.desktops takes an array of desktop objects
        w.desktops = [targetDesk];

        // Brief pause then read back
        var t = Date.now(); while(Date.now()-t < 300) {{}}
        var newDs   = w.desktops;
        var newId   = newDs && newDs.length > 0 ? String(newDs[0].id   || "") : "";
        var newName = newDs && newDs.length > 0 ? String(newDs[0].name || "") : "";
        results.approachA = {{
            attempted:  true,
            readBackId: newId,
            readBackName: newName,
            worked:     newId === targetDeskId,
        }};
    }}
}} catch(e) {{
    results.approachA = {{ attempted: true, error: String(e) }};
}}

// ── Restore to original desktop ───────────────────────────────────────────
try {{
    var allDesks2  = workspace.desktops;
    var origDesk   = null;
    for (var i = 0; i < allDesks2.length; i++) {{
        if (String(allDesks2[i].id||"") === origDesktopId) {{
            origDesk = allDesks2[i]; break;
        }}
    }}
    if (origDesk) {{
        w.desktops = [origDesk];
        results.restored = true;
    }} else {{
        results.restoreError = "original desktop object not found";
    }}
}} catch(e) {{
    results.restoreError = String(e);
}}

send(results);
""")

    if "fatalError" in result:
        error(f"Fatal: {result['fatalError']}")
        return result
    if "error" in result:
        warn(f"Error: {result['error']}")
        return result

    orig = f"{result.get('origDesktopName')!r} ({result.get('origDesktopId','')})"
    info(f"Original desktop : {orig}")

    a = result.get("approachA", {})
    if "error" in a:
        rline("w.desktops = [desktopObject]", f"ERROR: {a['error']}", good=False)
    elif a.get("worked"):
        rline("w.desktops = [desktopObject]",
              f"WORKS → landed on {a.get('readBackName')!r}", good=True)
    else:
        rline("w.desktops = [desktopObject]",
              f"SILENT FAIL → read back {a.get('readBackName')!r}", good=False)

    if result.get("restored"):
        ok(f"Restored to original desktop: {result.get('origDesktopName')!r}")
    else:
        warn(f"Restore failed: {result.get('restoreError', '?')}")

    return result


def test_focus_and_minimize(runner: ScriptRunner, window_id: str) -> dict:
    head("Test 2 — Focus / raise and minimize / restore")
    bare = window_id.strip("{}")

    result = runner.run("focus_minimize", f"""
var targetId = "{bare}";
var wins     = workspace.windowList();
var w        = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === targetId) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{ send({{error: "window not found"}}); }}

var origMinimized = Boolean(w.minimized);
var results       = {{ origMinimized: origMinimized }};

// ── Focus / raise ─────────────────────────────────────────────────────────
try {{
    workspace.activeWindow = w;
    var t = Date.now(); while(Date.now()-t < 200) {{}}
    var isActive = (workspace.activeWindow === w ||
                    String(workspace.activeWindow
                           ? workspace.activeWindow.internalId : "")
                    === String(w.internalId));
    results.focusRaise = {{ attempted: true, isActive: isActive }};
}} catch(e) {{
    results.focusRaise = {{ attempted: true, error: String(e) }};
}}

// ── Minimize ──────────────────────────────────────────────────────────────
try {{
    w.minimized = true;
    var t2 = Date.now(); while(Date.now()-t2 < 300) {{}}
    results.minimize = {{
        attempted:  true,
        readBack:   Boolean(w.minimized),
        worked:     Boolean(w.minimized) === true,
    }};
}} catch(e) {{
    results.minimize = {{ attempted: true, error: String(e) }};
}}

// ── Restore (un-minimize) ─────────────────────────────────────────────────
try {{
    w.minimized = false;
    var t3 = Date.now(); while(Date.now()-t3 < 300) {{}}
    results.unminimize = {{
        attempted: true,
        readBack:  Boolean(w.minimized),
        worked:    Boolean(w.minimized) === false,
    }};
}} catch(e) {{
    results.unminimize = {{ attempted: true, error: String(e) }};
}}

// Raise again after restore
try {{
    workspace.activeWindow = w;
}} catch(e) {{}}

send(results);
""")

    if "fatalError" in result:
        error(f"Fatal: {result['fatalError']}")
        return result
    if "error" in result:
        warn(f"Error: {result['error']}")
        return result

    fr = result.get("focusRaise", {})
    if "error" in fr:
        rline("workspace.activeWindow = w  (raise/focus)",
              f"ERROR: {fr['error']}", good=False)
    else:
        rline("workspace.activeWindow = w  (raise/focus)",
              f"isActive={fr.get('isActive')}", good=bool(fr.get("isActive")))

    mn = result.get("minimize", {})
    if "error" in mn:
        rline("w.minimized = true", f"ERROR: {mn['error']}", good=False)
    else:
        rline("w.minimized = true",
              f"readBack={mn.get('readBack')}", good=bool(mn.get("worked")))

    um = result.get("unminimize", {})
    if "error" in um:
        rline("w.minimized = false  (restore)", f"ERROR: {um['error']}", good=False)
    else:
        rline("w.minimized = false  (restore)",
              f"readBack={um.get('readBack')}", good=bool(um.get("worked")))

    return result


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="kwin_desktop_assign_test.py",
        description="Test virtual desktop assignment, focus, and minimize.",
    )
    parser.add_argument("--id", dest="window_id", required=True, metavar="UUID")
    parser.add_argument("--desktop", dest="target_desktop", default="",
        metavar="NAME",
        help="Desktop name to test moving to (default: auto-picks)")
    args = parser.parse_args()

    head("═══ KWin Desktop Assignment & Focus Test ═══════════════════════")
    info(f"Window ID : {args.window_id}")

    bus      = SessionBus()
    receiver = Receiver()

    try:
        reg = bus.publish(RECEIVER_SERVICE, (RECEIVER_PATH, receiver))
    except Exception as exc:
        error(f"Cannot publish receiver: {exc}"); sys.exit(1)

    loop = GLib.MainLoop()
    threading.Thread(target=loop.run, daemon=True).start()

    scripting = bus.get(KWIN_SERVICE, SCRIPTING_PATH)
    runner    = ScriptRunner(scripting, receiver)

    try:
        test_desktop_assignment(runner, bus, args.window_id, args.target_desktop)
        test_focus_and_minimize(runner, args.window_id)
    finally:
        loop.quit()
        try: reg.unpublish()
        except: pass

    head("═══ Done ════════════════════════════════════════════════════════")
    print()
    info("Summary of confirmed working operations for the library:")
    info("  • w.desktops = [desktopObj]     (move to virtual desktop)")
    info("  • workspace.activeWindow = w    (raise / focus)")
    info("  • w.minimized = true/false      (minimize / restore)")
    info("  • w.setMaximize(h, v)           (maximize / unmaximize)")
    info("  • w.frameGeometry = {x,y,w,h}  (move — x/y only, size ignored by app)")
    info("  • Geometry-based screen assign  (move centre-point into screen rect)")


if __name__ == "__main__":
    main()
