#!/usr/bin/env python3
# =============================================================================
# kwin_tile_test.py
# Generated by: Claude Sonnet 4.6
#
# PURPOSE:
#   Confirms which KWin scripting slot methods are available for window tiling
#   and verifies that they work as expected.
#
#   Tests:
#     A. Introspect workspace for slot methods matching 'QuickTile' or 'Tile'
#     B. Tile the target window left and record the resulting geometry
#     C. Tile the target window right and record the resulting geometry
#     D. Restore the window to its original geometry
#
#   The test is intentionally destructive (it moves and resizes the target
#   window) but restores the original state at the end.  Run it against a
#   window you don't mind briefly moving.
#
# USAGE:
#   # Step 1: get a live internalId from kwin_probe.py
#   python3 kwin_probe.py --class thunderbird-esr -- thunderbird
#
#   # Step 2: run tile test against that window
#   python3 docs/dev/kwin_tile_test.py --id <uuid-without-braces>
#
# REQUIREMENTS:
#   python313-pydbus   python313-gobject
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import threading
import time

from pydbus import SessionBus
from gi.repository import GLib


# ── Constants ─────────────────────────────────────────────────────────────────

KWIN_SERVICE     = "org.kde.KWin"
SCRIPTING_PATH   = "/Scripting"
RECEIVER_SERVICE = "org.probe.KWinTileTest"
RECEIVER_PATH    = "/Receiver"
RECEIVER_IFACE   = "org.probe.KWinTileTest"


# ── Colours ───────────────────────────────────────────────────────────────────

class C:
    _t     = sys.stdout.isatty()
    BOLD   = "\033[1m"  if _t else ""
    CYAN   = "\033[36m" if _t else ""
    GREEN  = "\033[32m" if _t else ""
    YELLOW = "\033[33m" if _t else ""
    RED    = "\033[31m" if _t else ""
    RESET  = "\033[0m"  if _t else ""

def info(m):  print(f"{C.CYAN}[INFO ] {C.RESET}{m}")
def ok(m):    print(f"{C.GREEN}[OK   ] {C.RESET}{m}")
def warn(m):  print(f"{C.YELLOW}[WARN ] {C.RESET}{m}")
def error(m): print(f"{C.RED}[ERROR] {C.RESET}{m}", file=sys.stderr)
def head(m):  print(f"\n{C.BOLD}{C.CYAN}{m}{C.RESET}")
def rline(label, value, good=True):
    mark = f"{C.GREEN}✓{C.RESET}" if good else f"{C.RED}✗{C.RESET}"
    print(f"  {mark}  {label:<45} {value}")


# ── D-Bus receiver ────────────────────────────────────────────────────────────

RECEIVER_XML = f"""
<node>
  <interface name='{RECEIVER_IFACE}'>
    <method name='receiveResult'>
      <arg type='s' name='test_name' direction='in'/>
      <arg type='s' name='json_data' direction='in'/>
    </method>
  </interface>
</node>
"""


class TileTestReceiver:
    dbus = RECEIVER_XML

    def __init__(self) -> None:
        self._results: dict[str, object] = {}
        self._events:  dict[str, threading.Event] = {}
        self._lock = threading.Lock()

    def expect(self, test_name: str) -> threading.Event:
        ev = threading.Event()
        with self._lock:
            self._events[test_name] = ev
        return ev

    def receiveResult(self, test_name: str, json_data: str) -> None:
        try:
            data = json.loads(json_data)
        except Exception as exc:
            data = {"parseError": str(exc), "raw": json_data[:200]}
        with self._lock:
            self._results[test_name] = data
            ev = self._events.get(test_name)
        if ev:
            ev.set()

    def get(self, test_name: str) -> object:
        with self._lock:
            return self._results.get(test_name)


# ── Script runner ─────────────────────────────────────────────────────────────

class ScriptRunner:
    def __init__(self, scripting, receiver: TileTestReceiver) -> None:
        self.scripting = scripting
        self.receiver  = receiver

    def run(self, test_name: str, js_body: str, timeout: float = 8.0) -> dict:
        svc   = RECEIVER_SERVICE
        path  = RECEIVER_PATH
        iface = RECEIVER_IFACE

        js = f"""
// KWin tile test — {test_name}
var _svc   = "{svc}";
var _path  = "{path}";
var _iface = "{iface}";
var _name  = "{test_name}";

function send(data) {{
    callDBus(_svc, _path, _iface, "receiveResult", _name,
             JSON.stringify(data));
}}

try {{
    {js_body}
}} catch(e) {{
    send({{ fatalError: String(e) }});
}}
"""
        js_fd, js_path = tempfile.mkstemp(
            suffix=".js", prefix=f"kwin_tile_{test_name}_"
        )
        os.close(js_fd)
        script_id = None
        ev = self.receiver.expect(test_name)

        try:
            with open(js_path, "w") as f:
                f.write(js)
            script_id = self.scripting.loadScript(js_path)
            self.scripting.start()
        except Exception as exc:
            os.unlink(js_path)
            return {"loadError": str(exc)}

        ev.wait(timeout=timeout)

        try:
            if script_id is not None:
                self.scripting.unloadScript(str(script_id))
        except Exception:
            pass
        try:
            os.unlink(js_path)
        except OSError:
            pass

        result = self.receiver.get(test_name)
        if result is None:
            return {"timeout": True, "test": test_name}
        return result


# ── Geometry helper ───────────────────────────────────────────────────────────

def geom_str(g: dict) -> str:
    if not g:
        return "(none)"
    return f"{g.get('x')},{g.get('y')}  {g.get('width')}x{g.get('height')}"


# ── Tests ─────────────────────────────────────────────────────────────────────

def test_introspect_slots(runner: ScriptRunner) -> list[str]:
    """
    Test A — introspect workspace for tiling slot methods.

    Iterates all properties of the workspace object and returns those whose
    names contain 'tile' or 'quicktile' (case-insensitive).  This tells us
    the exact names available in this KWin version without guessing.
    """
    head("Test A — Introspect workspace for tiling slot methods")

    result = runner.run("introspect_slots", """
var slots = [];
for (var key in workspace) {
    var kl = key.toLowerCase();
    if (kl.indexOf("tile") !== -1 || kl.indexOf("quicktile") !== -1) {
        slots.push({ name: key, type: typeof workspace[key] });
    }
}
// Also check a few specific names explicitly in case enumeration misses them
var candidates = [
    "slotWindowQuickTileLeft",
    "slotWindowQuickTileRight",
    "slotWindowQuickTileTop",
    "slotWindowQuickTileBottom",
    "slotWindowQuickTileTopLeft",
    "slotWindowQuickTileTopRight",
    "slotWindowQuickTileBottomLeft",
    "slotWindowQuickTileBottomRight",
];
var explicit = [];
for (var i = 0; i < candidates.length; i++) {
    explicit.push({
        name:   candidates[i],
        type:   typeof workspace[candidates[i]],
        exists: typeof workspace[candidates[i]] === "function",
    });
}
send({ slots: slots, explicit: explicit });
""")

    if "fatalError" in result:
        error(f"Test A failed: {result['fatalError']}")
        return []
    if "timeout" in result:
        error("Test A timed out")
        return []

    # Print enumerated slots (may be empty if workspace doesn't expose its keys)
    slots = result.get("slots", [])
    if slots:
        info(f"Enumerated {len(slots)} tile-related slot(s) on workspace:")
        for s in slots:
            info(f"  {s['name']}  (type: {s['type']})")
    else:
        info("No tile slots found via enumeration (workspace may not be enumerable)")

    # Print explicit probe results
    explicit = result.get("explicit", [])
    head("  Explicit slot name probe:")
    available = []
    for e in explicit:
        exists = e.get("exists", False)
        rline(e["name"], e["type"], good=exists)
        if exists:
            available.append(e["name"])

    if available:
        ok(f"\n  Available slot methods: {available}")
    else:
        warn("\n  No tiling slot methods found under the expected names.")
        warn("  Check KWin source or use kwin_introspect.py for alternate names.")

    return available


def test_tile_left(runner: ScriptRunner, target_id: str,
                   slot_name: str) -> dict:
    """
    Test B — tile the target window left using the confirmed slot method.

    Sets the window as activeWindow (required for slot methods), calls the
    slot, waits 500ms, and reads back geometry and screen name.
    """
    head(f"Test B — Tile left  (slot: {slot_name})")

    result = runner.run("tile_left", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === bare) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{
    send({{ error: "window not found", uuid: bare }});
}} else {{
    // Record geometry before tile
    var before = {{
        x: Number(w.frameGeometry.x),     y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        screen: String(w.output ? w.output.name : ""),
    }};

    // Slot methods operate on the active window
    workspace.activeWindow = w;
    var pause = Date.now(); while(Date.now()-pause < 100) {{}}

    // Call the tiling slot
    workspace["{slot_name}"]();
    var pause2 = Date.now(); while(Date.now()-pause2 < 500) {{}}

    // Read geometry after tile
    var after = {{
        x: Number(w.frameGeometry.x),     y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        screen: String(w.output ? w.output.name : ""),
    }};

    send({{ ok: true, before: before, after: after }});
}}
""")

    if "fatalError" in result:
        error(f"Test B failed: {result['fatalError']}")
        return {}
    if "timeout" in result:
        error("Test B timed out")
        return {}
    if "error" in result:
        error(f"Test B: {result['error']}")
        return {}

    before = result.get("before", {})
    after  = result.get("after",  {})
    info(f"  Before : {geom_str(before)}  screen={before.get('screen')}")
    info(f"  After  : {geom_str(after)}   screen={after.get('screen')}")

    changed = before != after
    if changed:
        ok("  Geometry changed — tile-left fired successfully")
    else:
        warn("  Geometry unchanged — slot may have had no effect")

    return after


def test_tile_right(runner: ScriptRunner, target_id: str,
                    slot_name: str) -> dict:
    """
    Test C — tile the target window right (symmetric confirmation).
    """
    # Derive the right slot name from the left slot name
    right_slot = slot_name.replace("Left", "Right")
    head(f"Test C — Tile right  (slot: {right_slot})")

    result = runner.run("tile_right", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === bare) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{
    send({{ error: "window not found", uuid: bare }});
}} else {{
    var before = {{
        x: Number(w.frameGeometry.x),     y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        screen: String(w.output ? w.output.name : ""),
    }};
    workspace.activeWindow = w;
    var pause = Date.now(); while(Date.now()-pause < 100) {{}}
    workspace["{right_slot}"]();
    var pause2 = Date.now(); while(Date.now()-pause2 < 500) {{}}
    var after = {{
        x: Number(w.frameGeometry.x),     y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        screen: String(w.output ? w.output.name : ""),
    }};
    send({{ ok: true, before: before, after: after }});
}}
""")

    if "fatalError" in result:
        error(f"Test C failed: {result['fatalError']}")
        return {}
    if "timeout" in result:
        error("Test C timed out")
        return {}

    before = result.get("before", {})
    after  = result.get("after",  {})
    info(f"  Before : {geom_str(before)}  screen={before.get('screen')}")
    info(f"  After  : {geom_str(after)}   screen={after.get('screen')}")

    changed = before != after
    if changed:
        ok("  Geometry changed — tile-right fired successfully")
    else:
        warn("  Geometry unchanged — slot may have had no effect")

    return after


def test_clear_tile_then_maximize(runner: ScriptRunner, target_id: str,
                                   tile_left_slot: str) -> None:
    """
    Test F — clear tile mode via w.tile = null, then maximize.

    Sequence:
      1. Tile-left  (puts window into quick-tile mode)
      2. w.tile = null  (attempt to detach from tile / clear mode flag)
      3. setMaximize(true, true)  (should now work if tile mode is cleared)

    Reports geometry and maximized state at each step.
    """
    head("Test F — Clear tile mode via w.tile = null, then maximize")

    result = runner.run("clear_tile_maximize", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === bare) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{
    send({{ error: "window not found" }});
}} else {{
    // Step 1: tile-left to enter quick-tile mode
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{}}
    workspace["{tile_left_slot}"]();
    var p2 = Date.now(); while(Date.now()-p2 < 800) {{}}

    var afterTile = {{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width),
        height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized),
        tile: String(w.tile),
    }};

    // Step 2: attempt to clear tile mode by setting w.tile = null
    var clearError = "";
    try {{
        w.tile = null;
        var p3 = Date.now(); while(Date.now()-p3 < 400) {{}}
    }} catch(e) {{
        clearError = String(e);
    }}

    var afterClear = {{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width),
        height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized),
        tile: String(w.tile),
    }};

    // Step 3: attempt setMaximize after clearing tile
    var maxError = "";
    try {{
        w.setMaximize(true, true);
        var p4 = Date.now(); while(Date.now()-p4 < 600) {{}}
    }} catch(e) {{
        maxError = String(e);
    }}

    var afterMax = {{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width),
        height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized),
        tile: String(w.tile),
    }};

    send({{
        ok:         true,
        afterTile:  afterTile,
        clearError: clearError,
        afterClear: afterClear,
        maxError:   maxError,
        afterMax:   afterMax,
    }});
}}
""", timeout=15.0)

    if "fatalError" in result:
        error(f"Test F failed: {result['fatalError']}")
        return
    if "timeout" in result:
        error("Test F timed out")
        return
    if "error" in result:
        error(f"Test F: {result['error']}")
        return

    def gstr(g):
        return f"{g.get('x')},{g.get('y')}  {g.get('width')}x{g.get('height')}"

    after_tile  = result.get("afterTile",  {})
    after_clear = result.get("afterClear", {})
    after_max   = result.get("afterMax",   {})
    clear_error = result.get("clearError", "")
    max_error   = result.get("maxError",   "")

    info(f"  After tile-left   : {gstr(after_tile)}"
         f"  maximized={after_tile.get('maximized')}"
         f"  tile={after_tile.get('tile')}")

    if clear_error:
        warn(f"  w.tile = null threw: {clear_error}")
    else:
        info(f"  After w.tile=null : {gstr(after_clear)}"
             f"  maximized={after_clear.get('maximized')}"
             f"  tile={after_clear.get('tile')}")

    if max_error:
        warn(f"  setMaximize threw : {max_error}")

    info(f"  After setMaximize : {gstr(after_max)}"
         f"  maximized={after_max.get('maximized')}"
         f"  tile={after_max.get('tile')}")

    if after_max.get("maximized"):
        ok("  SUCCESS — setMaximize worked after w.tile = null")
    else:
        warn("  FAILED — setMaximize still had no effect")
        if not clear_error and after_clear.get("tile") != after_tile.get("tile"):
            info("  (tile property did change — may need a different untile approach)")
        elif not clear_error:
            info("  (tile property unchanged — w.tile = null had no effect)")


def test_unmaximize_then_maximize(runner: ScriptRunner, target_id: str,
                                   tile_left_slot: str) -> None:
    """
    Test G — use setMaximize(false,false) to escape tile mode, then maximize.

    Hypothesis: setMaximize(false,false) clears the internal quick-tile flag
    as a side effect, even though it doesn't change w.tile visibly.  If true,
    a subsequent setMaximize(true,true) should succeed.

    Sequence:
      1. Tile-left            (enters quick-tile mode)
      2. setMaximize(false,false)  (known to work in tile mode — may clear flag)
      3. Wait 600ms
      4. setMaximize(true,true)   (does this work now?)
    """
    head("Test G — setMaximize(false,false) to escape tile mode, then maximize")

    result = runner.run("unmax_then_max", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === bare) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{
    send({{ error: "window not found" }});
}} else {{
    // Step 1: tile-left
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{}}
    workspace["{tile_left_slot}"]();
    var p2 = Date.now(); while(Date.now()-p2 < 800) {{}}

    var afterTile = {{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized), tile: String(w.tile),
    }};

    // Step 2: setMaximize(false, false) — known to work in tile mode
    w.setMaximize(false, false);
    var p3 = Date.now(); while(Date.now()-p3 < 600) {{}}

    var afterUnmax = {{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized), tile: String(w.tile),
    }};

    // Step 3: now attempt setMaximize(true, true)
    var maxError = "";
    try {{
        w.setMaximize(true, true);
        var p4 = Date.now(); while(Date.now()-p4 < 600) {{}}
    }} catch(e) {{
        maxError = String(e);
    }}

    var afterMax = {{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized), tile: String(w.tile),
    }};

    send({{
        ok:         true,
        afterTile:  afterTile,
        afterUnmax: afterUnmax,
        maxError:   maxError,
        afterMax:   afterMax,
    }});
}}
""", timeout=15.0)

    if "fatalError" in result:
        error(f"Test G failed: {result['fatalError']}")
        return
    if "timeout" in result:
        error("Test G timed out")
        return
    if "error" in result:
        error(f"Test G: {result['error']}")
        return

    def gstr(g):
        return f"{g.get('x')},{g.get('y')}  {g.get('width')}x{g.get('height')}"

    after_tile  = result.get("afterTile",  {})
    after_unmax = result.get("afterUnmax", {})
    after_max   = result.get("afterMax",   {})
    max_error   = result.get("maxError",   "")

    info(f"  After tile-left        : {gstr(after_tile)}"
         f"  maximized={after_tile.get('maximized')}"
         f"  tile={after_tile.get('tile')}")
    info(f"  After setMax(false,false): {gstr(after_unmax)}"
         f"  maximized={after_unmax.get('maximized')}"
         f"  tile={after_unmax.get('tile')}")
    if max_error:
        warn(f"  setMaximize(true,true) threw: {max_error}")
    info(f"  After setMax(true,true): {gstr(after_max)}"
         f"  maximized={after_max.get('maximized')}"
         f"  tile={after_max.get('tile')}")

    if after_max.get("maximized"):
        ok("  SUCCESS — setMaximize(false,false) clears tile mode flag")
        ok("  Sequence confirmed: tile-left → unmaximize → maximize works")
    else:
        warn("  FAILED — setMaximize(true,true) still blocked after unmaximize")


def test_double_maximize(runner: ScriptRunner, target_id: str,
                         tile_left_slot: str) -> None:
    """
    Test H -- call setMaximize(true,true) twice after tile-left, using two
    separate script loads so we can observe the state between calls.

    Test G showed that the first setMaximize(true,true) clears w.tile but
    does not actually maximize.  Splitting into two separate script executions
    avoids a potential KWin deadlock (which caused the single-script version
    to time out) and lets us read the intermediate state clearly.

    Sequence:
      Script 1: tile-left + first setMaximize(true,true)
      Script 2: second setMaximize(true,true)
    """
    head("Test H -- double setMaximize(true,true) after tile-left (two scripts)")

    # Script 1: tile-left then first setMaximize(true,true)
    result1 = runner.run("double_max_step1", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{{{}}}}
    workspace["{tile_left_slot}"]();
    var p2 = Date.now(); while(Date.now()-p2 < 800) {{{{}}}}
    var afterTile = {{{{ maximized: Boolean(w.maximized), tile: String(w.tile) }}}};

    w.setMaximize(true, true);
    var p3 = Date.now(); while(Date.now()-p3 < 600) {{{{}}}}
    var afterFirst = {{{{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized), tile: String(w.tile),
    }}}};
    send({{{{ ok: true, afterTile: afterTile, afterFirst: afterFirst }}}});
}}}}
""", timeout=12.0)

    if "fatalError" in result1:
        error(f"Test H step 1 failed: {result1['fatalError']}"); return
    if "timeout" in result1:
        error("Test H step 1 timed out"); return
    if "error" in result1:
        error(f"Test H step 1: {result1['error']}"); return

    after_tile  = result1.get("afterTile",  {})
    after_first = result1.get("afterFirst", {})
    info(f"  After tile-left       : maximized={after_tile.get('maximized')}"
         f"  tile={after_tile.get('tile')}")
    info(f"  After 1st setMax(T,T) : maximized={after_first.get('maximized')}"
         f"  tile={after_first.get('tile')}")

    # Script 2: second setMaximize(true,true) in a fresh script load
    result2 = runner.run("double_max_step2", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    w.setMaximize(true, true);
    var p = Date.now(); while(Date.now()-p < 600) {{{{}}}}
    send({{{{
        ok: true,
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized), tile: String(w.tile),
    }}}});
}}}}
""", timeout=10.0)

    if "fatalError" in result2:
        error(f"Test H step 2 failed: {result2['fatalError']}"); return
    if "timeout" in result2:
        error("Test H step 2 timed out"); return
    if "error" in result2:
        error(f"Test H step 2: {result2['error']}"); return

    def gstr(g):
        return f"{g.get('x')},{g.get('y')}  {g.get('width')}x{g.get('height')}"

    info(f"  After 2nd setMax(T,T) : {gstr(result2)}"
         f"  maximized={result2.get('maximized')}"
         f"  tile={result2.get('tile')}")

    if result2.get("maximized"):
        ok("  SUCCESS -- double setMaximize(true,true) works (two script loads)")
        ok("  Confirmed: tile-left -> setMax(T,T) [script 1] -> setMax(T,T) [script 2]")
    else:
        warn("  FAILED -- window still not maximized after two separate script calls")


def test_safe_tile_then_maximize(runner: ScriptRunner, target_id: str,
                                  tile_left_slot: str) -> None:
    """
    Test I -- confirmed safe two-script sequence: tile-left then maximize.

    Test G showed that setMax(false,false) -> setMax(true,true) in one script
    does not hang KWin and leaves tile=null.  Test H step 1 showed that
    setMax(true,true) immediately after tile-left DOES hang KWin.

    So the safe sequence is:
      Script 1: tile-left -> setMax(false,false) -> setMax(true,true)
                (same as Test G -- does not hang, leaves tile=null)
      Script 2: setMax(true,true)
                (tile is null now -- does this finally maximize?)
    """
    head("Test I -- safe two-script tile-then-maximize sequence")

    # Script 1: tile-left, then unmax, then first setMax(true,true)
    # This is the exact sequence from Test G which is known not to hang.
    result1 = runner.run("safe_tile_max_step1", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    // tile-left to shrink the window
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{{{}}}}
    workspace["{tile_left_slot}"]();
    var p2 = Date.now(); while(Date.now()-p2 < 800) {{{{}}}}
    var afterTile = {{{{ maximized: Boolean(w.maximized), tile: String(w.tile) }}}};

    // setMax(false,false) first -- safe in tile mode
    w.setMaximize(false, false);
    var p3 = Date.now(); while(Date.now()-p3 < 400) {{{{}}}}

    // setMax(true,true) -- clears tile to null (but doesn't maximize yet)
    w.setMaximize(true, true);
    var p4 = Date.now(); while(Date.now()-p4 < 600) {{{{}}}}

    var afterStep1 = {{{{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized), tile: String(w.tile),
    }}}};
    send({{{{ ok: true, afterTile: afterTile, afterStep1: afterStep1 }}}});
}}}}
""", timeout=12.0)

    if "fatalError" in result1:
        error(f"Test I step 1 failed: {result1['fatalError']}"); return
    if "timeout" in result1:
        error("Test I step 1 timed out"); return
    if "error" in result1:
        error(f"Test I step 1: {result1['error']}"); return

    after_tile  = result1.get("afterTile",  {})
    after_step1 = result1.get("afterStep1", {})
    info(f"  After tile-left       : maximized={after_tile.get('maximized')}"
         f"  tile={after_tile.get('tile')}")
    info(f"  After step 1 complete : maximized={after_step1.get('maximized')}"
         f"  tile={after_step1.get('tile')}")

    if after_step1.get("tile") != "null":
        warn("  tile not null after step 1 -- step 2 may not help")

    # Script 2: fresh load -- tile should now be null, try setMax(true,true)
    result2 = runner.run("safe_tile_max_step2", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    w.setMaximize(true, true);
    var p = Date.now(); while(Date.now()-p < 600) {{{{}}}}
    send({{{{
        ok: true,
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        maximized: Boolean(w.maximized), tile: String(w.tile),
    }}}});
}}}}
""", timeout=10.0)

    if "fatalError" in result2:
        error(f"Test I step 2 failed: {result2['fatalError']}"); return
    if "timeout" in result2:
        error("Test I step 2 timed out"); return
    if "error" in result2:
        error(f"Test I step 2: {result2['error']}"); return

    info(f"  After step 2 (setMax(T,T)): "
         f"{result2.get('x')},{result2.get('y')}  "
         f"{result2.get('width')}x{result2.get('height')}"
         f"  maximized={result2.get('maximized')}"
         f"  tile={result2.get('tile')}")

    if result2.get("maximized"):
        ok("  SUCCESS -- confirmed working sequence:")
        ok("  tile-left -> setMax(F,F) -> setMax(T,T) [script 1]")
        ok("             -> setMax(T,T) [script 2]  => maximized")
    else:
        warn("  FAILED -- window still not maximized after two-script sequence")


def test_minimize_then_maximize(runner: ScriptRunner, target_id: str,
                                 tile_left_slot: str) -> None:
    """
    Test J -- minimize after tile-left, then maximize.

    Hypothesis: minimizing exits the quick-tile mode entirely, so a
    subsequent setMaximize(true,true) works normally.

    Sequence:
      Script 1: tile-left -> minimize
      Script 2: setMaximize(true,true)
    """
    head("Test J -- minimize after tile-left, then maximize")

    # Script 1: tile-left then minimize
    result1 = runner.run("min_max_step1", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{{{}}}}
    workspace["{tile_left_slot}"]();
    var p2 = Date.now(); while(Date.now()-p2 < 800) {{{{}}}}
    var afterTile = {{{{ minimized: Boolean(w.minimized), maximized: Boolean(w.maximized), tile: String(w.tile) }}}};

    w.minimized = true;
    var p3 = Date.now(); while(Date.now()-p3 < 400) {{{{}}}}
    var afterMin = {{{{ minimized: Boolean(w.minimized), maximized: Boolean(w.maximized), tile: String(w.tile) }}}};

    send({{{{ ok: true, afterTile: afterTile, afterMin: afterMin }}}});
}}}}
""", timeout=10.0)

    if "fatalError" in result1:
        error(f"Test J step 1 failed: {result1['fatalError']}"); return
    if "timeout" in result1:
        error("Test J step 1 timed out"); return
    if "error" in result1:
        error(f"Test J step 1: {result1['error']}"); return

    after_tile = result1.get("afterTile", {})
    after_min  = result1.get("afterMin",  {})
    info(f"  After tile-left : minimized={after_tile.get('minimized')}"
         f"  maximized={after_tile.get('maximized')}"
         f"  tile={after_tile.get('tile')}")
    info(f"  After minimize  : minimized={after_min.get('minimized')}"
         f"  maximized={after_min.get('maximized')}"
         f"  tile={after_min.get('tile')}")

    # Script 2: setMaximize(true,true) from minimized state
    result2 = runner.run("min_max_step2", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    w.minimized = false;
    var p1 = Date.now(); while(Date.now()-p1 < 300) {{{{}}}}
    w.setMaximize(true, true);
    var p2 = Date.now(); while(Date.now()-p2 < 600) {{{{}}}}
    send({{{{
        ok: true,
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
        minimized: Boolean(w.minimized), maximized: Boolean(w.maximized),
        tile: String(w.tile),
    }}}});
}}}}
""", timeout=10.0)

    if "fatalError" in result2:
        error(f"Test J step 2 failed: {result2['fatalError']}"); return
    if "timeout" in result2:
        error("Test J step 2 timed out"); return
    if "error" in result2:
        error(f"Test J step 2: {result2['error']}"); return

    info(f"  After unminimize+setMax(T,T): "
         f"{result2.get('x')},{result2.get('y')}  "
         f"{result2.get('width')}x{result2.get('height')}"
         f"  maximized={result2.get('maximized')}"
         f"  tile={result2.get('tile')}")

    if result2.get("maximized"):
        ok("  SUCCESS -- minimize exits tile mode cleanly")
        ok("  Confirmed sequence: tile-left -> minimize [script 1]")
        ok("                   -> unminimize + setMax(T,T) [script 2]")
    else:
        warn("  FAILED -- setMaximize still blocked after minimize/unminimize")


def test_slot_maximize(runner: ScriptRunner, target_id: str,
                        tile_left_slot: str) -> None:
    """
    Test K -- use workspace.slotWindowMaximize() after tile-left.

    workspace.slotWindowMaximize() routes through KWin's window operation
    system (performWindowOperation), which is the same code path as the
    taskbar "Maximize" option that works after tile-left manually.
    This is fundamentally different from w.setMaximize(true,true) which
    directly sets the property and is blocked by the quick-tile mode flag.

    Two separate script loads:
      Script 1: tile-left only
      Script 2: set activeWindow + slotWindowMaximize()
    """
    head("Test K -- workspace.slotWindowMaximize() after tile-left")

    # Script 1: tile-left only -- nothing else in this script
    result1 = runner.run("slot_max_step1", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{{{}}}}
    workspace["{tile_left_slot}"]();
    var p2 = Date.now(); while(Date.now()-p2 < 800) {{{{}}}}
    send({{{{
        ok:        true,
        maximized: Boolean(w.maximized),
        tile:      String(w.tile),
        x:         Number(w.frameGeometry.x),
        y:         Number(w.frameGeometry.y),
        width:     Number(w.frameGeometry.width),
        height:    Number(w.frameGeometry.height),
    }}}});
}}}}
""", timeout=10.0)

    if "fatalError" in result1:
        error(f"Test K step 1 failed: {result1['fatalError']}"); return
    if "timeout" in result1:
        error("Test K step 1 timed out"); return
    if "error" in result1:
        error(f"Test K step 1: {result1['error']}"); return

    info(f"  After tile-left : "
         f"{result1.get('x')},{result1.get('y')}  "
         f"{result1.get('width')}x{result1.get('height')}"
         f"  maximized={result1.get('maximized')}"
         f"  tile={result1.get('tile')}")

    # Script 2: slotWindowMaximize() via the workspace slot
    result2 = runner.run("slot_max_step2", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    // slotWindowMaximize operates on workspace.activeWindow
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{{{}}}}

    // Check if the slot exists
    var slotExists = typeof workspace.slotWindowMaximize === "function";
    if (!slotExists) {{{{
        send({{{{ error: "slotWindowMaximize not a function",
                   type: typeof workspace.slotWindowMaximize }}}});
    }}}} else {{{{
        workspace.slotWindowMaximize();
        var p2 = Date.now(); while(Date.now()-p2 < 800) {{{{}}}}
        send({{{{
            ok:        true,
            maximized: Boolean(w.maximized),
            tile:      String(w.tile),
            x:         Number(w.frameGeometry.x),
            y:         Number(w.frameGeometry.y),
            width:     Number(w.frameGeometry.width),
            height:    Number(w.frameGeometry.height),
        }}}});
    }}}}
}}}}
""", timeout=10.0)

    if "fatalError" in result2:
        error(f"Test K step 2 failed: {result2['fatalError']}"); return
    if "timeout" in result2:
        error("Test K step 2 timed out"); return
    if "error" in result2:
        error(f"Test K step 2: {result2['error']}"); return

    info(f"  After slotWindowMaximize: "
         f"{result2.get('x')},{result2.get('y')}  "
         f"{result2.get('width')}x{result2.get('height')}"
         f"  maximized={result2.get('maximized')}"
         f"  tile={result2.get('tile')}")

    if result2.get("maximized"):
        ok("  SUCCESS -- slotWindowMaximize() works after tile-left")
        ok("  Confirmed sequence: tile-left [script 1] -> slotWindowMaximize [script 2]")
    else:
        warn("  FAILED -- slotWindowMaximize() did not maximize the window")


def test_introspect_maximize_slots(runner: ScriptRunner) -> list[str]:
    """
    Test L -- enumerate all workspace properties/methods whose names contain
    'max', 'maximize', or 'slot', to find the correct maximize slot name.
    """
    head("Test L -- Introspect workspace for maximize-related slot methods")

    result = runner.run("introspect_max_slots", """
var found = [];
for (var key in workspace) {
    var kl = key.toLowerCase();
    if (kl.indexOf("max") !== -1 || kl.indexOf("slot") !== -1) {
        found.push({ name: key, type: typeof workspace[key] });
    }
}
// Also probe specific candidates explicitly
var candidates = [
    "slotWindowMaximize",
    "slotWindowMaximizeVertical",
    "slotWindowMaximizeHorizontal",
    "slotWindowRestore",
    "slotWindowShade",
    "slotWindowRaise",
    "slotWindowLower",
    "slotWindowMinimize",
    "slotWindowClose",
    "slotWindowMove",
    "slotWindowResize",
    "slotWindowAboveOthers",
    "slotWindowBelowOthers",
    "slotWindowFullScreen",
];
var explicit = [];
for (var i = 0; i < candidates.length; i++) {
    explicit.push({
        name:   candidates[i],
        type:   typeof workspace[candidates[i]],
        exists: typeof workspace[candidates[i]] === "function",
    });
}
send({ found: found, explicit: explicit });
""")

    if "fatalError" in result:
        error(f"Test L failed: {result['fatalError']}")
        return []
    if "timeout" in result:
        error("Test L timed out")
        return []

    found    = result.get("found",    [])
    explicit = result.get("explicit", [])

    if found:
        info(f"Workspace properties/methods containing 'max' or 'slot' ({len(found)} found):")
        for p in sorted(found, key=lambda x: x["name"]):
            info(f"  {p['name']:<45} (type: {p['type']})")
    else:
        warn("No max/slot properties found via enumeration")

    head("  Explicit maximize/slot probe:")
    available = []
    for p in explicit:
        exists = p.get("exists", False)
        rline(p["name"], p["type"], good=exists)
        if exists:
            available.append(p["name"])

    if available:
        ok(f"\n  Available: {available}")
    else:
        warn("\n  None of the probed slot names are available")

    return available


def test_slot_maximize_hv(runner: ScriptRunner, target_id: str,
                           tile_left_slot: str) -> None:
    """
    Test M -- slotWindowMaximizeHorizontal + slotWindowMaximizeVertical
    after tile-left, each in a separate script.

    If the tile-mode block is specific to w.setMaximize() (the direct
    property setter), these slot methods may bypass it.  Three scripts:
      Script 1: tile-left only
      Script 2: slotWindowMaximizeHorizontal
      Script 3: slotWindowMaximizeVertical
    """
    head("Test M -- slotWindowMaximizeHorizontal + Vertical after tile-left")

    # Script 1: tile-left only
    result1 = runner.run("hv_step1", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{{{}}}}
    workspace["{tile_left_slot}"]();
    var p2 = Date.now(); while(Date.now()-p2 < 800) {{{{}}}}
    send({{{{
        ok: true, maximized: Boolean(w.maximized), tile: String(w.tile),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
    }}}});
}}}}
""", timeout=10.0)

    if "fatalError" in result1: error(f"Test M step 1: {result1['fatalError']}"); return
    if "timeout"    in result1: error("Test M step 1 timed out"); return
    if "error"      in result1: error(f"Test M step 1: {result1['error']}"); return
    info(f"  After tile-left       : {result1.get('width')}x{result1.get('height')}"
         f"  maximized={result1.get('maximized')}  tile={result1.get('tile')}")

    # Script 2: slotWindowMaximizeHorizontal
    result2 = runner.run("hv_step2", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{{{}}}}
    workspace.slotWindowMaximizeHorizontal();
    var p2 = Date.now(); while(Date.now()-p2 < 600) {{{{}}}}
    send({{{{
        ok: true, maximized: Boolean(w.maximized), tile: String(w.tile),
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
    }}}});
}}}}
""", timeout=10.0)

    if "fatalError" in result2: error(f"Test M step 2: {result2['fatalError']}"); return
    if "timeout"    in result2: error("Test M step 2 timed out"); return
    if "error"      in result2: error(f"Test M step 2: {result2['error']}"); return
    info(f"  After slotMaximizeH   : {result2.get('x')},{result2.get('y')}"
         f"  {result2.get('width')}x{result2.get('height')}"
         f"  maximized={result2.get('maximized')}  tile={result2.get('tile')}")

    # Script 3: slotWindowMaximizeVertical
    result3 = runner.run("hv_step3", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{{{
    if (String(wins[i].internalId).replace(/[{{{{}}}}]/g,"") === bare) {{{{
        w = wins[i]; break;
    }}}}
}}}}
if (!w) {{{{
    send({{{{ error: "window not found" }}}});
}}}} else {{{{
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{{{}}}}
    workspace.slotWindowMaximizeVertical();
    var p2 = Date.now(); while(Date.now()-p2 < 600) {{{{}}}}
    send({{{{
        ok: true, maximized: Boolean(w.maximized), tile: String(w.tile),
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
    }}}});
}}}}
""", timeout=10.0)

    if "fatalError" in result3: error(f"Test M step 3: {result3['fatalError']}"); return
    if "timeout"    in result3: error("Test M step 3 timed out"); return
    if "error"      in result3: error(f"Test M step 3: {result3['error']}"); return
    info(f"  After slotMaximizeV   : {result3.get('x')},{result3.get('y')}"
         f"  {result3.get('width')}x{result3.get('height')}"
         f"  maximized={result3.get('maximized')}  tile={result3.get('tile')}")

    if result3.get("maximized"):
        ok("  SUCCESS -- slotWindowMaximizeHorizontal + Vertical works after tile-left")
    elif result2.get("width") != result1.get("width"):
        ok("  Horizontal slot fired (width changed)")
        warn("  Vertical slot did not complete maximization")
    else:
        warn("  FAILED -- neither slot changed the geometry")


def test_introspect_screen_move(runner: ScriptRunner) -> None:
    """
    Test N -- enumerate all workspace methods related to moving windows
    between screens, and check whether sendClientToScreen() is callable.

    Also probes the window object for any screen/output-related methods
    that might allow direct screen assignment without geometry tricks.
    """
    head("Test N -- Introspect screen-move methods on workspace and window")

    result = runner.run("introspect_screen_move", f"""
// --- Workspace-level screen move methods ---
var wsFound = [];
var wsKeywords = ["screen", "output", "monitor", "display"];
for (var key in workspace) {{
    var kl = key.toLowerCase();
    for (var k = 0; k < wsKeywords.length; k++) {{
        if (kl.indexOf(wsKeywords[k]) !== -1) {{
            wsFound.push({{ name: key, type: typeof workspace[key] }});
            break;
        }}
    }}
}}

// Explicit workspace candidates
var wsCandidates = [
    "sendClientToScreen",
    "sendWindowToScreen",
    "slotWindowToNextScreen",
    "slotWindowToPrevScreen",
    "slotWindowToAboveScreen",
    "slotWindowToBelowScreen",
    "slotWindowToLeftScreen",
    "slotWindowToRightScreen",
    "slotSwitchToNextScreen",
    "slotSwitchToPrevScreen",
    "slotSwitchToLeftScreen",
    "slotSwitchToRightScreen",
    "slotSwitchToAboveScreen",
    "slotSwitchToBelowScreen",
    "activeOutput",
    "activeScreen",
    "screens",
    "outputs",
];
var wsExplicit = [];
for (var i = 0; i < wsCandidates.length; i++) {{
    var key = wsCandidates[i];
    var t   = typeof workspace[key];
    var v   = "";
    try {{
        if (t !== "function") {{ v = String(workspace[key]).slice(0, 80); }}
    }} catch(e) {{ v = "(error)"; }}
    wsExplicit.push({{ name: key, type: t, value: v, exists: t !== "undefined" }});
}}

// --- Window-level screen/output methods ---
// Use the active window for window-object introspection
var w = workspace.activeWindow;
var winFound = [];
var winExplicit = [];
if (w) {{
    for (var key in w) {{
        var kl = key.toLowerCase();
        for (var k = 0; k < wsKeywords.length; k++) {{
            if (kl.indexOf(wsKeywords[k]) !== -1) {{
                var t = typeof w[key];
                var v = "";
                try {{
                    if (t !== "function") {{ v = String(w[key]).slice(0,60); }}
                }} catch(e) {{ v = "(error)"; }}
                winFound.push({{ name: key, type: t, value: v }});
                break;
            }}
        }}
    }}

    var winCandidates = [
        "output", "screen", "sendToOutput", "sendToScreen",
        "setOutput", "setScreen", "moveToOutput", "moveToScreen",
        "outputChanged",
    ];
    for (var i = 0; i < winCandidates.length; i++) {{
        var key = winCandidates[i];
        var t   = typeof w[key];
        var v   = "";
        try {{
            if (t !== "function") {{ v = String(w[key]).slice(0,60); }}
        }} catch(e) {{ v = "(error)"; }}
        winExplicit.push({{ name: key, type: t, value: v,
                            exists: t !== "undefined" }});
    }}
}}

// --- Try calling sendClientToScreen to see if it accepts arguments ---
var sendClientTest = {{ tried: false, error: "" }};
if (typeof workspace.sendClientToScreen === "function" && w) {{
    sendClientTest.tried = true;
    try {{
        // Just call with current screen to test the signature — no actual move
        workspace.sendClientToScreen(w, w.output);
        sendClientTest.result = "called without error";
    }} catch(e) {{
        sendClientTest.error = String(e);
    }}
}}

send({{
    ok:          true,
    wsFound:     wsFound,
    wsExplicit:  wsExplicit,
    winFound:    winFound,
    winExplicit: winExplicit,
    sendClientTest: sendClientTest,
    hasActiveWindow: Boolean(w),
}});
""", timeout=10.0)

    if "fatalError" in result:
        error(f"Test N failed: {result['fatalError']}"); return
    if "timeout"    in result:
        error("Test N timed out"); return
    if "error"      in result:
        error(f"Test N: {result['error']}"); return

    # Workspace enumerated screen-related properties
    ws_found = result.get("wsFound", [])
    if ws_found:
        info(f"Workspace screen-related properties ({len(ws_found)} found):")
        for p in sorted(ws_found, key=lambda x: x["name"]):
            val = f" = {p['value']!r}" if p.get("value") else ""
            info(f"  {p['name']:<45} ({p['type']}){val}")
    else:
        warn("No screen-related workspace properties found via enumeration")

    # Workspace explicit probes
    head("  Workspace explicit probe:")
    for p in result.get("wsExplicit", []):
        val = f"  [{p['value']}]" if p.get("value") else ""
        rline(p["name"], f"{p['type']}{val}", good=p.get("exists", False))

    # Window enumerated screen-related properties
    win_found = result.get("winFound", [])
    if not result.get("hasActiveWindow"):
        warn("No active window — window-level introspection skipped")
    elif win_found:
        head("  Window screen-related properties:")
        for p in sorted(win_found, key=lambda x: x["name"]):
            val = f" = {p['value']!r}" if p.get("value") else ""
            info(f"  {p['name']:<45} ({p['type']}){val}")
    else:
        warn("No screen-related properties found on window object")

    # Window explicit probes
    head("  Window explicit probe:")
    for p in result.get("winExplicit", []):
        val = f"  [{p['value']}]" if p.get("value") else ""
        rline(p["name"], f"{p['type']}{val}", good=p.get("exists", False))

    # sendClientToScreen call test
    sc = result.get("sendClientTest", {})
    head("  sendClientToScreen call test:")
    if sc.get("tried"):
        if sc.get("error"):
            warn(f"  Called but threw: {sc['error']}")
        else:
            ok(f"  {sc.get('result', 'called')}")
    else:
        info("  Not tried (function not present or no active window)")


def get_original_geometry(runner: ScriptRunner, target_id: str) -> dict:
    """Read the window's current geometry before any test modifies it."""
    result = runner.run("get_geom", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === bare) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{
    send({{ error: "window not found" }});
}} else {{
    send({{
        x:         Number(w.frameGeometry.x),
        y:         Number(w.frameGeometry.y),
        width:     Number(w.frameGeometry.width),
        height:    Number(w.frameGeometry.height),
        screen:    String(w.output ? w.output.name : ""),
        maximized: Boolean(w.maximized),
    }});
}}
""")
    return result


def test_restore(runner: ScriptRunner, target_id: str,
                 original: dict) -> None:
    """
    Test D -- restore the window to its original geometry and maximize state.
    """
    head("Test D -- Restore original geometry")

    if not original:
        warn("  No original geometry recorded -- skipping restore")
        return

    x       = original.get("x", 0)
    y       = original.get("y", 0)
    w       = original.get("width", 800)
    h       = original.get("height", 600)
    was_max = original.get("maximized", False)
    do_max  = "true" if was_max else "false"

    result = runner.run("restore", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var win   = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === bare) {{
        win = wins[i]; break;
    }}
}}
if (!win) {{
    send({{ error: "window not found" }});
}} else {{
    // Clear tile mode and unmaximize first so the window can be repositioned
    win.setMaximize(false, false);
    var p1 = Date.now(); while(Date.now()-p1 < 300) {{}}
    win.frameGeometry = {{ x: {x}, y: {y}, width: {w}, height: {h} }};
    var p2 = Date.now(); while(Date.now()-p2 < 300) {{}}
    if ({do_max}) {{
        win.setMaximize(true, true);
        var p3 = Date.now(); while(Date.now()-p3 < 400) {{}}
    }}
    send({{ ok: true, maximized: Boolean(win.maximized),
            x: Number(win.frameGeometry.x),
            y: Number(win.frameGeometry.y) }});
}}
""")

    if result.get("ok"):
        state = "maximized" if result.get("maximized") else f"{x},{y}  {w}x{h}"
        ok(f"  Restored [{state}]")
    else:
        warn(f"  Restore may have failed: {result}")


def test_window_tile_properties(runner: ScriptRunner, target_id: str,
                                tile_left_slot: str) -> None:
    """
    Test E — enumerate tile-related properties on the window object itself.

    Tiles the window left (to put it into KWin's quick-tile mode), then
    inspects all properties/methods on the window object whose names contain
    'tile', 'quick', or 'mode'.  This tells us whether there is a scriptable
    way to clear the tile mode flag — the equivalent of clicking the restore
    button — so that setMaximize() works normally afterward.
    """
    head("Test E — Window tile-mode properties (post-tile introspection)")

    result = runner.run("window_tile_props", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === bare) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{
    send({{ error: "window not found" }});
}} else {{
    // Record geometry before tile
    var before = {{
        x: Number(w.frameGeometry.x), y: Number(w.frameGeometry.y),
        width: Number(w.frameGeometry.width), height: Number(w.frameGeometry.height),
    }};

    // Put window into quick-tile mode
    workspace.activeWindow = w;
    var p1 = Date.now(); while(Date.now()-p1 < 100) {{}}
    workspace["{tile_left_slot}"]();
    var p2 = Date.now(); while(Date.now()-p2 < 800) {{}}

    // Now enumerate all window properties containing tile/quick/mode
    var found = [];
    for (var key in w) {{
        var kl = key.toLowerCase();
        if (kl.indexOf("tile")  !== -1 ||
            kl.indexOf("quick") !== -1 ||
            kl.indexOf("mode")  !== -1) {{
            var t = typeof w[key];
            var v = "";
            try {{
                if (t !== "function") {{
                    v = String(w[key]);
                }}
            }} catch(e) {{ v = "(error reading)"; }}
            found.push({{ name: key, type: t, value: v }});
        }}
    }}

    // Also probe specific candidates explicitly
    var candidates = [
        "quickTileMode",
        "setQuickTileMode",
        "tile",
        "tiled",
        "tilingMode",
        "clearQuickTile",
        "resetTile",
        "isTiled",
        "quickTile",
    ];
    var explicit = [];
    for (var i = 0; i < candidates.length; i++) {{
        var key = candidates[i];
        var t   = typeof w[key];
        var v   = "";
        try {{
            if (t !== "function") {{ v = String(w[key]); }}
        }} catch(e) {{ v = "(error reading)"; }}
        explicit.push({{ name: key, type: t, value: v,
                         exists: t !== "undefined" }});
    }}

    // Try calling setMaximize while in tile mode — does it work?
    var maxBefore = Boolean(w.maximized);
    var maxError  = "";
    try {{
        w.setMaximize(true, true);
        var p3 = Date.now(); while(Date.now()-p3 < 400) {{}}
    }} catch(e) {{
        maxError = String(e);
    }}
    var maxAfter = Boolean(w.maximized);

    send({{
        ok:         true,
        before:     before,
        found:      found,
        explicit:   explicit,
        maxBefore:  maxBefore,
        maxAfter:   maxAfter,
        maxError:   maxError,
    }});
}}
""", timeout=12.0)

    if "fatalError" in result:
        error(f"Test E failed: {result['fatalError']}")
        return
    if "timeout" in result:
        error("Test E timed out")
        return
    if "error" in result:
        error(f"Test E: {result['error']}")
        return

    # Enumerated tile-related properties
    found = result.get("found", [])
    if found:
        info(f"Tile/quick/mode properties on window object ({len(found)} found):")
        for p in found:
            val = f" = {p['value']!r}" if p["value"] else ""
            info(f"  {p['name']}  (type: {p['type']}){val}")
    else:
        warn("No tile/quick/mode properties found via enumeration")

    # Explicit probes
    head("  Explicit property probe:")
    for p in result.get("explicit", []):
        exists = p.get("exists", False)
        val = f" = {p['value']!r}" if p["value"] and p["type"] != "function" else ""
        rline(p["name"], f"{p['type']}{val}", good=exists)

    # setMaximize while in tile mode
    head("  setMaximize(true,true) while in tile mode:")
    max_before = result.get("maxBefore", False)
    max_after  = result.get("maxAfter",  False)
    max_error  = result.get("maxError",  "")
    info(f"  maximized before call : {max_before}")
    info(f"  maximized after call  : {max_after}")
    if max_error:
        warn(f"  setMaximize threw     : {max_error}")
    if max_after:
        ok("  setMaximize worked while in tile mode")
    else:
        warn("  setMaximize had no effect while in tile mode — tile mode blocks it")
    """Read the window's current geometry before any test modifies it."""
    result = runner.run("get_geom", f"""
var bare  = "{target_id}";
var wins  = workspace.windowList();
var w     = null;
for (var i = 0; i < wins.length; i++) {{
    if (String(wins[i].internalId).replace(/[{{}}]/g,"") === bare) {{
        w = wins[i]; break;
    }}
}}
if (!w) {{
    send({{ error: "window not found" }});
}} else {{
    send({{
        x:      Number(w.frameGeometry.x),
        y:      Number(w.frameGeometry.y),
        width:  Number(w.frameGeometry.width),
        height: Number(w.frameGeometry.height),
        screen: String(w.output ? w.output.name : ""),
        maximized: Boolean(w.maximized),
    }});
}}
""")
    return result


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="kwin_tile_test.py",
        description=(
            "Test KWin tiling slot methods.\n"
            "Get a window internalId first with: "
            "python3 kwin_probe.py --class <rc> -- <command>"
        ),
    )
    parser.add_argument("--id", required=True, metavar="UUID",
        help="internalId of a live window (without braces)")
    parser.add_argument("--disable-teste", action="store_true",
        help="Skip Test E (window tile-mode property introspection)")
    parser.add_argument("--disable-testf", action="store_true",
        help="Skip Test F (w.tile = null then maximize)")
    parser.add_argument("--disable-testg", action="store_true",
        help="Skip Test G (setMax(false,false) then maximize)")
    parser.add_argument("--disable-testh", action="store_true",
        help="Skip Test H (double setMax — known to hang KWin)")
    parser.add_argument("--disable-testi", action="store_true",
        help="Skip Test I (two-script safe sequence)")
    parser.add_argument("--disable-testj", action="store_true",
        help="Skip Test J (minimize then maximize)")
    parser.add_argument("--disable-testk", action="store_true",
        help="Skip Test K (workspace.slotWindowMaximize after tile-left)")
    parser.add_argument("--disable-testl", action="store_true",
        help="Skip Test L (introspect workspace for maximize slot names)")
    parser.add_argument("--disable-testm", action="store_true",
        help="Skip Test M (slotWindowMaximizeHorizontal + Vertical after tile-left)")
    parser.add_argument("--disable-testn", action="store_true",
        help="Skip Test N (introspect screen-move methods)")
    args = parser.parse_args()

    target_id = args.id.strip("{}")

    head("═══ KWin Tiling Slot Test ═══════════════════════════════════════")
    info(f"Target window : {target_id}")

    # ── Connect to D-Bus ──────────────────────────────────────────────────────
    bus = SessionBus()
    try:
        scripting = bus.get(KWIN_SERVICE, SCRIPTING_PATH)
    except Exception as exc:
        error(f"Cannot connect to KWin scripting interface: {exc}")
        sys.exit(1)

    receiver = TileTestReceiver()
    try:
        registration = bus.publish(RECEIVER_SERVICE, (RECEIVER_PATH, receiver))
    except Exception as exc:
        error(f"Cannot publish D-Bus receiver: {exc}")
        sys.exit(1)

    # Run GLib loop in a daemon thread for D-Bus callbacks
    loop = GLib.MainLoop()
    t = threading.Thread(target=loop.run, daemon=True)
    t.start()
    # Allow the GLib event loop to start processing before the first script fires
    time.sleep(1.0)

    runner = ScriptRunner(scripting, receiver)

    # ── Read original geometry before any modification ────────────────────────
    original = get_original_geometry(runner, target_id)
    info(f"[DIAG] get_original_geometry raw result: {original}")
    if "error" in original or "timeout" in original:
        error(f"Cannot find window {target_id!r} — is it still open?")
        error("Get a fresh internalId with: python3 kwin_probe.py --class <rc> -- <cmd>")
        loop.quit()
        sys.exit(1)

    info(f"Original geometry : {geom_str(original)}  "
         f"screen={original.get('screen')}  "
         f"maximized={original.get('maximized')}")

    # ── Test A: discover available slot names ─────────────────────────────────
    available_slots = test_introspect_slots(runner)

    # Determine which left-tile slot to use for tests B and C
    # Prefer the most commonly documented name; fall back if absent
    preferred = "slotWindowQuickTileLeft"
    if preferred in available_slots:
        tile_left_slot = preferred
    elif available_slots:
        # Use whatever left-tile slot was found
        lefts = [s for s in available_slots if "left" in s.lower()]
        tile_left_slot = lefts[0] if lefts else available_slots[0]
    else:
        warn("\nNo tiling slot methods confirmed available.")
        warn("Tests B, C, D skipped.  Check Test A output above.")
        warn("The slot names may differ in this KWin version.")
        loop.quit()
        sys.exit(0)

    # ── Test B: tile left ─────────────────────────────────────────────────────
    after_left = test_tile_left(runner, target_id, tile_left_slot)
    time.sleep(0.3)

    # ── Test C: tile right ────────────────────────────────────────────────────
    after_right = test_tile_right(runner, target_id, tile_left_slot)
    time.sleep(0.3)

    # ── Test E: window tile-mode properties ───────────────────────────────────
    if not args.disable_teste:
        test_window_tile_properties(runner, target_id, tile_left_slot)
        time.sleep(0.3)
    else:
        info("Test E skipped (--disable-teste)")

    # ── Test F: w.tile = null then maximize ───────────────────────────────────
    if not args.disable_testf:
        test_clear_tile_then_maximize(runner, target_id, tile_left_slot)
        time.sleep(0.3)
    else:
        info("Test F skipped (--disable-testf)")

    # ── Test G: setMaximize(false,false) to escape tile mode, then maximize ───
    if not args.disable_testg:
        test_unmaximize_then_maximize(runner, target_id, tile_left_slot)
        time.sleep(0.3)
    else:
        info("Test G skipped (--disable-testg)")

    # ── Test H: double setMaximize(true,true) — known to hang KWin ────────────
    if not args.disable_testh:
        test_double_maximize(runner, target_id, tile_left_slot)
        time.sleep(0.3)
    else:
        info("Test H skipped (--disable-testh)")

    # ── Test I: safe two-script tile-then-maximize sequence ───────────────────
    if not args.disable_testi:
        test_safe_tile_then_maximize(runner, target_id, tile_left_slot)
        time.sleep(0.3)
    else:
        info("Test I skipped (--disable-testi)")

    # ── Test J: minimize after tile-left, then maximize ───────────────────────
    if not args.disable_testj:
        test_minimize_then_maximize(runner, target_id, tile_left_slot)
        time.sleep(0.3)
    else:
        info("Test J skipped (--disable-testj)")

    # ── Test L: introspect workspace for maximize-related slot names ──────────
    max_slots: list[str] = []
    if not args.disable_testl:
        max_slots = test_introspect_maximize_slots(runner)
        time.sleep(0.3)
    else:
        info("Test L skipped (--disable-testl)")

    # ── Test K: workspace.slotWindowMaximize() after tile-left ────────────────
    # Use the first confirmed maximize slot from Test L, falling back to the
    # expected name if Test L was skipped or found nothing.
    max_slot = next(
        (s for s in max_slots if "maximize" in s.lower() and "horizontal" not in s.lower() and "vertical" not in s.lower()),
        "slotWindowMaximize"
    )
    if not args.disable_testk:
        test_slot_maximize(runner, target_id, tile_left_slot)
        time.sleep(0.3)
    else:
        info("Test K skipped (--disable-testk)")

    # ── Test M: slotWindowMaximizeHorizontal + Vertical after tile-left ───────
    if not args.disable_testm:
        test_slot_maximize_hv(runner, target_id, tile_left_slot)
        time.sleep(0.3)
    else:
        info("Test M skipped (--disable-testm)")

    # ── Test N: introspect screen-move methods ────────────────────────────────
    if not args.disable_testn:
        test_introspect_screen_move(runner)
        time.sleep(0.3)
    else:
        info("Test N skipped (--disable-testn)")

    # ── Test D: restore ───────────────────────────────────────────────────────
    test_restore(runner, target_id, original)

    # ── Summary ───────────────────────────────────────────────────────────────
    head("═══ Summary ═════════════════════════════════════════════════════")
    if available_slots:
        ok(f"Available tiling slots : {available_slots}")
    else:
        warn("No tiling slot methods found")

    info(f"Original geometry  : {geom_str(original)}")
    if after_left:
        info(f"After tile-left    : {geom_str(after_left)}")
    if after_right:
        info(f"After tile-right   : {geom_str(after_right)}")

    head("═══ Done ════════════════════════════════════════════════════════")
    loop.quit()


if __name__ == "__main__":
    main()
