#!/usr/bin/env python3
# =============================================================================
# kwin_dbus_callback_test.py
# Generated by: Claude Sonnet 4.6
#
# PURPOSE:
#   Tests whether a KWin JS script can call back to a Python-registered
#   D-Bus service using callDBus().
#
#   If this works, it becomes the communication channel for kwin_window_probe:
#     - No file I/O
#     - No journal parsing
#     - Pure event-driven D-Bus round-trip
#
# USAGE:
#   python3 kwin_dbus_callback_test.py
#
# REQUIREMENTS:
#   python313-pydbus   python313-gobject  (for GLib main loop)
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



import json
import os
import sys
import tempfile
import threading
import time

from pydbus import SessionBus
from gi.repository import GLib

# ── D-Bus service that the KWin script will call back into ────────────────────

RECEIVER_SERVICE   = "org.probe.KWinReceiver"
RECEIVER_PATH      = "/Receiver"
KWIN_SERVICE       = "org.kde.KWin"
SCRIPTING_PATH     = "/Scripting"

# pydbus uses the XML string to know what interface to publish.
RECEIVER_XML = """
<node>
  <interface name='org.probe.KWinReceiver'>
    <method name='receiveSnapshot'>
      <arg type='s' name='json_data' direction='in'/>
    </method>
    <method name='ping'>
      <arg type='s' name='message' direction='in'/>
    </method>
  </interface>
</node>
"""


class KWinReceiver:
    """
    D-Bus object that KWin scripts call back into.
    pydbus publishes this on the session bus.
    """
    dbus = RECEIVER_XML

    def __init__(self):
        self.received:   list[dict] = []
        self.ping_received           = threading.Event()
        self.snapshot_received       = threading.Event()

    def ping(self, message: str) -> None:
        """Simple round-trip test — KWin calls this first."""
        print(f"  [D-Bus] ping() received: {message!r}")
        self.ping_received.set()

    def receiveSnapshot(self, json_data: str) -> None:
        """KWin script calls this with JSON-encoded window list."""
        print(f"  [D-Bus] receiveSnapshot() received ({len(json_data)} bytes)")
        try:
            data = json.loads(json_data)
            self.received = data.get("windows", [])
        except json.JSONDecodeError as exc:
            print(f"  [D-Bus] JSON parse error: {exc}")
            print(f"  [D-Bus] Raw data: {json_data[:200]}")
        self.snapshot_received.set()


def main() -> None:
    bus      = SessionBus()
    receiver = KWinReceiver()

    # ── Publish our receiver service on the session bus ───────────────────────
    print("Registering D-Bus receiver service ...")
    try:
        # bus.publish() returns a registration handle; keep it alive
        registration = bus.publish(RECEIVER_SERVICE, (RECEIVER_PATH, receiver))
        print(f"  Published as '{RECEIVER_SERVICE}' at '{RECEIVER_PATH}'")
    except Exception as exc:
        print(f"ERROR: Cannot publish D-Bus service: {exc}")
        print("       Is another instance of this script already running?")
        sys.exit(1)

    # ── Run GLib main loop in a background thread ─────────────────────────────
    # pydbus requires a GLib main loop to dispatch incoming D-Bus calls.
    # We run it in a daemon thread so it doesn't block the main thread.
    loop = GLib.MainLoop()
    loop_thread = threading.Thread(target=loop.run, daemon=True)
    loop_thread.start()
    print("  GLib main loop running in background thread")

    # ── Connect to KWin scripting ─────────────────────────────────────────────
    scripting = bus.get(KWIN_SERVICE, SCRIPTING_PATH)
    print(f"  Connected to {KWIN_SERVICE} /Scripting")

    # ── Write the KWin test script ────────────────────────────────────────────
    js_fd, js_path = tempfile.mkstemp(suffix=".js", prefix="kwin_cbtest_")
    os.close(js_fd)

    js_script = f"""
// KWin callback test script
// Tests callDBus() back to Python receiver at {RECEIVER_SERVICE}

var service   = "{RECEIVER_SERVICE}";
var path      = "{RECEIVER_PATH}";
var iface     = "org.probe.KWinReceiver";

// Step 1: simple ping to verify callDBus works at all
try {{
    callDBus(service, path, iface, "ping", "hello from KWin script");
    print("kwin_cbtest: ping sent via callDBus");
}} catch(e) {{
    print("kwin_cbtest: callDBus ping FAILED: " + String(e));
}}

// Step 2: enumerate windows and send as JSON
try {{
    var windows = workspace.windowList();
    var results = [];
    for (var i = 0; i < windows.length; i++) {{
        var w = windows[i];
        results.push({{
            internalId:      String(w.internalId      || ""),
            resourceClass:   String(w.resourceClass   || ""),
            resourceName:    String(w.resourceName    || ""),
            caption:         String(w.caption         || ""),
            desktopFileName: String(w.desktopFileName || ""),
            pid:             Number(w.pid             || 0),
            x:               Number(w.x               || 0),
            y:               Number(w.y               || 0),
            width:           Number(w.width           || 0),
            height:          Number(w.height          || 0),
            minimized:       Boolean(w.minimized),
            maximized:       Boolean(w.maximized),
            fullScreen:      Boolean(w.fullScreen),
            onAllDesktops:   Boolean(w.onAllDesktops),
        }});
    }}
    var payload = JSON.stringify({{ windows: results }});
    callDBus(service, path, iface, "receiveSnapshot", payload);
    print("kwin_cbtest: snapshot sent, " + results.length + " windows");
}} catch(e) {{
    print("kwin_cbtest: snapshot callDBus FAILED: " + String(e));
}}
"""

    with open(js_path, "w") as f:
        f.write(js_script)
    print(f"\nKWin script written to: {js_path}")

    # ── Load and run the script ───────────────────────────────────────────────
    print("Loading KWin script ...")
    try:
        script_id = scripting.loadScript(js_path)
        scripting.start()
        print(f"  Script loaded (ID: {script_id}), start() called")
    except Exception as exc:
        print(f"ERROR: Failed to load script: {exc}")
        loop.quit()
        os.unlink(js_path)
        sys.exit(1)

    # ── Wait for ping callback ────────────────────────────────────────────────
    print("\nWaiting for ping callback (up to 3s) ...")
    if receiver.ping_received.wait(timeout=3.0):
        print("  SUCCESS: ping round-trip confirmed — callDBus() works!")
    else:
        print("  TIMEOUT: ping not received.")
        print("  callDBus() may not be available in this KWin scripting context.")
        print("  Check journal:  journalctl -b | grep kwin_cbtest")
        loop.quit()
        try:
            scripting.unloadScript(str(script_id))
        except Exception:
            pass
        os.unlink(js_path)
        sys.exit(1)

    # ── Wait for snapshot callback ────────────────────────────────────────────
    print("Waiting for snapshot callback (up to 3s) ...")
    if receiver.snapshot_received.wait(timeout=3.0):
        windows = receiver.received
        print(f"  SUCCESS: received {len(windows)} windows via D-Bus callback\n")

        # Display a sample
        for i, w in enumerate(windows[:6]):
            rc  = w.get("resourceClass", "?")
            cap = w.get("caption",       "?")[:45]
            pid = w.get("pid",            0)
            uid = w.get("internalId",    "?")
            print(f"  [{i}]  {rc:<30}  pid={pid:<7}")
            print(f"        caption='{cap}'")
            print(f"        internalId={uid}")
        if len(windows) > 6:
            print(f"  ... and {len(windows) - 6} more")
    else:
        print("  TIMEOUT: snapshot not received within 3s.")

    # ── Cleanup ───────────────────────────────────────────────────────────────
    try:
        scripting.unloadScript(str(script_id))
        print(f"\nScript ID {script_id} unloaded.")
    except Exception as exc:
        print(f"\nUnload notice (non-fatal): {exc}")

    loop.quit()
    os.unlink(js_path)
    registration.unpublish()
    print("D-Bus service unpublished.")
    print("\nDone.")


if __name__ == "__main__":
    main()
