#!/usr/bin/env python3
# =============================================================================
# kwin_introspect.py
# Generated by: Claude Sonnet 4.6
#
# Walks the entire org.kde.KWin D-Bus object tree and prints every
# non-standard interface and method found.  Used to discover what
# KWin actually exposes on this version of Plasma.
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from pydbus import SessionBus
import xml.etree.ElementTree as ET

bus = SessionBus()

SKIP_PREFIXES = (
    "org.freedesktop.DBus",
    "org.freedesktop.DBus.Properties",
    "org.freedesktop.DBus.Introspectable",
    "org.freedesktop.DBus.Peer",
)


def introspect_path(path: str, depth: int = 0) -> None:
    indent = "  " * depth
    try:
        obj  = bus.get("org.kde.KWin", path)
        xml  = obj.Introspect()
        root = ET.fromstring(xml)

        # Print methods on non-standard interfaces
        for iface in root.findall("interface"):
            iface_name = iface.attrib["name"]
            if any(iface_name.startswith(p) for p in SKIP_PREFIXES):
                continue

            methods = iface.findall("method")
            signals = iface.findall("signal")
            props   = iface.findall("property")

            if methods or signals or props:
                print(f"\n{indent}PATH : {path}")
                print(f"{indent}IFACE: {iface_name}")

            for m in methods:
                in_args  = [
                    a.attrib.get("name", a.attrib.get("type", "?"))
                    for a in m.findall("arg")
                    if a.attrib.get("direction", "in") == "in"
                ]
                out_args = [
                    a.attrib.get("name", a.attrib.get("type", "?"))
                    for a in m.findall("arg")
                    if a.attrib.get("direction") == "out"
                ]
                sig = ", ".join(in_args)
                ret = f" -> {', '.join(out_args)}" if out_args else ""
                print(f"{indent}  method  {m.attrib['name']}({sig}){ret}")

            for s in signals:
                sig_args = [
                    a.attrib.get("name", a.attrib.get("type", "?"))
                    for a in s.findall("arg")
                ]
                print(f"{indent}  signal  {s.attrib['name']}({', '.join(sig_args)})")

            for p in props:
                access = p.attrib.get("access", "?")
                ptype  = p.attrib.get("type", "?")
                print(f"{indent}  prop    {p.attrib['name']}  [{ptype}]  ({access})")

        # Recurse into child paths declared in this node
        for node in root.findall("node"):
            child = node.attrib.get("name")
            if child:
                sep        = "" if path.endswith("/") else "/"
                child_path = f"{path}{sep}{child}"
                introspect_path(child_path, depth + 1)

    except Exception as exc:
        print(f"{indent}[skip] {path}: {exc}")


print("=" * 64)
print("KWin D-Bus object tree")
print("=" * 64)
introspect_path("/")
print("\n" + "=" * 64)
print("Done.")
