#!/usr/bin/env python3
# =============================================================================
# docs/dev/kwin_click.py
# Generated by: Claude Sonnet 4.6
#
# PURPOSE
# -------
# Visual test for the coordinate math used by {WCLICK} tokens in
# kwin_restore.py input_actions injection.
#
# Shows a 1000×1000 window with a dot grid every 25 px.  When the user
# clicks anywhere inside the window:
#   - A 48 px red filled circle with white crosshair is drawn at the
#     click position and fades out after 1 second.
#   - The title bar updates to show both window-relative and absolute
#     compositor coordinates of the click.
#
# This directly simulates what kwin_restore.py does for {WCLICK x, y}:
#
#     abs_x = window_x + x
#     abs_y = window_y + y
#     NotifyPointerMotionAbsolute(abs_x, abs_y)
#
# Qt's mapToGlobal() returns the same absolute compositor coordinate.
# If the dot appears exactly where you clicked, the math is correct and
# {WCLICK} tokens will land where they should during a restore.
#
# No child process or ClickIndicator is used — all painting is done
# directly on the canvas to avoid Wayland input-blocking issues.
#
# USAGE
# -----
#   python3 docs/dev/kwin_click.py
#
# REQUIREMENTS
#   PyQt6   (sudo zypper install python313-qt6)
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



from __future__ import annotations

import sys

from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget
from PyQt6.QtCore    import Qt, QTimer, QPoint
from PyQt6.QtGui     import QPainter, QColor, QPen, QBrush


# ── Constants ─────────────────────────────────────────────────────────────────

WINDOW_SIZE    = 1000   # width and height of the canvas
GRID_SPACING   = 25     # pixels between grid dots
GRID_DOT_R     = 2      # radius of each grid dot
DOT_DIAMETER   = 48     # diameter of click indicator dot
DOT_DURATION   = 1000   # ms each click dot stays visible
BG_COL         = QColor("#1e1e1e")
GRID_COL       = QColor("#888888")
DOT_COL        = QColor("#FF2222")
CROSS_COL      = QColor("#ffffff")


# ── Canvas ────────────────────────────────────────────────────────────────────

class ClickCanvas(QWidget):
    """
    Grid canvas that draws a timed red dot wherever the user clicks.
    Each dot lives for DOT_DURATION ms then disappears.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setFixedSize(WINDOW_SIZE, WINDOW_SIZE)
        # List of active dots: {"x": int, "y": int} in canvas-local coords
        self._dots: list[dict] = []

    def mousePressEvent(self, event) -> None:  # type: ignore[override]
        rel_x = event.pos().x()
        rel_y = event.pos().y()

        # Absolute compositor coordinates — same calculation as inject_actions()
        abs_pt = self.mapToGlobal(event.pos())
        abs_x  = abs_pt.x()
        abs_y  = abs_pt.y()

        # Update title bar
        self.window().setWindowTitle(
            f"kwin_click  —  rel({rel_x}, {rel_y})  abs({abs_x}, {abs_y})"
        )

        # Add dot at canvas-local coords
        entry: dict = {"x": rel_x, "y": rel_y}
        self._dots.append(entry)
        self.update()

        # Schedule removal after DOT_DURATION ms
        t = QTimer(self)
        t.setSingleShot(True)
        def remove(e=entry):
            try:
                self._dots.remove(e)
            except ValueError:
                pass
            self.update()
        t.timeout.connect(remove)
        t.start(DOT_DURATION)

    def paintEvent(self, event) -> None:  # type: ignore[override]
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)

        # Background
        painter.fillRect(self.rect(), BG_COL)

        # Grid dots
        painter.setBrush(QBrush(GRID_COL))
        painter.setPen(Qt.PenStyle.NoPen)
        x = GRID_SPACING
        while x < WINDOW_SIZE:
            y = GRID_SPACING
            while y < WINDOW_SIZE:
                painter.drawEllipse(
                    x - GRID_DOT_R, y - GRID_DOT_R,
                    GRID_DOT_R * 2, GRID_DOT_R * 2,
                )
                y += GRID_SPACING
            x += GRID_SPACING

        # Click dots
        d   = DOT_DIAMETER
        r   = d // 2
        arm = r - 4
        for dot in self._dots:
            cx = dot["x"]
            cy = dot["y"]

            # Filled red circle
            painter.setBrush(QBrush(DOT_COL))
            painter.setPen(Qt.PenStyle.NoPen)
            painter.drawEllipse(cx - r, cy - r, d, d)

            # White crosshair
            pen = QPen(CROSS_COL)
            pen.setWidth(2)
            painter.setPen(pen)
            painter.drawLine(cx,       cy - arm, cx,       cy + arm)
            painter.drawLine(cx - arm, cy,       cx + arm, cy)

        painter.end()


# ── Main window ───────────────────────────────────────────────────────────────

class MainWindow(QMainWindow):
    def __init__(self) -> None:
        super().__init__()
        self.setWindowTitle("kwin_click  —  click anywhere")
        self.setCentralWidget(ClickCanvas(self))
        self.setFixedSize(WINDOW_SIZE, WINDOW_SIZE)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    app = QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
