#!/usr/bin/env python3
# =============================================================================
# kwin_script_test.py
# Generated by: Claude Sonnet 4.6
#
# PURPOSE:
#   Tests the KWin scripting interface (/Scripting) to verify:
#     1. We can load a JS script via D-Bus
#     2. The script can enumerate workspace.windowList()
#     3. The script can write results to a temp file
#     4. We can unload the script afterwards
#
#   This is a prerequisite test before rewriting kwin_window_probe.py
#   to use the scripting approach.
#
# USAGE:
#   python3 kwin_script_test.py
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



import json
import os
import sys
import tempfile
import time

from pydbus import SessionBus

KWIN_SERVICE   = "org.kde.KWin"
SCRIPTING_PATH = "/Scripting"
PLUGIN_NAME    = "org.probe.kwin_test"   # used for unload only if supported


def main() -> None:

    bus = SessionBus()

    # ── Connect to /Scripting ─────────────────────────────────────────────────
    try:
        scripting = bus.get(KWIN_SERVICE, SCRIPTING_PATH)
    except Exception as exc:
        print(f"ERROR: Cannot connect to /Scripting: {exc}")
        sys.exit(1)

    print("Connected to org.kde.KWin /Scripting")

    # ── Create temp files ─────────────────────────────────────────────────────
    # Output file the KWin script will write results into
    out_fd, out_path = tempfile.mkstemp(suffix=".json", prefix="kwin_probe_")
    os.close(out_fd)

    # The KWin JS script itself
    js_fd, js_path = tempfile.mkstemp(suffix=".js", prefix="kwin_script_")
    os.close(js_fd)

    print(f"Output file : {out_path}")
    print(f"Script file : {js_path}")

    # ── Write the KWin JavaScript ─────────────────────────────────────────────
    # KWin scripts run in a QJSEngine context with a 'workspace' global.
    # workspace.windowList() returns all current windows.
    # Each window object exposes: resourceClass, resourceName, caption,
    #   desktopFileName, pid, desktopWindow, x, y, width, height,
    #   minimized, maximized, fullScreen, onAllDesktops, internalId, etc.
    #
    # For file I/O we use Qt.createQmlObject to get a FileIO helper,
    # OR we try the readFile/writeFile globals that some KWin versions expose.
    # We try both approaches and report which worked.

    js_script = f"""
// KWin diagnostic script — enumerate all windows and write to file
// Output path: {out_path}

var outputPath = "{out_path}";
var results = [];

try {{
    var windows = workspace.windowList();
    for (var i = 0; i < windows.length; i++) {{
        var w = windows[i];
        try {{
            results.push({{
                internalId:      String(w.internalId      || ""),
                resourceClass:   String(w.resourceClass   || ""),
                resourceName:    String(w.resourceName    || ""),
                caption:         String(w.caption         || ""),
                desktopFileName: String(w.desktopFileName || ""),
                pid:             Number(w.pid             || 0),
                x:               Number(w.x               || 0),
                y:               Number(w.y               || 0),
                width:           Number(w.width           || 0),
                height:          Number(w.height          || 0),
                minimized:       Boolean(w.minimized),
                maximized:       Boolean(w.maximized),
                fullScreen:      Boolean(w.fullScreen),
                onAllDesktops:   Boolean(w.onAllDesktops),
            }});
        }} catch(we) {{
            results.push({{ error: String(we), index: i }});
        }}
    }}
}} catch(e) {{
    results = [{{ fatalError: String(e) }}];
}}

// Attempt 1: writeFile() global (available in some KWin versions)
var writeOk = false;
try {{
    writeFile(outputPath, JSON.stringify({{ method: "writeFile", windows: results }}, null, 2));
    writeOk = true;
}} catch(e1) {{
    // Attempt 2: callDBus to write via external helper is too complex for a test.
    // Record the error in the filename itself as a last resort signal.
    try {{
        // Some KWin versions expose a file write through Qt
        var f = Qt.createQmlObject('import QtQml 2.0; QtObject {{ }}', workspace);
        writeFile(outputPath, JSON.stringify({{ method: "writeFile_retry", windows: results }}));
        writeOk = true;
    }} catch(e2) {{
        // Neither method worked — write error info so Python knows
        // We can't write the file, but we signal failure by leaving it empty
        print("kwin_probe: writeFile not available: " + String(e1));
        print("kwin_probe: window count = " + results.length);
        // Write results via print() to journal as fallback
        print("kwin_probe: RESULTS_JSON=" + JSON.stringify({{ method: "journal", windows: results }}));
    }}
}}

if (writeOk) {{
    print("kwin_probe: wrote " + results.length + " windows to " + outputPath);
}}
"""

    with open(js_path, "w") as f:
        f.write(js_script)

    print(f"\nKWin script written ({len(js_script)} bytes)")

    # ── Load and run the script ───────────────────────────────────────────────
    # The two-argument overload (filePath, pluginName) exists in the
    # introspection XML but pydbus resolves to the single-argument form,
    # so we use that.  The returned integer ID is used to unload later.
    print(f"\nLoading script via /Scripting ...")
    script_id = None
    try:
        script_id = scripting.loadScript(js_path)
        print(f"loadScript() returned ID: {script_id}")
    except Exception as exc:
        print(f"ERROR: loadScript() failed: {exc}")
        cleanup(js_path, out_path)
        sys.exit(1)

    # Scripts need to be explicitly started after loading
    try:
        scripting.start()
        print("start() called on scripting engine")
    except Exception as exc:
        print(f"  (start() not needed or failed: {exc})")

    # ── Wait for the script to execute ────────────────────────────────────────
    print("\nWaiting for script execution (up to 3s) ...")
    deadline = time.monotonic() + 3.0
    file_written = False
    while time.monotonic() < deadline:
        time.sleep(0.1)
        size = os.path.getsize(out_path)
        if size > 0:
            file_written = True
            print(f"Output file populated after "
                  f"{3.0 - (deadline - time.monotonic()):.2f}s  ({size} bytes)")
            break

    # ── Read and display results ──────────────────────────────────────────────
    print()
    if file_written:
        with open(out_path) as f:
            data = json.load(f)

        method  = data.get("method", "unknown")
        windows = data.get("windows", [])

        print(f"SUCCESS — file write method: '{method}'")
        print(f"Windows found by KWin script: {len(windows)}")
        print()

        # Show first 5 windows as a sample
        for i, w in enumerate(windows[:5]):
            if "fatalError" in w or "error" in w:
                print(f"  [{i}] ERROR: {w}")
            else:
                rc  = w.get("resourceClass", "?")
                cap = w.get("caption", "?")[:40]
                pid = w.get("pid", 0)
                uid = w.get("internalId", "?")
                print(f"  [{i}]  {rc:<25}  pid={pid:<7}  caption='{cap}'")
                print(f"        internalId={uid}")

        if len(windows) > 5:
            print(f"  ... and {len(windows) - 5} more")

    else:
        print("NOTICE: Output file was NOT written by the script.")
        print("        writeFile() is not available in this KWin scripting environment.")
        print()
        print("Check the KWin journal output for 'kwin_probe:' lines:")
        print("  journalctl -b | grep kwin_probe")
        print()
        print("If RESULTS_JSON appears in the journal, we'll use the journal")
        print("as the communication channel instead of a file.")

    # ── Unload the script ─────────────────────────────────────────────────────
    # unloadScript() takes the plugin name string per the introspection XML,
    # but since we loaded without a name we try the ID approach too.
    try:
        if script_id is not None:
            scripting.unloadScript(str(script_id))
        print(f"\nScript ID {script_id} unloaded cleanly.")
    except Exception as exc:
        print(f"\nUnload notice (non-fatal): {exc}")

    cleanup(js_path, out_path)


def cleanup(js_path: str, out_path: str) -> None:
    for p in (js_path, out_path):
        try:
            os.unlink(p)
        except OSError:
            pass


if __name__ == "__main__":
    main()
