#!/usr/bin/env python3
# =============================================================================
# docs/dev/portal_keyboard_test.py
# Generated by: Claude Sonnet 4.6
#
# Tests XDG RemoteDesktop portal keyboard injection.
#
# Flow:
#   1. CreateSession
#   2. SelectDevices (KEYBOARD, persist_mode=2 for one-time dialog)
#   3. Start   ← KDE shows "Allow wayland-desktop to control input?" dialog
#   4. NotifyKeyboardKeycode — sends 't' to focused window
#
# On first run: KDE dialog appears, click Allow.
# On subsequent runs: restore_token skips the dialog.
#
# Usage:
#   python3 docs/dev/portal_keyboard_test.py
# =============================================================================
#
# do not edit: begin
#
# Wayland Desktop Setup
# Plasma6 Session Restore for Wayland, including input injection
#
# Copyright © 2026 by Sam Azer<sam dot azer at azertech dot net>, All rights reserved.
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU
# General Public License](LICENSE.md) for more details.
#
# You should have received a copy of the [GNU General Public
# License](LICENSE.md) along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# do not edit: end
#
# =============================================================================



import os
import sys
import time
import random
import string
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))

from gi.repository import GLib, Gio

PORTAL_BUS  = "org.freedesktop.portal.Desktop"
PORTAL_PATH = "/org/freedesktop/portal/desktop"
PORTAL_RD   = "org.freedesktop.portal.RemoteDesktop"
PORTAL_REQ  = "org.freedesktop.portal.Request"
PORTAL_SESS = "org.freedesktop.portal.Session"

# Device type flags
DEVICE_KEYBOARD = 1
DEVICE_POINTER  = 2

TOKEN_FILE = Path("~/.config/wayland-desktop/portal_session_token").expanduser()


def _token(n=8):
    """Random handle token — must be a valid D-Bus object path element."""
    return "".join(random.choices(string.ascii_lowercase, k=n))


def _sender_path_component(conn):
    """
    D-Bus unique name ':1.123' → '1_123'
    Used as the sender segment of a portal request object path:
      /org/freedesktop/portal/desktop/request/{sender}/{token}
    """
    return conn.get_unique_name().lstrip(":").replace(".", "_")


def run_portal_keyboard_test():
    print("=== Portal Keyboard Test ===\n")

    conn = Gio.bus_get_sync(Gio.BusType.SESSION, None)
    loop = GLib.MainLoop()

    session_path = None
    restore_token_in = None

    # Load saved restore token if available
    if TOKEN_FILE.exists():
        restore_token_in = TOKEN_FILE.read_text().strip()
        print(f"[INFO] Loaded restore token: {restore_token_in[:16]}...")
    else:
        print("[INFO] No saved token — dialog will appear")

    # ── Step 1: CreateSession (async — wait for Response signal) ─────────────
    print("\n--- Step 1: CreateSession ---")
    sess_token  = _token()   # becomes the session handle path element
    req_token0  = _token()   # becomes the request handle path element
    sender_part = _sender_path_component(conn)
    req_path0   = f"/org/freedesktop/portal/desktop/request/{sender_part}/{req_token0}"

    create_result = [None]

    def on_create_response(conn2, sender, obj_path, iface, signal, params, user_data):
        response, results = params
        create_result[0] = (response, dict(results))
        loop.quit()

    sub_id0 = conn.signal_subscribe(
        PORTAL_BUS, PORTAL_REQ, "Response",
        req_path0, None,
        Gio.DBusSignalFlags.NONE,
        on_create_response, None,
    )

    conn.call_sync(
        PORTAL_BUS, PORTAL_PATH, PORTAL_RD,
        "CreateSession",
        GLib.Variant("(a{sv})", ({
            "handle_token":         GLib.Variant("s", req_token0),
            "session_handle_token": GLib.Variant("s", sess_token),
        },)),
        GLib.VariantType("(o)"),
        Gio.DBusCallFlags.NONE, -1, None,
    )

    GLib.timeout_add_seconds(10, loop.quit)
    loop.run()
    conn.signal_unsubscribe(sub_id0)

    resp0, res0 = create_result[0] or (1, {})
    print(f"[{'OK' if resp0 == 0 else 'FAIL'}] CreateSession response={resp0}  results={res0}")
    if resp0 != 0:
        print("CreateSession failed — aborting")
        return

    session_path = res0.get("session_handle")
    if not session_path:
        print(f"[ERROR] No session_handle in results: {res0}")
        return
    print(f"[OK] session_path: {session_path}")

    # ── Step 2: SelectDevices (async — wait for Response signal) ─────────────
    print("\n--- Step 2: SelectDevices ---")
    req_token = _token()
    req_path  = f"/org/freedesktop/portal/desktop/request/{sender_part}/{req_token}"

    select_result = [None]
    select_done   = [False]

    def on_select_response(conn2, sender, obj_path, iface, signal, params, user_data):
        response, results = params
        select_result[0] = (response, dict(results))
        select_done[0]   = True
        loop.quit()

    sub_id = conn.signal_subscribe(
        PORTAL_BUS, PORTAL_REQ, "Response",
        req_path, None,
        Gio.DBusSignalFlags.NONE,
        on_select_response, None,
    )

    options = {
        "handle_token": GLib.Variant("s", req_token),
        "types":        GLib.Variant("u", DEVICE_KEYBOARD),
        "persist_mode": GLib.Variant("u", 2),
    }
    if restore_token_in:
        options["restore_token"] = GLib.Variant("s", restore_token_in)

    conn.call_sync(
        PORTAL_BUS, PORTAL_PATH, PORTAL_RD,
        "SelectDevices",
        GLib.Variant("(oa{sv})", (session_path, options)),
        GLib.VariantType("(o)"),
        Gio.DBusCallFlags.NONE, -1, None,
    )

    # Wait for Response (timeout 30s)
    GLib.timeout_add_seconds(30, loop.quit)
    loop.run()
    conn.signal_unsubscribe(sub_id)

    resp, res = select_result[0] or (1, {})
    print(f"[{'OK' if resp == 0 else 'FAIL'}] SelectDevices response={resp}  results={res}")
    if resp != 0:
        print("SelectDevices rejected — aborting")
        return

    # ── Step 3: Start (shows dialog if no valid restore token) ────────────────
    print("\n--- Step 3: Start ---")
    print("(If the KDE dialog appears, click 'Allow')")

    req_token2 = _token()
    req_path2  = f"/org/freedesktop/portal/desktop/request/{sender_part}/{req_token2}"

    start_result = [None]
    start_done   = [False]

    def on_start_response(conn2, sender, obj_path, iface, signal, params, user_data):
        response, results = params
        start_result[0] = (response, dict(results))
        start_done[0]   = True
        loop.quit()

    sub_id2 = conn.signal_subscribe(
        PORTAL_BUS, PORTAL_REQ, "Response",
        req_path2, None,
        Gio.DBusSignalFlags.NONE,
        on_start_response, None,
    )

    conn.call_sync(
        PORTAL_BUS, PORTAL_PATH, PORTAL_RD,
        "Start",
        GLib.Variant("(osa{sv})", (
            session_path,
            "",   # parent_window — empty for non-GTK/Qt apps
            {"handle_token": GLib.Variant("s", req_token2)},
        )),
        GLib.VariantType("(o)"),
        Gio.DBusCallFlags.NONE, -1, None,
    )

    # Wait for Response (timeout 60s — user needs time to click Allow)
    GLib.timeout_add_seconds(60, loop.quit)
    loop.run()
    conn.signal_unsubscribe(sub_id2)

    resp2, res2 = start_result[0] or (1, {})
    print(f"[{'OK' if resp2 == 0 else 'FAIL'}] Start response={resp2}")
    if resp2 != 0:
        print("Start rejected or timed out — aborting")
        return

    # Save restore token if provided
    new_token = res2.get("restore_token")
    if new_token:
        TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
        TOKEN_FILE.write_text(str(new_token))
        print(f"[OK] Restore token saved: {str(new_token)[:16]}...")
    else:
        print("[INFO] No restore token in response (may not be supported by this KDE version)")

    # ── Step 4: Send a keystroke ──────────────────────────────────────────────
    print("\n--- Step 4: Send keystroke ---")
    print("Sending 't' (keycode 20) to the focused window in 2 seconds...")
    print("Focus a terminal or text editor now!")
    time.sleep(2)

    try:
        # state=1 = pressed, state=0 = released
        conn.call_sync(
            PORTAL_BUS, PORTAL_PATH, PORTAL_RD,
            "NotifyKeyboardKeycode",
            GLib.Variant("(oa{sv}iu)", (session_path, {}, 20, 1)),
            None,
            Gio.DBusCallFlags.NONE, -1, None,
        )
        conn.call_sync(
            PORTAL_BUS, PORTAL_PATH, PORTAL_RD,
            "NotifyKeyboardKeycode",
            GLib.Variant("(oa{sv}iu)", (session_path, {}, 20, 0)),
            None,
            Gio.DBusCallFlags.NONE, -1, None,
        )
        print("[OK] Keystroke sent — did a 't' appear?")
    except Exception as e:
        print(f"[ERROR] NotifyKeyboardKeycode failed: {e}")

    # ── Step 5: Close session ─────────────────────────────────────────────────
    print("\n--- Step 5: Close session ---")
    try:
        conn.call_sync(
            PORTAL_BUS, session_path, PORTAL_SESS,
            "Close",
            GLib.Variant("()", ()),
            None,
            Gio.DBusCallFlags.NONE, -1, None,
        )
        print("[OK] Session closed")
    except Exception as e:
        print(f"[INFO] Close: {e} (non-fatal)")

    print("\n=== Done ===")


if __name__ == "__main__":
    run_portal_keyboard_test()
